### ISSUE TITLE
Default look on My Deck page not loading anything. 

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#1]
Since last 3-4 days, trying to open the My Decks page (https://mtgarena.pro/decks/#my) results in endlessly loading with nothing loaded. If I click the Available / Unavailable buttons the decks reappear, but it seems the default look is broken. 

Also trying to switch to other pages beyond first causes endless loading, too.

**Comment by Razviar** [comment]
Fixed
