### ISSUE TITLE
Public history queries - does this deck face card X?

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#100]
This is a brainstorm proposal subject so any input is welcome before it is finalized.

One way of guessing if a deck would face powerful opponents is being able to look at the cards that this deck plays against. "Does this deck face Goblin Chainwhirler?" is a really reliable way to guess if a deck is selected to play against power cards, or against specific archetype that these staple cards appear in. 

Once we implement public data, would be really useful if a user can check if a deck faces one or several cards, and receive an answer what percentage of decks it has matched have played these cards.

Example:

Let's say that you really want to avoid a Mono Red Aggro deck with Steam-Kin & Goblin Chainwhirler. You look at a new powerful deck and wonder, will this deck be matched againt Mono Red Aggro?

You supply several card names (Steam-Kin, Chainwhirler) and you receive data that 27% of matched opponents for that deck have played these cards. This is clearly a power level deck, being fairly badly matched against Mono Red Aggro. You want to avoid this deck.

For example you see a nice performing Merfolk deck. You do the same check (Steam-Kin, Chainwhirler) and you get 0.7%. This deck is absolutely Casual ranked, it never matches Mono Red (maybe occasional match vs Steam-Kin, but never Chainwhirler) and that is a deck you want to play away from the meta. 

But then you check (Ajani Pridemate) and you see 31%, wow - that deck is regularly matched againast White Lifegain combo. You need to ensure that this deck gets Sideboard with Dispersal and Waterknot for locking Ajani Pridemate, etc.

**Comment by apoapostolov** [comment]
Very nice. This UI approach should provide the needed tools for players to estimate what to expect from a deck during last meta (data should be since the release of the last set) before they commit to build it.

**Comment by Razviar** [comment]
Done
