### ISSUE TITLE
Weird numbers in Matches Results

### ISSUE THREAD

**Issue by ParanoikCZE** [Razviar/mtga-pro-tracker#103]
When I went to my stats, I've ran into weird sums in my daily games. See screen.
Played with two decks, total 29:29, above, you can see 29:30, below 30:29. Seems like one game is somehow invalid.

![obrazek](https://user-images.githubusercontent.com/19796452/47271081-0c5b4c80-d575-11e8-9122-c610dd75c11f.png)

STR:
https://mtgarena.pro/u/Qawaya see stats for Oct 20.

**Comment by Razviar** [comment]
I'm trying to locate this floating bug, no luck for now.

**Comment by ParanoikCZE** [comment]
Maybe this could help. There is 11PM (CET) and this last match was calculated to next day .. 
Another funny behavior occured.
![obrazek](https://user-images.githubusercontent.com/19796452/47390627-22edd900-d718-11e8-9a74-c5e8f21c29eb.png)
