### ISSUE TITLE
Installation issue with ToastActivator

### ISSUE THREAD

**Issue by MahBoiiii** [Razviar/mtga-pro-tracker#104]
Hello!

I recently wanted to try out this app, but when running the installer I'm getting the attached error.  The installer completes after this, however whenever I attempt to run the application, it immediately crashes with a "MTGApro has stopped working" windows prompt.

I'm currently running on Win7, and have tried placing the target directory for the install on a number of different drives.

Any help would be great.
Thanks!

![image](https://user-images.githubusercontent.com/18168987/47328406-05007580-d63f-11e8-9335-5cfe9543a7f6.png)

**Comment by Razviar** [comment]
It's normal behavior of installer. Just click OK and it will keep installing. 
App crashes because you don't have 4.6.2. .NET framework. Please refer to installation manual and troubleshooting part of download page: https://mtgarena.pro/mtga-pro-tracker/
