### ISSUE TITLE
Progress not loading anything

### ISSUE THREAD

**Issue by tonyharney** [Razviar/mtga-pro-tracker#110]
I have played a game with the tracker loaded and all of the tabs populate data except for the Progress option.  It pulls up a blank page and gives me no information about my collection status, gold/gem information, or vault progress.  I can see a brief summary of some information under My Profile, but nothing under Progress.

**Comment by Razviar** [comment]
Please give me a link to your Progress page (with #Nick)

**Comment by tonyharney** [comment]
mtga.cc/progress/#Skitty

**Comment by tonyharney** [comment]
It looks like the Progress page is now loading information after a second day of adding statistics.  Not sure what triggered it to start working, but it's awesome!  :)

**Comment by Razviar** [comment]
Fixed
