### ISSUE TITLE
Unable to Insert/Embed Media on Profile

### ISSUE THREAD

**Issue by lmichaela94** [Razviar/mtga-pro-tracker#116]
**Describe the bug**
I am unable to type in the MEDIA portion of the "Insert custom text or video" on m profile. I am on Windows 10 and have attempted in Chrome and Firefox.

**To Reproduce**
1. Copy embed code or link to video
2. Go to profile
2. Click on "custom text or video''
3. Click the "+" drop down menu
4. Click "Media"
5. See error, be unable to edit text fields

**Expected behavior**
Ability to edit and insert text into text fields in order to embed video

**Screenshots**
[I uploaded the video here.](https://www.reddit.com/r/MTGArenaPro/comments/9s11ft/cant_insertembed_videos/)

**EDIT/ADDITION**
It turns out when, in the video, I add the embed code to the normal text box, click save, and nothing updates on the profile, that's true for any text entered. I tried adding in plain text just saying "text" and even just the link to my video, clicked Set Content, and nothing popped up, even after a refresh.

**Comment by Razviar** [comment]
Fixed
