### ISSUE TITLE
Open Source The Project

### ISSUE THREAD

**Issue by Nimgoble** [Razviar/mtga-pro-tracker#120]
It would be nice if you open sourced the project so that others can contribute.

**Comment by Spongman** [comment]
agreed. there's lots of easy CPU/memory optimizations that could be made among others. for example, why re-implement `Stream.CopyTo`? why not use `WebClient.UploadValues` ? why does it re-parse the registry stuff all the time?

**Comment by riQQ** [comment]
See #63
