### ISSUE TITLE
Same card from different sets isn't included in dekcs.

### ISSUE THREAD

**Issue by Presac** [Razviar/mtga-pro-tracker#122]
Case:
I'm looking at this deck https://mtgarena.pro/decks/walk-the-plank-dimir/ and noticed it said I didn't have any Grasping Scoundrels, which seems odd as every other cards from the same free deck is unlocked. Under "My Decks Lists" the "same" deck do say I have it https://mtgarena.pro/decks/precon-npe-grn-ub-11220/

Here Grasping Scoundrel is from Guilds of Ravnica
![My deck](https://user-images.githubusercontent.com/10221581/47713511-c1a79780-dc3a-11e8-89b9-eadcc86ea29d.png).

Here it is from Core Set 2019
![Deck from featured list](https://user-images.githubusercontent.com/10221581/47713515-c4a28800-dc3a-11e8-9674-663eb9d436a3.png).

As I see it, the program should check for card name instead of just a specific card from a set. Or are the rules for cards more convoluted than I thought? (new player/only played a week so far)

**Comment by Razviar** [comment]
This is known issue, I'm looking for the most efficient way to handle reprints.

**Comment by starkebn** [comment]
I agree this really needs to happen, perhaps a manually created cross reference database that has just uses the set code and card number
