### ISSUE TITLE
Multiple account collection tracking is not working-Critical

### ISSUE THREAD

**Issue by zuniga-jonathan** [Razviar/mtga-pro-tracker#131]
**Describe the bug**
When using two accounts as specified with different tokens but with same display name collection tracking shows NPE decks being obtained again on older account as well as miss-tracking gold and gem rewards. 

**To Reproduce**
1. Make new alt account with different token but same display name as original 
2. Obtain any decks or boosters or reward cards or gems or gold
3. Check tracked collection and tracked gold/gems. It is updating as if you are obtaining them in both accounts. 

**Expected behavior**
Updates should happen only to each individual account and not both, its impossible to see what cards I've obtained and my collection is now inaccurate.

**Screenshots**
https://i.imgur.com/AvZuFIS.png Screenshot showing miss tracking of gold/gems
https://i.imgur.com/lytIbxF.jpg     Screenshot showing that I obtained white deck again even though im on the 10th day playing so there is no way i can be receiving NPE decks now...

**Additional context**

**Comment by Razviar** [comment]
Just released v.1.3.3 fixes that
