### ISSUE TITLE
Client stops working after some time

### ISSUE THREAD

**Issue by R34P** [Razviar/mtga-pro-tracker#132]
**Describe the bug**
The Client will stop uploading data to the server.
Need to restart it in order for it start working again.

**To Reproduce**
Uknown, I just keep it on for like 20h+

**Expected behavior**
The client can no longer upload data.

**Additional context**
My system is running Windows 10 Pro with 1803

**Comment by apoapostolov** [comment]
@R34P Do you play Competitive Events in order one after another?

**Comment by Razviar** [comment]
Just released v.1.3.3 fixes that
