### ISSUE TITLE
Hey some Prob with my Profile page!

### ISSUE THREAD

**Issue by soblacky** [Razviar/mtga-pro-tracker#135]
**Describe the bug**

**To Reproduce**
1. Go to 'https://mtgarena.pro/u/soblacky'
3. Scroll down to '18.10 then after this scroll up to today!'
4. See error Stop

**Expected behavior**
Hey first my Profile page on MTG Arena Pro:

On this page you see when you scroll down i beginn to play this Game in German my Deck Pic and the Deck name was showing.
But on the last days you see on my page it was ONLY show now numbers not the Deck pic and not the name of my Deck. I test it now on the Firefox Browser and Google Chrom Browser. i delete my Cache but nothing help.
Again for some days it works all fine and i will say again i play this game in german.
When i change the Language in english and import some decks and start the game new all works fine too but when i change in german it stopet to show the name and the pic.
For me for some days some was changing!?
I cant now make decks in german because nothing was show on my Profile page!?
I beginning to play this game on 18.10. and the next days i can make decks in german and all was fine and working. but not in the last days!?
I change my token too but this dont help too!!??
pls help me i think the last update or patch crashed some now to work again good to play this game in german!?!? :)
Greedz and hope you can help me again work all fine to play this game in german and show my Deck names and the pics!? :) :) :)

**Screenshots**

**Additional context**

**Comment by soblacky** [comment]
Hey :) Can now someone help me here or why no Answer or reactions here!? O.o :)

**Comment by Razviar** [comment]
Sorry for late answer, we were having some troubles with new Tracker version roll out. I'll look into this

**Comment by soblacky** [comment]
Ok, would be nice when you can fix it and works again all fine!? :) :)

**Comment by soblacky** [comment]
Hey :) Here you can see what i play today mtga.cc/decks/#soblacky but here on my Profil page https://mtgarena.pro/u/soblacky you see it show i play nothing today!? :) Hope its help you to see whats again a Problem! ^^ :)

**Comment by Razviar** [comment]
You should delete anything, please wait until I figure out what's causing this issue

**Comment by soblacky** [comment]
Ok sry but i will only help you to can fix it!
But i must say sry again i write some wrong here. I see now the last 2 days the tracker show nothing. i look wrong with the date. I think the only reason is i play this game in German!? I talk with some other players and they say to me in they game works all fine! :) :) ok When you have some question here so pls tell me when i can help you to fix it. would be awesome you find it and  works all fine again and i can stay to play this game in german! :) thx and greedz

**Comment by Razviar** [comment]
Got v.1.4.6 update, now we can focus on tiny fixes. I hope your problem will be solved soon

**Comment by soblacky** [comment]
ok today my games were recorded again because the last few days they were not recorded. that's good thank you. Now my pictures and my statistics and I'm happy again! thank for the hard and great work! :)

**Comment by Razviar** [comment]
You are very welcome! Enjoy!

**Comment by soblacky** [comment]
Stop Tracking again last 2 Days!?!?

**Comment by Razviar** [comment]
Read this : https://www.reddit.com/r/MTGArenaPro/comments/9z2ngf/tracker_update_v150_released_21112018_catchup_mode/?utm_source=reddit-android
