### ISSUE TITLE
Problem synced my account to the site

### ISSUE THREAD

**Issue by postglory** [Razviar/mtga-pro-tracker#137]
Hello Razivar,

I have attempted multiple resets of the app and multiple restarts of my PC, I even tried to de sync the game from my steam library with no luck of syncing the game to my account.

this was the error i received.

**Comment by Razviar** [comment]
Just released v.1.3.3 fixes that

**Comment by postglory** [comment]
Thank you so much i will test when i get home. Do you have a paypall account i can send u a few bones for this ( buy you a coffee)?

**Comment by Razviar** [comment]
Hi! You can support us on Patreon if you want to. Here's the link: https://www.patreon.com/bePatron?u=11854215
