### ISSUE TITLE
Error installing MTGA Protracker

### ISSUE THREAD

**Issue by ghost** [Razviar/mtga-pro-tracker#138]
Hi,

When I try to install the lastest version of the soft, it fizzles and I can read this message:

![20181106_124040](https://user-images.githubusercontent.com/44805070/48062675-009d9600-e1c3-11e8-9737-32948f69e691.jpg)

thanks for your help!

**Comment by NachoPr** [comment]
I am having this issue too

**Comment by Razviar** [comment]
Just released v.1.3.3 fixes that

**Comment by monsterguy** [comment]
It installs fine, but I do get that same error message when I install (1.3.3, 1.3.4 & 1.3.5).
I'm not installing to the default directory and I'm using Windows7.

**Comment by Razviar** [comment]
You can click OK and go on with installation. Just ignore error

**Comment by magicman1967** [comment]
I am having the same issue. the first time I just clicked ok and I guess it was ok because the app worked but yesterday when I opened the app it said there was an update. I got the same error message and now the app won't work at all.

**Comment by Razviar** [comment]
> I am having the same issue. the first time I just clicked ok and I guess it was ok because the app worked but yesterday when I opened the app it said there was an update. I got the same error message and now the app won't work at all.

you should download latest app 1.5.1 and follow those steps: https://www.reddit.com/r/MTGArenaPro/comments/9z2ngf/tracker_update_v150_released_21112018_catchup_mode/

**Comment by Razviar** [comment]
Won't do you mean by "won't work"? Do you see app interface? Is there error log in installation directory?

**Comment by magicman1967** [comment]
Not sure? the app itself seems to be working now. thanks for your help.
