### ISSUE TITLE
Upload Failed: update tracker to resume

### ISSUE THREAD

**Issue by TheChesh1reCat** [Razviar/mtga-pro-tracker#141]
"Upload Failed: update tracker to resume" after last update 1.3.5

Can you explain what is going wrong?

No transfer data to the website at all.

**Comment by TheChesh1reCat** [comment]
"Upload Failed: update tracker to resume" after last update 1.3.5

Can you explain what is going wrong?

No transfer data to the website at all.

**Comment by Razviar** [comment]
Unfortunately we had bugged version staged for release. Now we released 1.3.6 which works correctly.
