### ISSUE TITLE
Collection Export error

### ISSUE THREAD

**Issue by lucasenra** [Razviar/mtga-pro-tracker#151]
**Describe the bug**
Clicking Export button on Collection page redirects to an error page instead of giving the requested file.

**To Reproduce**
1. Go to My Arena > Collection
2. Click on 'Export'
3. Click on 'MTGGoldfish CSV'
4. Get redirected to [https://mtgarena.pro/mtg/donew.php](https://mtgarena.pro/mtg/donew.php) (message: "Hacker! Go home!" hahaha)

**Expected behavior**
Get the .csv file for download

**Comment by ToniMarino** [comment]
I'm also getting this bug.

**Comment by Razviar** [comment]
This issue raised after we have switched to new API. We'll fix it very soon

**Comment by Razviar** [comment]
You're not a hacker anymore, it works now :)
