### ISSUE TITLE
Wrong date on profile information

### ISSUE THREAD

**Issue by Hiub** [Razviar/mtga-pro-tracker#153]
Hello,

Since the multiple updates, my profile on the website mtgarena.pro is one day late.

For exemple, everything registered today (November 12th) is presented as yesterday (November 11th) : 
- Gold gain and loss
- Match result
- etc.

![capture](https://user-images.githubusercontent.com/3345628/48337753-24018e80-e664-11e8-9aeb-2cc14f2fab1a.PNG)

Thank you,

**Comment by apoapostolov** [comment]
@Razviar is this related to the change in timezone tracking? If so, this may be one time issue for each user as they get data mixed up before no proper time tracking and now after proper time tracking.

**Comment by apoapostolov** [comment]
I confirm this is a problem since yesterday. This is my Social Feed. I haven't even run the game today and yesterday w/l is credited today as a duplicate

![image](https://user-images.githubusercontent.com/4083812/48359474-b70ee880-e6a5-11e8-85a5-b3071488cc4a.png)

**Comment by Razviar** [comment]
I'll check that
