### ISSUE TITLE
After Match Collection Reports that it isfull

### ISSUE THREAD

**Issue by LonelyHours** [Razviar/mtga-pro-tracker#154]
After playing a match and opening a GRN booster at 9:07pm my profile page says that I suddenly completed my collection.

![image](https://user-images.githubusercontent.com/17940445/48341040-2a255880-e6c0-11e8-9dce-ecf25afee24a.png)

 The profile also thinks i have completed my collection on the graph display.

![image](https://user-images.githubusercontent.com/17940445/48341147-71134e00-e6c0-11e8-9415-92e00922754a.png)

I have not completed my collection. 

Restarting the game client doesnt fix the issue. Restarting the tracker client doesnt fix the issue. Buying and opening another GRN booster  pack to update my collection doesnt fix my issue either.

**Comment by LonelyHours** [comment]
Restarting my computer and relaunching both applications did not change change the reported completion state.

**Comment by Razviar** [comment]
It's already fixed. You need to get at leas 1 card to bring back numbers to normal.

**Comment by LonelyHours** [comment]
Thanks!
