### ISSUE TITLE
Hatchery Spider is not bring back cards.

### ISSUE THREAD

**Issue by Wyveryn** [Razviar/mtga-pro-tracker#155]
Played with Hatchery spider in a draft event.  It worked correctly at least once.  

However, in later games, it did not work correctly, 

Assume that the critical cards in your 40 card deck cost four mana, and you want to make sure you can cast them on turn four.   That means you have to hit your first four land drops.  If you are playing first, that means you need to have four lands in your first 10 cards – your initial seven plus the cards you draw on turns two, three and four.   To make sure you draw four lands in ten cards, you need to play at least 40 % lands.  In a forty card deck, that means at least 16 land cards.  If your important cards are five drops, and you want to play them on turn five, you need five lands in your first eleven cards – or 45% land.  That means you need slightly over 18 lands in your deck.

When I summoned the hatchery spider, it would have an icon on it saying there were 3 creatures in the graveyard.  One of them was a Generous Cat, casting cost 3, also a green creature.  

However, upon summoning the Hatchery Spider, only lands appeared in the search, the Generous cat did not.  My opponent was nice enough to kill my Hatchery Spider, and I used a card to bring it back from out of the graveyard, sorry, do not remember the card, but it was out of the same edition, Hatchery Spider had a 4 on him, but when you take him out of graveyard, the number switches to 3.  Generous cat, casting cost 3, is now on top of the graveyard, I can see it on top of the grave yard, yet none of the creatures appear in the search.  

Also, there was a multi color creature in the graveyard, Sumala Woodshaper, it is casting cost 4, so I did not expect it to show up in the search as an option to cast, but maybe it had something to do with the bug.

**Comment by apoapostolov** [comment]
This issue has nothing to do with MTGArenaPro tracker, it seems you are reporting MTGA bug. You should contact Wizards support instead.
