### ISSUE TITLE
When drafting cards, there should be a counter to tell you how many are in your collection.

### ISSUE THREAD

**Issue by Wyveryn** [Razviar/mtga-pro-tracker#156]
When drafting cards, I often find myself with zero viable options to put in my draft deck.  When this happens, I look for a card I do not yet have four of in my collection. The only way to check, appears to be, click on Decks, choose a deck, then search for the card, see how many of that card you have, click on home, click on draft, click on reenter draft.  

it would be so much easier if, when drafting cards, there was some symbol or number that appeared on the card that told me how many of that card are in my collection.  

it could just appear on every card in one of the corners, or float over the card when I put the cursor over it.

**Comment by apoapostolov** [comment]
You can use MTGArena.Pro to search cards you currently view in MTGA and decide whether ti is worth taking. What you are suggesting is for Wizards support, perhaps it is best to write on their forum.
