### ISSUE TITLE
Profile Page Not Loading, Duplicate Booster Entries

### ISSUE THREAD

**Issue by mackoz** [Razviar/mtga-pro-tracker#160]
**Describe the bug**
Profile page not loading, just spinning constantly

**To Reproduce**
1. Go to https://mtga.cc/u/mackoz
2. Loading circle doesn't stop spinning

**Expected behavior**
Profile page to load successfully

**Screenshots**
![Profile Page](https://user-images.githubusercontent.com/6621333/48398616-23a1db80-e6d6-11e8-9993-a53ddfa78d27.png)
![Boosters](https://user-images.githubusercontent.com/6621333/48398649-4207d700-e6d6-11e8-92ef-79062d987bb3.png)

**Additional context**
2nd screenshot is my boosters page. Before this started happening, I noticed there were duplicate entries on my boosters page. There were between 4x to 11x duplicate entries for each booster back I opened. Boosters page: [Boosters](https://mtga.cc/boosters/#mackoz) (date: 12/11/2018)

**Comment by ccprolix** [comment]
I have the same problem with my profile page. My opened booster packs are displayed correctly though.

**Comment by Razviar** [comment]
Double booster problem fixed, with user profile - try ctrl+f5

**Comment by mackoz** [comment]
Profile looks good now, thanks! The booster page is now showing the infinite loading circle: 
![image](https://user-images.githubusercontent.com/6621333/48411373-3debb180-e6f6-11e8-9088-a8c6fda7f665.png)

**Comment by Razviar** [comment]
I had to wipe all booster DB because of too many doubles. So when you'll get new boosters, they will show up there.
