### ISSUE TITLE
Add automatic YouTube/Twitch recognition for Add Video

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#162]
Currently Add Video only renders YouTube videos.

The feature can be expanded to render Twitch streams (even past streams) using links like that

https://www.twitch.tv/videos/334553665

That can be embedded with this:

<iframe src="https://player.twitch.tv/?autoplay=false&video=v334553665" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>

--

All we need to recognize between Youtube and Twitch format

**Comment by Razviar** [comment]
Agreed, Twitch is pretty popular in MTGA community, so it will be usefull to recognize Twitch videos too, not just youtube.
