### ISSUE TITLE
Healer's Hawk is depicted as a Non-Creature

### ISSUE THREAD

**Issue by AstronautApeStudio** [Razviar/mtga-pro-tracker#163]
**Describe the bug**
In My Decks, while looking at the specs of the deck, it says that I have 16 creatures, while in fact I have 18. When I click the "Creature" hyperlink, the non-creature cards go dark and only the creature cards stay with a lighter color. The card healer's Hawk of Guilds of Ravnica is said to be a non-creature, but it is in fact a 1/1 1 Plains cost creature - bird type card.

**To Reproduce**
1. Go to 'https://mtgarena.pro/decks/white-fast/'
2. Click on 'Creature'
3. Scroll up to 'Main/ Side card list'

**Expected behavior**

**Screenshots**
[Picture 1](https://lithi.io/file/9c94.png)

**Comment by Razviar** [comment]
Okay, I'll check that
