### ISSUE TITLE
Time that matches were played is incorrect

### ISSUE THREAD

**Issue by napoearth** [Razviar/mtga-pro-tracker#164]
**Describe the bug**
In the matches list, the time is off by 6 hours.  I have selected the correct time zone for my location and fo

**To Reproduce**
1. Mouse over 'My Arena'
2. Click on 'Matches List'
3. Look at any match in the list
4. The time that the match was played is incorrect.

**Expected behavior**
It should show the actual time that the game was played.

**Screenshots**
![mtg arena pro](https://user-images.githubusercontent.com/44950690/48464078-d1c78700-e7a3-11e8-9fcb-daa9b84c59fd.jpg)

**Additional context**
It appears that instead of subtracting 6 hours from GMT it is either adding 6 hours or is subtracting 6 hours twice.

**Comment by Razviar** [comment]
We are working on time issue now.

**Comment by Razviar** [comment]
From now on, with v.1.4.8 time should be correct. Old records may remain shifted
