### ISSUE TITLE
Match Data missing

### ISSUE THREAD

**Issue by Chronix1** [Razviar/mtga-pro-tracker#166]
Hey guys,

since 08. November i have some Problems with the Tracker.
Bevor my Decks and win/los where show on the my profile section
but on 08. + 09. November there show only 
"Matches Results 16:9 (0NaNh0NaNm)"
not what decks i have played

and after 09. there are no more data tracked

Gochiller's Matches History
mtga.cc/matches/#Gochiller

the last match showing here is from 
07/11/2018
21:19 — 21:27

after that day no more data, may it haves something to do with that "Matches Results 16:9 (0NaNh0NaNm)" problem

I have always the Tracker running and make all Updates

sry if you allready know about this

**Comment by Razviar** [comment]
You should make sure that you have v.1.4.6 and try Manual Reset. 
If it doesn't help, send me your token and ZIP of your game log on admin@mtgarena.pro

**Comment by Razviar** [comment]
From now on, with v.1.4.8 time should be correct.
