### ISSUE TITLE
Social Feed W/L mix yesterday ratio with today's plays

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#167]
On Social Feed, yesterday w/l, play time and play modes are migrated to today. Observed with yesterday and today results, but also with day before yesterday and yesterday.

![image](https://user-images.githubusercontent.com/4083812/48541829-38dd5c80-e8c6-11e8-8169-0f70e30b908e.png)

**Comment by Razviar** [comment]
From now on, with v.1.4.8 time should be correct. Reopen this if it's not.
