### ISSUE TITLE
Win/Loss ratio on Profile not displayed correctly.

### ISSUE THREAD

**Issue by ccprolix** [Razviar/mtga-pro-tracker#169]
Since the last update, Win/Loss ratios on my profile are not displayed correctly.  Stats for each played deck state 0:0, while the overall tracking for e.g. constructed ranked keeps working as intended.
[](url)https://imgur.com/a/eX8ViXj

Also progress (gold, vault ...) does not seem to update anymore on the profile page.

**Comment by apoapostolov** [comment]
Do you have 2:2 total rating from yesterday?

There is an issue with yesterda's progress in w/l being credited to today.

**Comment by ccprolix** [comment]
I don't know exactly, I may have played a game before midnight, but new matches are not added correctly either, for example, now it says 3:3 and still zero wins and losses for specific decks.

**Comment by apoapostolov** [comment]
Update 1.4.8 fixes this issue. Please update, give it two consecutive days to see if any matches from yesterday move to today, and please report if all is good. Thanks.

**Comment by ccprolix** [comment]
I updated to 1.4.8 but the issue remains for me.
[](url)https://imgur.com/a/mlo9yTT

**Comment by Razviar** [comment]
As written above, "give it two consecutive days to see if any matches from yesterday move to today, and please report if all is good. Thanks."
Old data will not be fixed, only the new one will start to render since few days.

**Comment by ccprolix** [comment]
I played some games today but the issue still remains. 
I get a 0:0 stat for specific decks and progress is not displayed on the profile page.

**Comment by Razviar** [comment]
We are working on that now.

**Comment by Razviar** [comment]
It;s fixed.
