### ISSUE TITLE
Profile Page Not Updating My Matches and New Cards

### ISSUE THREAD

**Issue by mackoz** [Razviar/mtga-pro-tracker#170]
**Describe the bug**
Profile page not updating even though my matches, boosters, and earned cards are being logged.

**To Reproduce**
1. Go to https://mtgarena.pro/u/mackoz
2. Compare my profile page with my boosters/matches history (history has all the updates but profile page is missing a bunch)

**Expected behavior**
Profile and booster/match history to be in-sync

**Screenshots**
### Profile Page
![image](https://user-images.githubusercontent.com/6621333/48556507-fea99600-e898-11e8-9327-7e9b1fbb31c1.png)
### Match History
![image](https://user-images.githubusercontent.com/6621333/48556517-08cb9480-e899-11e8-95c9-afa7e1128a2b.png)

**Additional context**
I've been using VMs to play and some had different time zones (mac not supported 😢 ). Not sure if that is related since I was switching between different VMs to optimize my setup.

**Comment by apoapostolov** [comment]
Tracker 1.4.8 fixes this. Please update, give it a day with no leftover results from previous day, and report if all is good. Thanks in advance.

**Comment by mackoz** [comment]
![image](https://user-images.githubusercontent.com/6621333/48593669-a909d380-e902-11e8-9775-f1cdb525bd10.png)

Just played a match today and I'm still getting the 0:0 score for my deck

**Comment by Chronix1** [comment]
same here, now cards i have earnd and match results 0:0, but in match history the matches are correctly displayed

**Comment by Funky69** [comment]
same here, only match history and percentage of total cards in collection works

**Comment by Razviar** [comment]
I'm working on fix now.

**Comment by Razviar** [comment]
Should be working fine now. Traditionally, fix is working only for future data, old progress can't be restored.

**Comment by Makistos** [comment]
I have updated to latest version but I still can see this issue from yesterday (Nov 22). https://mtgarena.pro/u/Makis.42056. Only one game shown while tracker shows more and the booster I got isn't shown either.

**Comment by Makistos** [comment]
Look at my profile page. It only shows one match from yesterday.

**Comment by Razviar** [comment]
As I wrote before, try full reset button on tracker v.1.5.2

**Comment by Makistos** [comment]
Reset didn't help. I still have the same issue.

**Comment by Razviar** [comment]
At this point I can't give any other advise. I can assume it's some rare system incompatibility, which is hard to reproduce. Sorry.
