### ISSUE TITLE
progress is not loaded

### ISSUE THREAD

**Issue by StarkPrimera** [Razviar/mtga-pro-tracker#171]
the tracker does not analyze progress and the status of the vault, how can I solve it?

**Comment by Persee59** [comment]
I have the same issue even after update into 1.4.8

**Comment by Razviar** [comment]
I'm working on fix now.

**Comment by Razviar** [comment]
Should be working fine now. Traditionally, fix is working only for future data, old progress can't be restored.

**Comment by StarkPrimera** [comment]
a me ancora non funziona, ne la pagina dei progressi ne lo statodel vault
