### ISSUE TITLE
Import deck hangs

### ISSUE THREAD

**Issue by timothy-debock** [Razviar/mtga-pro-tracker#172]
**Describe the bug**
when Importing a decklist the dialog box keeps showing the loading icon
 example deck: https://www.channelfireball.com/articles/standard-mono-red-when-to-play-a-land-before-experimental-frenzy-and-a-sideboard-guide/?_ga=2.209824469.1345593552.1542295872-363772558.1524843674

**To Reproduce**
1. Go to 'https://mtgarena.pro/deckbuilder/'
2. Click on 'import dack.'
3. past the decklist
4. loading icons stays for ever

**Expected behavior**
Have the deckbuilder showing the deck

**Additional context**
A work arround is using the deckconverer https://mtgarena.pro/converter/ pasting the list and then choose show in deckbuilder
-> the decklist is loaded correctly but wont be saved when clicking save

**Comment by Razviar** [comment]
It's fixed now.
