### ISSUE TITLE
Stopped working entirely since update on the 15th(?)

### ISSUE THREAD

**Issue by AiSard** [Razviar/mtga-pro-tracker#176]
Nothing has been tracked since updating on the 15th/16th

**Additional Context** Note however that I had been experiencing multiple issues prior. 
- All matches have been tracked as Constructed Rank rather than Quick Constructed since the 8th
- Profile page would not update, fixed by restarting pc.
- Everything else would also not be tracked after a while (if pc was not restarted)

These previous issues have since been replaced with no tracking whatsoever, restarting the .exe or pc having no effect.

**Comment by Razviar** [comment]
You should update to v.1.4.8 and perform manual reset. There were issues indeed, but now it's fixed. If you are still getting the issues, please send me your token and ZIP of game log from AppData WOTC directory on admin@mtgarena.pro

**Comment by AiSard** [comment]
Tracking has resumed (was already on 1.4.8 just hadn't manual reset)

Still experiencing matches being tracked as Constructed Ranked rather than Quick Constructed on the Profile Page without deck indication (even if other parts of the site are tracking the deck properly)

Should I still send token and zip? (as well as, should this have been a separate bug post?)
https://mtgarena.pro/u/AiSard/

**Comment by AiSard** [comment]
Sent.

Also a slight update (might just be how mtgapro works though)
The logs are from just before midnight
After midnight, Profile Page updated a bunch of stuff that was missing (boosters/cards/wc/etc)
Now recognizes deck, but still recording as Constructed instead of Quick

**Comment by Razviar** [comment]
Checked your log and data, all seems to be working. Data in profile page is updating: https://mtgarena.pro/u/AiSard/
