### ISSUE TITLE
Some Direct Challenges are not tracked right

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#177]
Four games using Direct Challenge had issues tracking the local deck, so they appear broken on both Matches and on Social Feed.

![image](https://user-images.githubusercontent.com/4083812/48671015-9376f280-eb2a-11e8-82f5-65845fa71fc9.png)

![image](https://user-images.githubusercontent.com/4083812/48671019-9eca1e00-eb2a-11e8-8b63-08e7636a8849.png)

Logs: https://1drv.ms/t/s!At_LoPNJEMUNk68XP6_JPPDZkbqQsA

**Comment by Razviar** [comment]
Direct Challenge are represented differently in log, so it will take additional testing. I'll work on this.

**Comment by Razviar** [comment]
Tracking implemented. You need to restart app to get new filters rolling.
