### ISSUE TITLE
Says I have an ypdate but none available

### ISSUE THREAD

**Issue by de-hamma** [Razviar/mtga-pro-tracker#180]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Razviar** [comment]
Are you sure that you are using latest v.1.4.8?
If you don't see actual UPDATE button in the app. just ignore the notice.

**Comment by Razviar** [comment]
Also, you can remove everything from C:\Users\{USERNAME}\AppData\Roaming\MTGAproTracker  folder, it might help
