### ISSUE TITLE
Tracker is not working after update 1.5.0

### ISSUE THREAD

**Issue by sarion0** [Razviar/mtga-pro-tracker#183]
**Describe the bug**
Tracker is not working after update 1.5.0
no information today
![image](https://user-images.githubusercontent.com/45102513/48851874-2929b080-edbd-11e8-87d4-774b86f42256.png)

**Comment by sarion0** [comment]
manual resync and scan old logs not working too

**Comment by AxDSan** [comment]
https://mtgarena.pro/news/your-tracker-stopped-updating-after-v-1-5-0-release/

**Comment by sarion0** [comment]
Now working, TY!
