### ISSUE TITLE
Implement identification of MTGA-Tracker-Pro users

### ISSUE THREAD

**Issue by AxDSan** [Razviar/mtga-pro-tracker#184]
Just as the title specifies, it would be nice to implement some kind of overlay or maybe a feature within the tracker to identify other MTGA Tracker Pro users/players.

That way we can connect with each other user, and also look up our progress, decks, etc., etc.,

For those concerned about privacy, development can add an option to disable this feature

**Comment by bwoneill** [comment]
I don't think this should be a feature. At least it should not be available to players until the match is over as being able to look up an opponent's deck during a match can give you an unfair advantage.

**Comment by bwoneill** [comment]
You can see any decks listed in an MTGA Tracker Pro player's account by going to `mtga.cc/decks/#<username>`. Even if the decks are listed as "Hidden" anyone can access them (tested on Internet Explorer using a virtual machine).
For example, you can see my decks at: [mtga.cc/decks/#bwoneill](url)
It may not tell you exactly which deck you are using, but in most cases you'll be able to narrow it down to 1 within a few plays.

**Comment by AxDSan** [comment]
Oh I know this already, but my point is that there is NO (specifically) current way of knowing if your opponent is using the Tracker, like an actual identifier that tells you: "hey this person this person is using MTGA Tracker Pro!" get me now? Of course there's your way of doing it in which you would have to literally go through everyone in your match list and check them manually, But that's not what I mean.

So this is being implemented already, I'm guessing the change will appear in the changelog, so this can be treated as closed, Thanks for all the suggestions.

**Comment by bwoneill** [comment]
My point is that if all you need is someone's username to look up their deck lists, then even telling you someone has a tracker account _during a match_ potentially gives them an unfair advantage. People reuse usernames (case in point, my username) and telling someone that an account exists _during a match_ potentially puts those accounts at a disadvantage versus unscrupulous players.

Either that information must be withheld until the end of the match or deck lists must be made, by default and retroactively, inaccessible to others. I would have no problem with a link to your opponent's account showing up in your match history, but this should not be given during a match.
