### ISSUE TITLE
Texture Background

### ISSUE THREAD

**Issue by DubstepSharKHS** [Razviar/mtga-pro-tracker#188]
Hi, i'm a eSports manager and currently working on a MTGA tournament series. Someone showed me the tracker, but as far as i can see i can forge results in a print with minimal knowledge. A complex background would help a lot in preventing this issue.

Ps: Also feel free to contact me if you guys have any ideas regarding tournaments, i will probably email you eventually anyway :)

**Comment by Razviar** [comment]
Hi! We have tournament platform on other CCG project, TES Legends. You can take a look here: https://teslegends.pro/tourn/

And same system is planned to be implemented for MTGA. If you are interested in tournament organization, please email me on admin@mtgarena.pro
