### ISSUE TITLE
Can't parse logs for certain dates

### ISSUE THREAD

**Issue by martinstark** [Razviar/mtga-pro-tracker#193]
I have logs from 19, 20, 21, 22 of November. My profile is missing data from 19, 21, and 22. I have tried to manually scan them using "Scan Old Logs..." but it doesn't work.

I have attached one of the files below, let me know if you want all of them (you need to change the file extension of the file back to .htm).

[Log - 19-11-2018 17.58.43 - 1.log](https://github.com/Razviar/mtga-pro-tracker/files/2609289/Log.-.19-11-2018.17.58.43.-.1.log)

**Comment by Razviar** [comment]
Are you using v.1.5.1 and done full reset before logs upload attempt?

**Comment by martinstark** [comment]
Not at home right now so can't check what version I'm running, but I downloaded the update that was published right before I made my post, and tried importing the logs from the missing days after the update.

I'll retry tonight and report back. Does the Tracker client have it's own logs somewhere that I can forward to you? It doesn't report any errors when parsing the logs, but my profile isn't updated.

**Comment by martinstark** [comment]
Does the full reset reset all my old match results on my profile? I would like to keep those if possible

**Comment by Razviar** [comment]
Full reset resets only the APP. All data in the account will remain.

**Comment by Razviar** [comment]
By the way, we rolled out v.1.5.2, don't forget to update.

**Comment by martinstark** [comment]
Did reset and reupload. I got some of the matches to appear on the Matches List now, and it caught up with my unlocked cards, but I still cannot get any matches from the logs from the 21st to upload.

The "My Arena"/"Profile" page is also missing the Matches Results summaries for the 19th, 21st and 22nd. (and some of the other dates have the wrong numbers compared to the Matches List page)

**Comment by Razviar** [comment]
Well, this is best we can get, some matches may go missing. Unfortunately we cannot guarantee 100% tracking even after all updates

**Comment by martinstark** [comment]
Sure, not complaining. But isn't it weird that the matches appear on the Matches List, but not on the profile summary? That seems like a bug on the website, at least

**Comment by martinstark** [comment]
You're not interested in my logs from the 21st, to check why they fail to parse/upload?

**Comment by Razviar** [comment]
Sure, I would like to take a look, send me zip of logs on admin@mtgarena.pro
