### ISSUE TITLE
[webpage] Midrange tag is displayed as "Artifact" instead

### ISSUE THREAD

**Issue by Mikaill** [Razviar/mtga-pro-tracker#195]
**Describe the bug**
Midrange tag for personal decks is displayed as "Artifact" instead

**To Reproduce**
1. Go to https://mtgarena.pro/decks/
2. Look for any deck marked as midrange (use filter if necessary)
3. Open the deck preview by clicking on its name
4. See that the deck is described as "Artifact" and hovering over the midrange symbol displays "Artifact" tooltip.

**Expected behavior**
Midrange tag is displayed as midrange and not artifact in deck preview.

**Screenshots**
![screen3](https://user-images.githubusercontent.com/17011135/48923690-037dd380-eeb1-11e8-8ba6-3aedae38f842.png)

**Comment by Razviar** [comment]
Thank you , we'll fix that

**Comment by Razviar** [comment]
Fixed. Ctrl+f5 to see update.
