### ISSUE TITLE
Not Updating After Doing Everything Mentioned

### ISSUE THREAD

**Issue by windyridge** [Razviar/mtga-pro-tracker#202]
**Describe the bug**
 It doesn't update and hasn't since Nov 20.
I updated, re-keyed, did everything mentioned, nothing works.  This usually happens anytime there is an update but eventually it starts to work again. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Razviar** [comment]
You have to update to version 1.5.2 and use full reset button in the app. If that doesn't help, remove mtgaprotracker directory from appdata folder manually. Unfortunately, I have on other advice
