### ISSUE TITLE
'New Update Available' only shows up after manual restart

### ISSUE THREAD

**Issue by AiSard** [Razviar/mtga-pro-tracker#203]
For the last two updates (done on the 23rd and 26th, at least on my side) the red New Update Available button only shows up when the program is manually restarted (Exit and running the .exe again)

I assume that such a button should be showing up whenever a new update gets pushed (if not, change this to a suggestion I guess?)

Just in case its relevant: I've done a Manual Re-Sync and Full Reset during this period (usually before Exit and restart) and the Update button doesn't show up then either if that matters.

**Comment by SB-FM** [comment]
Same issue, the current update mechanic forces me to restart the application every session.

**Comment by Razviar** [comment]
Yes, we know that about that issue, updates mechanics will improve in the next releases
