### ISSUE TITLE
Wrong deck in a match report

### ISSUE THREAD

**Issue by scpsc** [Razviar/mtga-pro-tracker#204]
Matches list is wrong for the game attached: I played a deck named "WBG" and not the one named "destroy".

There is no doubt for me: it was my last game tonight and the time does correspond.

![wbg](https://user-images.githubusercontent.com/4867738/48986021-64a2e280-f10f-11e8-97e5-f8b04cb2a0a0.PNG)

**Comment by Razviar** [comment]
Yes, such mix ups are sometimes happening, but not frequently and those are hard to replicate, that is why we consider it ok
