### ISSUE TITLE
Tracker don't found the game info

### ISSUE THREAD

**Issue by Shizenix** [Razviar/mtga-pro-tracker#205]
**Describe the bug**
The tracker don't found the game info, he always said :"awaiting for updates ..." i have try to reinstal or repair but it still dosn't work (since the 20th november) 

**Screenshots**
![image](https://user-images.githubusercontent.com/45342338/48986058-f3176400-f10f-11e8-8818-28197f6090d4.png)

![image](https://user-images.githubusercontent.com/45342338/48986065-07f3f780-f110-11e8-8465-04924d8aaf67.png)

**Comment by Razviar** [comment]
Click Full reset button
