### ISSUE TITLE
Game data and profile not updating

### ISSUE THREAD

**Issue by SB-FM** [Razviar/mtga-pro-tracker#206]
**Describe the bug**
After doing the usual update procedure (which is tedious sadly) and the application apparently running fine, no game data appears on my account. 

No matches, no cards, no deck changes. This is the affected account https://mtgarena.pro/u/NIL.

Version: 1.5.2.0

Tried fixes:
* restarting the app
*  "manual Re-Sync" option 
* re-selecting the log location

edit: i zipped the log and send it via email to the admin account - title is the name of this ticket.

**Comment by Razviar** [comment]
You have to use "full reset" button
