### ISSUE TITLE
Draft viewer rating not always shown

### ISSUE THREAD

**Issue by Showstopper123** [Razviar/mtga-pro-tracker#207]
In the draft viewer, bars with ratings are shown on most cards, but not all.

For the small cards on the left, it seems cardnames including apostrophe (') do not show a rating. This includes card names such as Lich's Caress or Marauder's Axe.

For the big (picked) cards on the right, I have not been able to find out the pattern, but they are also sometimes not shown.

In addition, the ratings could use an explanation on the page: How are they calculated? What do they mean?

![image](https://user-images.githubusercontent.com/22116046/49041976-10f3d000-f1c7-11e8-8bd6-c55a2baeaa29.png)

**Comment by Razviar** [comment]
Those are draftsim's ratings (there even credit on the bottom of the page). But we are going to replace them with our own ratings, that is why not all cards are rated
