### ISSUE TITLE
Can't add more than 60 cards to my deck in deck builder.

### ISSUE THREAD

**Issue by ALionNamedBoy** [Razviar/mtga-pro-tracker#208]
**Describe the bug**
The Deck Builder does not allow me to add more than 60 cards to my deck.

**To Reproduce**
1. Go to Deck Builder
2. Attempt to add more than 60 cards to your deck

**Expected behavior**
I should be able to add more than 60 cards.

**Comment by Razviar** [comment]
Delivered.
