### ISSUE TITLE
Deck analysis creature count does not always function correctly

### ISSUE THREAD

**Issue by ALionNamedBoy** [Razviar/mtga-pro-tracker#209]
**Describe the bug**
I have a deck that uses 3 creatures. The deck viewer interface shows no creatures in the deck.

**To Reproduce**
1. Go to https://mtgarena.pro/decks/thousand-year-storm-ur-burn/

**Expected behavior**
The indicator should show the correct number of creatures.

**Screenshots**
![image](https://user-images.githubusercontent.com/16676951/49151343-00706080-f353-11e8-95f2-8f0592ef639f.png)

**Additional context**
I thought it might be the card in particular (Electrostatic Field), or the card type (Creature - Wall), but this bug is not present in a different deck.

**Comment by Razviar** [comment]
I'll check that

**Comment by cameo25** [comment]
+1 I am also seeing this on my custom deck. My creature stat is at 18% which seemed odd to me. Looking more closely some cards are not recognized as creatures.

Twilight Panther, Hired Poisoner, Grasping Thrall and more

![capture](https://user-images.githubusercontent.com/3249893/51444072-85b72800-1ca7-11e9-94b7-4d3e4fdae66c.JPG)
