### ISSUE TITLE
Stuck on Awaiting for updates...

### ISSUE THREAD

**Issue by azthec** [Razviar/mtga-pro-tracker#210]
**Describe the bug**
Since the update to version 1.5.2 the MTGArena application has stopped uploading games and other related content being stuck on the "Awaiting for updates...." message as can be below.

**To Reproduce**
1. Manually open the application.
2. See error.

**Expected behavior**
Expected the application to move from this state into a functioning state if no updates are available.

**Screenshots**
https://imgur.com/AiCUmr3

**Additional context**
1. Using the latest version 1.5.2.
2. .NET 4.6.2 or higher is installed and functioning.
3. FULL RESET does not solve the problem.
4. Error persists through full reboots.
5. No web traffic is blocked and antivirus do not block the program.

**Comment by azthec** [comment]
Sent.

**Comment by Razviar** [comment]
Mail didn't went through I suppose, can you resend it, but use some file storage to pass the file. You can drop over link like Dropbox right here

**Comment by azthec** [comment]
Google Drive [here](https://drive.google.com/file/d/0B3pk5KbgZpjgUUNicFdlOUVzUXcteEw3ekZid2gtVzdYODBF/view?usp=sharing).

**Comment by Razviar** [comment]
Thank you!

**Comment by azthec** [comment]
[Here](https://drive.google.com/file/d/1ZsyPoK6a5bXPiSMdNe1f2NKsosXjizGN/view?usp=sharing) it is.

**Comment by azthec** [comment]
Alright [here](https://drive.google.com/open?id=1KU3K5YLqIl0mwxmoNAsS7EtVfmENJMnT).

**Comment by Razviar** [comment]
Yep, this is it, checking it now.

**Comment by Razviar** [comment]
Log is fine. I just checked it, app was able to parse it. 
So, the problem is somewhere else. Try now to use "Full reset" button and input your token.
After that, tell about ALL changes of app interface. 

Normal flow:
1. Reading log...
2. Your MTGA nick displayed
3. Uploading data
4. Upload complete
5. Awaiting for updates

Compare it to your flow of interface and let me know what differs.

**Comment by azthec** [comment]
It has now booted successfully and uploaded the data to the website without the need to press Full reset. I have no explanation.

If you wish to debug it more and even want to me to run some debug enabled version of the Pro-Tracker I am up for it.

**Comment by Razviar** [comment]
I think it's some kind of magic, I just had to cast rays of fixture to your copy of the app. If it gets stuck in future, please let me know :)
