### ISSUE TITLE
Card Ante for duels.

### ISSUE THREAD

**Issue by DatOneGuy1010** [Razviar/mtga-pro-tracker#211]
**Is your feature request related to a problem? Please describe.**

Dueling currently lacks a purpose. This would spice up games with friends.

**Describe the solution you'd like**

After the duel is confirmed and all that have a window pop up for card ante. Pick a card from your collection of matching rarity to the other players ante so it'll balance out a bit. Then after both parties either agree on ante or not start the match. Winner takes both cards.

**Describe alternatives you've considered**

**Additional context**

This idea came about when I was chatting with a friend whilst dueling. We thought about how you cannot earn rewards for dueling to prevent abuse no doubt so we thought how about a sort of jack pot. A reward dictated by the involved parties would be pretty neat. Also matching rarity to prevent abuse of the mechanic.

**Comment by SvenRtbg** [comment]
Sorry to disappoint you, but the bug tracker for MTG Arena is somewhere else, probably here: https://mtgarena.community.gl/forums/categories/52
This here is the bugtracker for one of the tracker apps, developed independently from the game.
