### ISSUE TITLE
Tracker not tracking after changing MTGA Pro account, but not MTGA account

### ISSUE THREAD

**Issue by PassoP** [Razviar/mtga-pro-tracker#212]
**Describe the bug**

I made two accounts for MTGA Pro. After changing account, the tracker isn't tracking. I use the same MTGA account for both trackers.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Razviar** [comment]
You can't have two different account for one in-game account. You can use only one token. Make full reset and install single token for single mtga account
