### ISSUE TITLE
Collection manager search: results disappear when scrolling to the bottom of the page

### ISSUE THREAD

**Issue by mgabor3141** [Razviar/mtga-pro-tracker#214]
Steps to reproduce:
1. Search for a card that will return a moderate number of results (eg. Mountain)
1. Scroll to the bottom of the page, loading new pages of results each time
1. Scroll to the bottom of the last page: everything disappears and the "No results" test is visible

**Comment by Razviar** [comment]
Thanks for the report, I'll fix that

**Comment by Razviar** [comment]
Fixed
