### ISSUE TITLE
Feature request: Hide decks button

### ISSUE THREAD

**Issue by jzhanglsw** [Razviar/mtga-pro-tracker#216]
I realize it might be difficult to add deck filters and more interactive features to the deck lists but being able to hide stupid decks like the "Land Shopping List" deck that is just a bunch of unique lands would be helpful to getting closer to that goal. I don't want to see the same 10 NPE decklists when I filter for decks I can craft.

**Comment by Razviar** [comment]
We are working on the solution for that
