### ISSUE TITLE
Pile view option in deck editor

### ISSUE THREAD

**Issue by MrBadDragon** [Razviar/mtga-pro-tracker#218]
I would like to have the option to view my deck in a pile view by CMC. This is a common way of brewing a deck and I am finding it hard to visualize how my decks mana curve looks from a single list. 

Right now I would settle for a view only mode, if that was easier to put together :-)  I've added a picture as an example of what I am after.

It would be sufficient to display the card names with mouse over.

![mtgo 2](https://user-images.githubusercontent.com/32524113/49678195-9b9dce80-fae7-11e8-9372-e12e2d110252.PNG)

**Comment by Razviar** [comment]
Yep, it's not too hard to implement, we'll do that

**Comment by MrBadDragon** [comment]
Great - one request is to display multiple cards - Arena gives a card count which is ok, but when you are gut-feeling your CMC and dual/tripple mana symbols is not intuitive.

Compare the  screenshot below with the one I posted earlier to see what I mean. I am happy to have a count of lands however.

![arena2](https://user-images.githubusercontent.com/32524113/49692623-29e78280-fbc4-11e8-85a1-e590cf6d0361.PNG)

**Comment by Razviar** [comment]
I'm not sure if you are still interested, lol, but it's implemented :)
