### ISSUE TITLE
User link doesn't show the appropriate decks list

### ISSUE THREAD

**Issue by yassir-a-p** [Razviar/mtga-pro-tracker#220]
**Describe the bug**
The permanent user links doesn't show their decks list.

**To Reproduce**
1. Go to any user page, i visited 'https://mtgarena.pro/decks/#professornoxlive' and 'https://mtgarena.pro/decks/#PartyNightLife'
2. See error: the page doesn't show user's decks and instead shows Singleton Decks list (screenshot 1&2).

**Expected behavior**
Expected: User page shows user's saved decks list.

**Screenshot**
![screenshot 178-jpeg](https://user-images.githubusercontent.com/33170240/49688358-54452b80-fb43-11e8-9618-cfffd287c1e9.jpg)

**Additional info**
Tested using Firefox 63.0.3 and Opera 56

**Comment by Razviar** [comment]
Thanks for report, it's fixed. Try ctrl+f5
