### ISSUE TITLE
MTGArena stopped uploading data to website 

### ISSUE THREAD

**Issue by PavorNocturnus** [Razviar/mtga-pro-tracker#223]
Not sure why, but back my most recent data on the website comes from November 20th.  I assume it has something to do with updating the client, which I had to eventually update manually after the auto-updater failed multiple times.  Currently, my MTGAPro client indicates version 1.5.2.0. which was installed on 11/23/2018.

Just checked the website and it appears none of my data has been saved since 11/20/2018, though.  Any ideas?

Edit:  Here's some things I've tried:  Manually uploading logs.  Using the 'Repair' function on the MTGA Pro Tracker Setup.  Putting my anti-virus software to sleep for a moment.  No success as of yet.

**Comment by MTGJustin** [comment]
Same issue as above. Also tried manually uploading logs, repairing, shutting down anit-virus programs, and then entirely uninstalling and reinstalling. None of those worked.

**Comment by Razviar** [comment]
Reboot your PC, use "Full Reset" button in the app interface and re-input your token.

**Comment by MTGJustin** [comment]
I did that two nights ago and it did not resolve the problem.
  

  
  

  
  
>

**Comment by Razviar** [comment]
I just checked general state of tracker, and it's OK. Data from players is being uploaded, no log format changes registered. So it's some specific for your configuration problem. 

To try to debug this I will need:
1. Screenshot of app interface while game is running (alt+tab from the game and open Tracker)
2. Zipped copy of C:\Users\{YOUR USERNAME}\AppData\LocalLow\Wizards Of The Coast\MTGA\output_log.txt
3. Your user token

You can send me all that stuff on admin@mtgarena.pro

**Comment by MrBadDragon** [comment]
Since the update, logging appears to have been turned off.

**Comment by Razviar** [comment]
Nope, I just checked, logging is thankfully still there.

**Comment by DontletmeSudo** [comment]
I am not seeing stats for decks I imported and play with. No W/L. I am seeing other tracking. Anything I can send your way?

**Comment by vault101** [comment]
> Reboot your PC, use "Full Reset" button in the app interface and re-input your token.

Same issue here, resolved by full reset though...
