### ISSUE TITLE
Ranked Matches not updating

### ISSUE THREAD

**Issue by t-dimaras** [Razviar/mtga-pro-tracker#224]
After the December 13th MTGA update, which introduced ranked ladder, constructed ladder matches are not updated. Neither the W/R ratio progresses accordingly, nor the Matches List contains ladder matches.

Since ladder is a new feature, that is understandable.

**Comment by Razviar** [comment]
Actually, ladder matches are being uploaded, just I can't figure why they are not working as they should. Trying to debug now.

**Comment by Razviar** [comment]
Should be working now.
