### ISSUE TITLE
Tapping large costs for "X" From multiple mana producing objects quicker!  

### ISSUE THREAD

**Issue by seisler20148** [Razviar/mtga-pro-tracker#225]
**Context**
I play Expansion // Explosion for a total cost of 2u 2R and X=20
I have 9 Treasure artifacts on the board, 4 Basic lands, and 15 Dual lands. 
**Problem**
Because I have treasure on the board I have to tap each source individually. Each time I Sacrifice a treasure for mana I have to click it once, wait for the oddly placed color wheel to come up, and click a color. Once I get through those I have to do the same thing for 15 Dual lands. It takes an enormous amount of time to tap all of these, making it a very risk situation trying to produce all of this mana at any time during my game. 
**Solution** 
The main request here is to come up with a way that is more convenient for choosing large cost of X that is coming from multiple sources of mana producing objects. Perhaps if you click a treasure it can bring up an interface that is not the color wheel where you can quickly assign the colors for multiple treasure at a time. For Dual lands and regular lands perhaps there is a quick button labeled "X" somewhere on the screen That you can click before you quick tap all of the mana you want to be assigned for just X.

**Comment by SvenRtbg** [comment]
Sorry to disappoint you, but the bug tracker for MTG Arena is somewhere else, probably here: https://mtgarena.community.gl/forums/categories/52
This here is the bugtracker for one of the tracker apps, developed independently from the game.
