### ISSUE TITLE
My Decks page stuck forever loading...?

### ISSUE THREAD

**Issue by dhosein** [Razviar/mtga-pro-tracker#226]
**Describe the bug**
Whenever I try to visit the 'My Decks' page, I seem to get stuck forever loading. This only occurs on this one page. The address I'm being linked to is: https://mtgarena.pro/decks/?my
Then the filter list is: mtga.cc/decks/?Sylver

![image](https://user-images.githubusercontent.com/28493814/50041887-9bf01980-0053-11e9-8f86-40611fa4dea7.png)

**Comment by Razviar** [comment]
Fixed. Try Ctrl+f5

**Comment by dhosein** [comment]
No change - just refreshes the page and gets stuck in the same place again.

**Comment by Razviar** [comment]
Must be cache, try again, should work now.
