### ISSUE TITLE
Bug when logged into a second account

### ISSUE THREAD

**Issue by mgabor3141** [Razviar/mtga-pro-tracker#227]
I logged in from another account from the same PC and played a few rounds of Magic. I now have a spike on all my graphs that is a single data point from the other account.

Ideally I'd like to set up the tracker to track whatever account I'm currently logged into on MTG with different tracker tokens, but at the very least I'd like it to throw away data that isn't for the currently logged in user.

Also, please fix the spikes in my past data.

Thanks!

![image](https://user-images.githubusercontent.com/9047995/50053268-548c8a80-0132-11e9-813f-79681c7598db.png)

**Comment by Razviar** [comment]
Sorry, we are not doing manual user data cleanup. Soon we will add tool to wipe specific days. Also, multiple accounts support is should be supported, we were fixing it for several times. I will investigate how this could happen

**Comment by mgabor3141** [comment]
@Razviar This happened again. Is the featuire to wipe specific days coming soon? My progress graph is ugly again...

![image](https://user-images.githubusercontent.com/9047995/62839752-35c5a000-bc8f-11e9-8ff1-463566793311.png)
