### ISSUE TITLE
Booster Recommendation

### ISSUE THREAD

**Issue by Azebu** [Razviar/mtga-pro-tracker#228]
I'm always frustrated when I spend my gold on packs when I should be saving up for Ravnica Allegiance. However the main problem is not knowing which packs to choose. I alternate between GRN, DOM and XLN, but recently I've been hitting a lot of dupes on GRN.

A good solution to this would be having the site suggest which packs to open based on your collection! If it would scan all the cards (mostly rares and mythics) that you don't have yet, compare them to a number of cards of each rarity in the set, and based on that calculate the odds of you not hitting a 5th copy.

Further improvement would be an option to filter out cards which you don't care about, and even better, if you could specify the amount of each card you'd like (2 Azcantas are enough, for example). This could also be integrated with Decklist Browser, by having a button to "Add cards I'm missing to my Desired Collection".

Thank you and have a nice day!

**Comment by Razviar** [comment]
That's very good idea, we had some suggestions like that before, so we will definitely implement this in some form. Thank you!

**Comment by zhbanok** [comment]
I very like this idea. 
But we need to remember that not all cards of set can be opened thru packs. According to my data (which is not 100% true) GRN has only 259 of these cards, M19 - 260 cards, DOM - 259 cards, RIX - 191 cards, XLN - 259 cards.

I dont think feature must recommend just only one pack. It can, but it will help a lot if we can also see more stats for manual decisions:
For example what I want to see for every set:
% of commons that have 4 copies
% of uncommons that have 4 copies
% of rares that have 4 copies
% of mythics that have 4 copies
number of unique cards, total sum of cards wishlisted and % of wishlisted cards in that set for 2 rarities. I agree that only rare and mythic quality needed. 

How i see it:
We can add any card that we want to wishlist. And adding threshold number for every wishlisted card seems nice.
As additional feature we can add to wishlist even decks. And all cards that we dont own can be counted as wishlisted card. (wishlisted decks != favorite decks).
As additional feature we can wishlist cards with some rank priority. For example 3 ranks: 
-basic - all cards in set in which we are not very interested
-moderate - some cards that seems ok and maybe will see some play in future in some unusual or junk deck or deck of low priority.
-high - cards totally fine, that wanted right now for current meta, that highly used in mainboards or sideboards.

Also this info page can count total numbers of Wildcards needed for crafting any number of wishlisted decks. For example we wishlisted 3 decks, some lands or/and some other cards that we dont own can be in 2 or even 3 decks, so we can combine this crossing cards and calculate right number of WCs needed.
