### ISSUE TITLE
Timer counts down too fast to choose pop up options

### ISSUE THREAD

**Issue by BachJS** [Razviar/mtga-pro-tracker#229]
When playing my deck which has 
4x Leonin Vanguard
4x Ajani's Welcome 
3x Ajani's Pridemate
1x Dawn of Hope
I often have the timer count down when all the triggered abilities start faster than I can click the button to add a +1/+1 counter on Pridemate, to cancel Dawn of Hope's draw card.

Also when using Skirk Prospector adding (R) mana with his ability sometimes cannot be done before the timer runs down.

Please make sure that the timer does not count down faster than you can humanly play.
However, I would prefer the game to go faster. I want to automate these silly choices until I say otherwise. If I could press "a" select an option then press "A" and have that option always chosen without the popup that would be great. A yellow flag could be put on the card to allow me to end the automation.

It may be that my computer is slow.

**Comment by DontletmeSudo** [comment]
@BachJS  this isn't a bug tracker for MTGA, this is for an add-on to the game.
