### ISSUE TITLE
I can't change my avatar image in web page.

### ISSUE THREAD

**Issue by ticketminami** [Razviar/mtga-pro-tracker#231]
**Describe the bug**
I can't change my avatar image in web page.

**To Reproduce**
1. Go to https://mtgarena.pro/u/Ticket with my account.
2. Click on Change Avatar.
3. Select same Image and push "SET AVATAR".
4. Page is reloaded. But avatar image was not changed.

I retry 1-4 from IE, Chrome, Android mobile phone. 
And I retry with other Images(big or small).
...I can't change my avatar.

**Comment by Quenway** [comment]
The same here. A few days ago I succeed in changing my avatar, and today when I was testing for one of my friends, it doesn't work and Karn was my new avatar... 

Thank you for the hard work ! Your tracker is amazing, with some bug, but awesome :)

**Comment by ticketminami** [comment]
Yes.
My Avatar is Karn too.

**Comment by Razviar** [comment]
Thanks for reporting, avatar is can be change now :)

**Comment by ticketminami** [comment]
I checked it.
And I can change my avatar.
Thank you for your support.
