### ISSUE TITLE
Sorting of Winrate is not working properly

### ISSUE THREAD

**Issue by Ramadas108** [Razviar/mtga-pro-tracker#233]
**Describe the bug**
Sorting of Winrate is not working properly

**To Reproduce**
 https://lh3.googleusercontent.com/-SBLnVxYhM9A/XB0czGG9xkI/AAAAAAAAVbc/84y1LWPHvBgcvfwhF8HgM-Bj0NTJMoyEwCHMYCw/s0/2018-12-21_18-03-05.png

**Expected behavior**

**Screenshots**
https://lh3.googleusercontent.com/-SBLnVxYhM9A/XB0czGG9xkI/AAAAAAAAVbc/84y1LWPHvBgcvfwhF8HgM-Bj0NTJMoyEwCHMYCw/s0/2018-12-21_18-03-05.png

**Additional context**

**Comment by Razviar** [comment]
Fixed.
