### ISSUE TITLE
Deckbuilder Scroll Bug When Using Smart Search

### ISSUE THREAD

**Issue by ALionNamedBoy** [Razviar/mtga-pro-tracker#236]
**Describe the bug**
When searching for a term in the Deckbuilder and then scrolling down with the mouse scroll wheel, the cards will stop loading, and you will only be able to view the first 30 cards that correspond to your query.

**To Reproduce**
1. Go to https://mtgarena.pro/deckbuilder.
2. Search for a term (eg "Destroy").
3. Scroll down using your mouse wheel.
4. Notice that you cannot scroll down further than what is first loaded.

**Expected behavior**
The next cards should load and display when the user scrolls down.

**Screenshots**

**Additional context**
As long as the user has not first triggered this error with their mouse wheel, this bug can be circumvented by directly clicking the vertical scroll bar of the cards and dragging it to the bottom of the display area.

**Comment by Razviar** [comment]
Thanks for the report, it's fixed now. Ctrl+f5 to see changes. Let me know if you notice similar bugs with scroll again.
