### ISSUE TITLE
Select options go under Set Deck Type Window and dont visible in Browse Decks/My Decks/edit name and format

### ISSUE THREAD

**Issue by zhbanok** [Razviar/mtga-pro-tracker#237]
**Describe the bug**
Select options go under Set Deck Type Window and dont visible in Browse Decks/My Decks/edit name and format

**To Reproduce**
1. Go to Browse Decks > My Decks
2. Click on 'Edit name and format' for any deck
3. Click on deck type or format select field
4. Select options go under Set Deck Type Window and dont visible. Tested in latest firefox and chrome.

**Expected behavior**
Select option must be visible after click on this input field.

**Screenshots**
![image](https://user-images.githubusercontent.com/46106228/50402223-e38a4a00-07a5-11e9-9f58-3cdb2e982a12.png)

**Comment by Razviar** [comment]
Thanks for the report, it's fixed now. Ctrl+f5 to see chenges.
