### ISSUE TITLE
Batch renaming at /decks/?my is bugged

### ISSUE THREAD

**Issue by St3v3s4n** [Razviar/mtga-pro-tracker#238]
**Describe the bug**
If you rename more than one deck at https://mtgarena.pro/decks/?my without reloading between each edited deck, the website only recognizes the very first edit that was done. The rest gets lost.

I renamed like 15 decks that way, only to find out, that only the first edit made it remote =)

**To Reproduce**
1. Go to 'https://mtgarena.pro/decks/?my'
2. Hover over a deck
3. Click on the pencil for editing
4. Change the name
5. Click "OK"
6. Pick next deck and repeat 3 to 5
7. Hit F5

**Expected behavior**
Only the first of the two edits will be displayed

**Screenshots**

**Additional context**
Would be cool to have it done with an ajax call or something similar asynchronous.

**Comment by Razviar** [comment]
It's fixed, and I'm reworking deck quick edition dialog now.
