### ISSUE TITLE
when you mix promo versions and normal versions of the same card they are not recognized correctly

### ISSUE THREAD

**Issue by rcitaliano** [Razviar/mtga-pro-tracker#242]
**Describe the bug**
Firstable thank you very much for the tool, it is great!!!!!!!!
when you mix promo versions and normal versions of the same card they are not recognized correctly

**To Reproduce**

1. you need to create a deck in MTG Arena
2. the deck must have a card with two normal versions and a promo version (I've tested this only with teferi)
3. play some games with the deck(maybe you can skip this, I'm not sure)
4. check the deck on the website

**Expected behavior**
I guess that we need to show 3 total teferi in the deck

**Screenshots**
deck in MTGA
![image](https://user-images.githubusercontent.com/11677787/50519629-24db6c00-0abc-11e9-9159-a82a4e9d6cff.png)
Deck on the website
![image](https://user-images.githubusercontent.com/11677787/50519666-43d9fe00-0abc-11e9-9d37-34a92caaa9d3.png)

**Comment by Razviar** [comment]
Promo elves are fixed, Teferi is still in progress
