### ISSUE TITLE
Manual Re-Sync does not work proberly

### ISSUE THREAD

**Issue by Vinrael** [Razviar/mtga-pro-tracker#247]
After 11 wins for the day the App shows me an obviously incorrect score of 7-4. I thought about some upload error and used the "Manual Re-Sync"-Button to read the last log file again (all 11 wins were in this one session). After that, my score suddenly changed to 15-7. I did it again and the score changed to 23-10. So in fact every single re-sync added 8-3 (where ever this number comes from, again, I should have had 11 wins at this point) to my score instead of replacing incorrect uploads/errors.

**Comment by Vinrael** [comment]
![image](https://user-images.githubusercontent.com/45329900/50559172-7f5f0d00-0cf4-11e9-85f7-754c84fc8848.png)

After 15 wins my balance looks like this. The buttom score of 15-11 should be correct, but there is this huge gap of 4 games total..before your server upgrade the app missed one match, maybe two if i was playing 50+ matches, but now its apparently 4 out of 26, so almost 20%

**Comment by Vinrael** [comment]
![image](https://user-images.githubusercontent.com/45329900/50573780-8c562c00-0dda-11e9-904f-964b04e0c669.png)

I give it up, can anyone tell me where these numbers come from??? My overall score should be 21-17 and it is 49-51 instead.

**Comment by Razviar** [comment]
Issue is fixed, new matches will be counted correctly. Old errors will remain, sorry, we can't edit old stats
