### ISSUE TITLE
Ranked Matches/decks not tracking

### ISSUE THREAD

**Issue by cs-joao-felipe** [Razviar/mtga-pro-tracker#248]
I've used Full Reset button already. Thou there is still a 15 or match gap that ain't tracking, I've noticed that within the W/L ratio tracker they are accounted for but they do not show up on the Match List.

I provided a Screen shot to better shot it, day(2018-12-29) started up fine with matches being tracked then it suddenly stopped, it resumed showing up next day(2018-12-30) but w/o opponent cards.

![image](https://user-images.githubusercontent.com/828103/50547064-b0b6da80-0c19-11e9-87fc-0ecac6555242.png)

**Comment by cs-joao-felipe** [comment]
On top of that Ranked matched are being considered ordinary matches

**Comment by Razviar** [comment]
It's fixed now. New matches will appear
