### ISSUE TITLE
Additional copies of a card in sideboard prevents cards in main deck from being exported 

### ISSUE THREAD

**Issue by OriginalThing** [Razviar/mtga-pro-tracker#251]
If you have additional copies of a card in your sideboard then when you export a deck the cards in the main deck aren't exported.

For example, when exporting this deck https://mtgarena.pro/decks/9r-19u-11c/ it results in only a 57 card main deck. Only the sideboard copy of Warkite Marauder is exported and not the 3 copies of Warkite Marauder in the main deck. If the Warkite Marauder is removed from the sideboard then the 3 copies of Warkite Marauder in the main deck are exported.

**Comment by Razviar** [comment]
It's fixed now. https://imgur.com/a/iVgYzBJ
