### ISSUE TITLE
Export deck language

### ISSUE THREAD

**Issue by npelle** [Razviar/mtga-pro-tracker#252]
Fail to import decks from mtgarena.pro to game with copy link and export deck options.

After trying many times I couldn't import decks due tue this error: the input strings contain an unknow card title: xxx xxx

One of the examples I have is the card "Forest". I have the game un spanish language, so I tried to change the word "Forest" to "Bosque" ("Forest" in Spanish) and the error for this card dissapeared. Then I have another error for the next card which I will have to translate, and so on.

I suggest that the exported card list use the language specified in the profile setting (in my case, Spanish).

**Comment by H4Z4RD-H42** [comment]
Same error here. I'm italian.
If i set english language for website and cards, the export list is in english, but if i set italian language, export list is in another language that i not know (german?), check the screenshot.

https://i.imgur.com/Qwgco0m.jpg
![image](https://user-images.githubusercontent.com/6650832/51797555-117c0780-2206-11e9-998b-2465f16867d8.png)

https://i.imgur.com/3XOIgJb.jpg
![image](https://user-images.githubusercontent.com/6650832/51797585-77688f00-2206-11e9-981e-661cf738662d.png)

**Comment by H4Z4RD-H42** [comment]
now work correctly.

**Comment by Razviar** [comment]
Fixed
