### ISSUE TITLE
collection progression chart shows I lost cards. pic attached 

### ISSUE THREAD

**Issue by Aziz10** [Razviar/mtga-pro-tracker#253]
not sure why this happened
 
<img width="1124" alt="screen shot 2019-01-01 at 2 41 03 am" src="https://user-images.githubusercontent.com/19154688/50569116-40ba6880-0d6f-11e9-9d2d-85510ed13f69.png">

**Comment by Razviar** [comment]
It's ok, see explanation here:
https://www.reddit.com/r/MTGArenaPro/comments/aauuf0/tracking_mayhem/?utm_source=reddit-android
