### ISSUE TITLE
Tracker app - match history error

### ISSUE THREAD

**Issue by Avadon83** [Razviar/mtga-pro-tracker#254]
Start using the app and it' great , but match history give of error
![screenshot_20190101-090515](https://user-images.githubusercontent.com/46244495/50570933-a6294c00-0da5-11e9-80b0-f8e8c0d0c6f3.jpg)

**Comment by Razviar** [comment]
API have changed, app will bed updated soon. Please wait for a few days

**Comment by Razviar** [comment]
It's fixed now
