### ISSUE TITLE
Wrong date on Gold and Gems progress

### ISSUE THREAD

**Issue by barretojs** [Razviar/mtga-pro-tracker#256]
**Describe the bug**
The gold progress is showing the wrong date for progress made after 2019, logging 2020 instead of 2019.

**To Reproduce**
1. Open the progress feature
2. Click on the Gold and Gems tab
3. Scroll over any progress made in 2019

**Expected behavior**
The date should be set to 01/01/2019, instead of 2020

**Screenshots**
![mtg_arena](https://user-images.githubusercontent.com/43803300/50598294-75bedc00-0e91-11e9-9564-f44336825f13.PNG)

**Additional context**
All the progress made on gold after 2019 is getting logged as 2020.

**Comment by Razviar** [comment]
Fixed
