### ISSUE TITLE
Changing the port MTGA uses?

### ISSUE THREAD

**Issue by nickbekke** [Razviar/mtga-pro-tracker#257]
**Problem:**
When i'm at work or any other place that uses a firewall to block incoming/outgoing traffic i can't use MTGA, i keep getting the following error;

> Could not establish a connection to environment:
> An exception has occurred while attempting to connect.
> wss://client.arenagame-b.east.magic-the-gathering-arena.com:9405/Prod/ws

**Solution:**
Use commonly used ports such as port 80 or 443 to connect to the MTGA servers and login, this way the game can be used on more public places such as hotels but specifically at work or behind a firewall :)

p.s.
I've tried to use different network adapters and by changing metrics on network adapters i was able to use MTG Arena at work behind a firewall. I did this using one network adapter (free internet connection without firewall) for MTGA and my LAN adapter for work related (domain) connections such as RDP/Citrix.

Sincerely,
Nick

**Comment by Razviar** [comment]
Sorry, we are not mtga developers, we are 3rd party software devs.
