### ISSUE TITLE
Warning 1946.Property when attempting to update

### ISSUE THREAD

**Issue by prugor** [Razviar/mtga-pro-tracker#259]
When attempting to update the following error is displayed. I've removed, reinstalled, and attempted to update. Same error each time.
![errormtgapro](https://user-images.githubusercontent.com/46383122/50704433-fa8a3100-101c-11e9-84f4-d23ce82d0db0.jpg)

**Comment by Razviar** [comment]
It's normal installer behavior. Click OK and keep installing.
