### ISSUE TITLE
Match history incomplete and 0:2 loss count in BO1 

### ISSUE THREAD

**Issue by 1MarkC** [Razviar/mtga-pro-tracker#262]
**Describe the bug**
I am missing matches being logged.
Also, some BO1 matches are logged as 0:2

**To Reproduce**
NA

**Expected behavior**
Correct tracking

**Screenshots**

Matches logged as 0:2 loss, while I only do BO1
<img width="956" alt="screenshot 2019-01-06 at 22 05 51" src="https://user-images.githubusercontent.com/46259937/50741607-ccb11200-11ff-11e9-8de1-94dadc708b83.png">

This match is missing from my matches history:
<img width="177" alt="screenshot 2019-01-06 at 21 13 39" src="https://user-images.githubusercontent.com/46259937/50741610-d5a1e380-11ff-11e9-9d06-7fe7cd9e2e72.png">

**Additional context**

**Comment by 1MarkC** [comment]
maybe the 0:2 loss stem from trying the manual re-sync button, to try and get missing matches loaded

**Comment by Razviar** [comment]
It's known issue, we are working on fix

**Comment by Razviar** [comment]
Now issue with tracking should be fixed, new matches will be tracked correctly. I have no idea about disconnects thing tho
