### ISSUE TITLE
Missing Data from Jan 3 thru Jan 5

### ISSUE THREAD

**Issue by tonymar** [Razviar/mtga-pro-tracker#264]
If this can't be fixed, please tell me how to read or parse the logs below?
Want Win Loss and Deck.  That would help a lot.

**Comment by tonymar** [comment]
It shows 1/2/2019 on my Matches
Then it shows 1/6/2019.
My Log shows: there are matches on 1-3 (3 each),1-4 (2 each), 1-5 (4 each).
Have done Full Reset, nothing happened
Have done Manual Reset, nothing happened
Have done Scan Old Logs, nothing happened
And right now says, "MTGA is not running!" and I did not turn it off.
Hope someone can help me.
![screenclip](https://user-images.githubusercontent.com/8173798/50772842-4e2e9180-124c-11e9-9a8b-ba0e769ac267.png)

**Comment by Yras** [comment]
how you made this logs?
i want have my logs like yours

**Comment by tonymar** [comment]
On the MTGArena.Pro it says, "Scan Old Logs..." when clicked it takes you to a folder with the logs in it.
The little box with the Token and Detected user.

**Comment by Razviar** [comment]
So what is status now? Have you tried to use that "scan old logs" function? Is game running detection works?

**Comment by tonymar** [comment]
Scan Old Logs does nothing. Does not add the missing dates.
Game is running when MTGA is running. Has new data.

**Comment by tonymar** [comment]
Played 4 Games on 1/8   Nothing on webpage. MGTAPro was running, saw the app on my desktop. 
![screenclip](https://user-images.githubusercontent.com/8173798/50908501-13ad2c00-13e7-11e9-8c0a-8b6b13fcc265.png)

**Comment by Razviar** [comment]
Old logs scanning is finally fixed.
