### ISSUE TITLE
Update available, cant update

### ISSUE THREAD

**Issue by Inous2018** [Razviar/mtga-pro-tracker#267]
When opening MTGA Pro Tracker, I get a prompt to update, but when I click the button an msi.exe opens and gives me three options: change (grayed out), repair, remove. I've tried the repair option to no avail. I also attempted the procedure to fix "tracker not updating." I have .NETFramework 4.7.2, tried getting a new token, uninstalled, reinstalled which didn't fix the problem. Looking on your release page I see that the latest version is 1.5.3 which is the version I have installed. How do I go about fixing this issue?

**Comment by nicktheone** [comment]
Same issue here since I think a week.

**Comment by Razviar** [comment]
Use full reset button on the tracker app. It will resolve the issue

**Comment by Inous2018** [comment]
This did not work, however, deleting the AppData under C:\Users\[USERNAME]\AppData\Roaming did work!

**Comment by Inous2018** [comment]
> Same issue here since I think a week.

Try deleting MTGAproTracker folder under this directory:

C:\Users\[USERNAME]\AppData\Roaming
