### ISSUE TITLE
Allegiance Booster Cards all showing as 5th copy 

### ISSUE THREAD

**Issue by Troubleshoot-Ron** [Razviar/mtga-pro-tracker#272]
**Describe the bug**
On the Booster Tab in My Arena all copies of Allegiance show as 5th copy (At least on 17/1/2019). Opened booster on 18/1/2019 looks to be correct.?

**To Reproduce**
1. Go to 'My Arena.'
2. Click on 'Boosters'
3. Scroll down to Allegiance Boosters Date 17/01/2019'
4. See error "5th Copy

**Expected behavior**
I have only opened 5 total boosters of Allegiance, so I know not every card is my 5th copy

**Comment by apoapostolov** [comment]
@Razviar this is resolved today, right?

I checked and can confirm same behavior, today's boosters look proper.

**Comment by Razviar** [comment]
Fixed
