### ISSUE TITLE
[Suggestion] Maybeboard

### ISSUE THREAD

**Issue by Alechilles** [Razviar/mtga-pro-tracker#277]
I think a really nice and important tool for any deckbuilder is a "Maybeboard", so users can keep a convenient list of cards they might swap in later. I've always used this feature extensively on sites like tappedout and aetherhub. This also helps fuel discussion in the comments section.

**Comment by Alechilles** [comment]
Example can be seen by scrolling down to the maybeboard on this deck on aetherhub: https://aetherhub.com/Deck/Public/54359

**Comment by Razviar** [comment]
We will add it. Also, it will clean up sideboards from "maybebording" and will help to divide bo1 and bo3 decks.
