### ISSUE TITLE
Filter Buttons Are Not Displayed When Using Firefox

### ISSUE THREAD

**Issue by Fat6andalf** [Razviar/mtga-pro-tracker#278]
I don't know if this is a known issue or maybe some setting on my end, When I use Mozilla Firefox and I go to the Browse Decks from the main screen or to Decks from My Profile the filter buttons for the mana type, Playable, Craftable, etc. are not visible. The links are there when I mouse over them but the graphic for the button is not visible. My screenshot illustrates this. Everything is fine when I use the Microsoft browser.![mtga issue 0-0002](https://user-images.githubusercontent.com/46227237/51632084-712f9580-1f1c-11e9-9f0b-3a9ff87189e7.png)

**Comment by Aquaman88** [comment]
Unfortunatelly we can not fix problem with Firefox browser. There are some buttons that can not be used in it. Please, try to use another browser.
