### ISSUE TITLE
bad url

### ISSUE THREAD

**Issue by v-gael** [Razviar/mtga-pro-tracker#279]
**Describe the bug**
Bad url when you want to access to "My Deck"

**To Reproduce**
1. Go to MTGA Pro Tools
2. Click on My Decks
3. See error

**Expected behavior**
redirect to https://mtgarena.pro/decks/?my

**Actual behavior**
redirect to https://mtgarena.pro/decks/#my

**Additional context**
Not a severe issue but annoying in the long run

**Comment by Razviar** [comment]
Fixed
