### ISSUE TITLE
W/L % Listed for Decks Can Differ Radically from Win / Loss Counts

### ISSUE THREAD

**Issue by fuzzyTew** [Razviar/mtga-pro-tracker#280]
EDIT: the example deck I linked is gone now, so I clicked the first one listed at the time I visited the deck list on the site and it has the same issue.

**Describe the bug**
Decks in the tracker have w/l percentages that mistmatch their counts.

**To Reproduce**
See https://mtgarena.pro/decks/goblin-aggro-2-5daaacc3-2c56-4641-b3f8-8ad034775971/ .  This deck is marked with a w/l ratio of 66.67%, but if one hovers over this metric today, it says "Global winratio. W: 6, L: 2".

These numbers don't match 66.67% .  If the ratio is calculated W/(W+L) to give the % games won, it would be 75%.  If the ratio is calculated W/L to give the ratio between them, it would be 300%.

**Expected behavior**
The percentage given should match 100 * W / (W + L) to not confuse the user.

**Comment by fuzzyTew** [comment]
Linked a new deck because old deck disappeared.

**Comment by Aquaman88** [comment]
Hi! Thank you for your issue. Now we can see next information: w25, l 15, global winrate 62,5. So it is a correct information.

**Comment by fuzzyTew** [comment]
@Aquaman88 thanks for fixing that deck, but it is still easy to find another deck with the issue.  For example https://mtgarena.pro/decks/esper-bo1-2/ is listed as 68.42% with W/L of 70/40, which should be 63.64%.

**Comment by Aquaman88** [comment]
Nope, here i see 74/40. So statistic is correct. Maybe we have that problem because we should wait some time before system will show us correct results.

**Comment by fuzzyTew** [comment]
74/40 doesn't make the statistic correct: that would be 64.91% .  It still says 68.42% even though the W/:L has changed.

**Comment by Aquaman88** [comment]
The information is updating every time. It happens because users are playing on this deck.  Now it is 88/48. So information will update..just give it some time.

**Comment by fuzzyTew** [comment]
I see; it takes a day to update the % from the W/L .  I guess a better issue report would simply be a feature request to note that somewhere near the statistic.  Thanks for bearing with me, Aquaman.
