### ISSUE TITLE
Opponent's Spotted Cards not showing in Match History

### ISSUE THREAD

**Issue by battaile** [Razviar/mtga-pro-tracker#282]
**Describe the bug**
On  my Matches History page, my matches have stopped displaying the opponent's spotted cards.

**To Reproduce**
1. Go to https://mtgarena.pro/matches/
2. See error

**Expected behavior**
Should be seeing the color image representing the opponent's deck which I can click on and view the cards they played during the match

**Screenshots**
![Screenshot](https://i.imgur.com/FFt8fR0.png)

**Additional context**
Have tried resetting, deleting log, rebooting, etc

**Comment by battaile** [comment]
Working correctly again as of this morning.

**Comment by Dayfid58** [comment]
I have the same issue. Started this morning after Magic Arena pushed out a new update. Perhaps they changed something and the dev needs to fix code. I will wait a few days. too bad, I use this feature a lot and miss it when it is gone.
