### ISSUE TITLE
Bug in Progress -> Collection (duplication of buttons)

### ISSUE THREAD

**Issue by leoschulmann** [Razviar/mtga-pro-tracker#283]
**Describe the bug**
Duplication of buttons in 'Progress' menu. 
![capture](https://user-images.githubusercontent.com/28384965/51801582-e10d8b00-2250-11e9-81af-14dc5097663d.PNG)

**To Reproduce**
1. Go to 'my arena -> collection'
2. Click on 'stats by expansion', select any set
3. Click "back" (tested on Chrome)
4. Get the usual progress window for collection, but with duplicated buttons and short link (mtga.cc/progress/#user)
5. Can be repeated, gaining additional rows of buttons.

**Comment by Razviar** [comment]
Thanks for report. It fixed now.
