### ISSUE TITLE
Deck list not loading

### ISSUE THREAD

**Issue by YelmsLight** [Razviar/mtga-pro-tracker#285]
**Describe the bug**
Deck listings don't appear when I select 'Decks' from my Social page.  However, I can access it by using 'My Decks' from the menu listing at the top.

**To Reproduce**
1. Go to my Social page:  https://mtgarena.pro/decks/?YelmsLight
2. Click on 'Decks.'
3. Deck listing never appears, just a loading symbol.

Also, the page defaults to only decks made in the last 30 days.  I can access the rest by changing the time frame to Empty, but it used to default to Empty, or some other option which showed all my deck builds since I started using the Tracker.  (Btw, the behavior changed after the point at which my earlier decks would no longer have been shown with the '30 day' option selected.)

**Comment by Razviar** [comment]
This bug is fixes, try ctrl+f5
