### ISSUE TITLE
Can't input my token

### ISSUE THREAD

**Issue by jeremy-boes** [Razviar/mtga-pro-tracker#290]
**Describe the bug**
I noticed the tracker crashed when trying to upload data automatically. I tried a manyal re-sync. Crashed too. So I full reseted, rebooted, and went on copying my token but nothing happened. The token is copied in the text box but the tracker does nothing.

I tried to reinstall the tracker, doesn't work either.

**Expected behavior**
When token is entered, tracker should initialise normally

**Screenshots**
![screen](https://user-images.githubusercontent.com/42269011/52051052-b4a88600-2552-11e9-9eab-c7c522b9de82.png)

I masked the token for obvious reasons, but it is copied in the textbox

**Comment by h333n** [comment]
same issue here. on 2nd pc I have it running for a couple of weeks already, but progress doesnt update. So I assume some web service is down at the moment...

**Comment by ergag** [comment]
I got same issue, after updating to 1.5.7 mtg pro apps (on windows 10).
My token are invalid according to the apps.

**Comment by drswizz** [comment]
Same (Win 10). I have uninstalled, reinstalled, restarted several times, checked my cables and wires, checked my internet connection, and allowed access through firewall. If that is of any help.

**Comment by chrtylee** [comment]
I didn't do all that, but I redownloaded and reinstalled the tracker and
made a new account. The new token is invalid as well.

**Comment by ergag** [comment]
there is new version 1.5.9
at least my token is now valid, but haven't tried all feature yet, since it still reading all my game log right now.

**Comment by chrtylee** [comment]
Yeah I did the tracker update, still no luck
