### ISSUE TITLE
Launch Application and Nothing Appears

### ISSUE THREAD

**Issue by RepinWolf** [Razviar/mtga-pro-tracker#292]
**Describe the bug:** Program seems to not start.

**To Reproduce:** Start the application executable.

**Expected behavior:** Program should start and a window should appear.

**Detail:**

I originally was running v1.5.3, allowed the app to update to 1.5.7 and then it when the update successfully completed, I clicked Open MTGA Pro on the installer. Seemingly, no process started and no window appeared. I then went to my Start Menu and attempted to launch it again - and again, no process I could find or window opened. I tried running as Administrator, no process or window. I uninstalled, reinstalled from GitHub, no process or window when attempting to launch again. I restarted my PC, same thing. It appears 1.5.7 just doesn't start or is crashing immediately on me.

I'm running Windows 10 Pro N v1809 (build 17763.253) and have .NET v4.6.2 or higher (1.5.3 MTGA Pro Tracker successfully used to run)

**Comment by RepinWolf** [comment]
Unrelated but upon migrating back down to 1.5.3, it pings Windows 10 for notifications to update the program every minute or two and is quite annoying.

**Comment by Razviar** [comment]
Can you tell me your username on MTGAPro?

**Comment by RepinWolf** [comment]
https://mtgarena.pro/u/Repin%20Wolf

**Comment by Razviar** [comment]
First of all, try to manually remove C:\Users\{USERNAME}\AppData\Roaming\MTGAproTracker folder

**Comment by Razviar** [comment]
I searched the logs. For some reasons you app wasn't able to download cards database on your PC.
We'll implement fix, but for now you can:
1. DOnwload https://mtgarena.pro/wp-content/plugins/mtgarenapro/js/cards_db_app.js manually
2. Put it into C:\Users{USERNAME}\AppData\Roaming\MTGAproTracker folder
3. Try to run updated app

**Comment by RepinWolf** [comment]
Okay, I will update the app again and then put that file in the folder - stand by.

**Comment by RepinWolf** [comment]
This appears to have worked. Thank you for your prompt help!
