### ISSUE TITLE
There is an outlier in the data on my "Progress" stat

### ISSUE THREAD

**Issue by AkiraChisaka** [Razviar/mtga-pro-tracker#296]
**Describe the bug**
In my stats, on the Progress page, you can find that there is a single day (Nov. 11th) where it shows that I have a completely full collection.

I'm not sure why this happens, but it doesn't really make sense, since it's a single outlier in my data.

So I was wondering if you can help me remove that data. Basically, if it is possible to remove all my data on Nov. 11th.

If not, can you help me reset my data?

**To Reproduce**
1. Go to https://mtgarena.pro/progress/#Akira
2. You can see there is a problem on Nov. 11th.

My account number is Akira#19066. If it might be useful.

**Expected behavior**
I want to remove the outlier on Nov. 11th. It would be fine if you need to remove all data on Nov 11th. Or even all data on my account.

**Comment by Razviar** [comment]
This is common bug, many users are affected and having this spike. We currently working on the solution.
