### ISSUE TITLE
tracker not recording matches anymore

### ISSUE THREAD

**Issue by barretojs** [Razviar/mtga-pro-tracker#304]
**Describe the bug**
my last record on the tracker is from 29/01, but i played on the 31st and today(2/2).

**To Reproduce**
1. Go to 'progress'
2. matches show 2/0 from 29th

**Expected behavior**
expected to show my recent matches but it's stuck on the 29th

**Additional context**
my profile: https://mtgarena.pro/u/karvalhus

**Comment by Razviar** [comment]
Have you updated to the latest version? Try "full reset" button

**Comment by m7m8m9** [comment]
I have a similar issue. For me the problem is that my matches are seem to be recorded and are visible in "Matches history". However there's no entries in "Progress" and there's no summary on main profile page.
/u/m7m8m9/
