### ISSUE TITLE
"My Arena -> Events" does not work anymore

### ISSUE THREAD

**Issue by leoschulmann** [Razviar/mtga-pro-tracker#306]
**Describe the bug**
Events page in "my arena" shows infinite loading animation

**To Reproduce**
100% reproduces on different machines on my account. 
It should contain some F2P drafts and CE's which I played recently.
Full reset does not help.
https://mtgarena.pro/events/#osleek

**Comment by Razviar** [comment]
I'll look into it

**Comment by Razviar** [comment]
Fixed. And now you can see your rewards.
