### ISSUE TITLE
Incorrect win/loss calculation

### ISSUE THREAD

**Issue by Hobuso** [Razviar/mtga-pro-tracker#315]
**Describe the bug**
Different calculation on differet pages

**To Reproduce**
You can see that my today (06.02.2019) ratio 5/3
But on the progress page i have 4/3
Also all my mathes were played using the same white deck and i have 1 match with "deck not captured" that are completely different

![image](https://user-images.githubusercontent.com/47399146/52368794-5141bb00-2a60-11e9-91ce-fbdd071478d1.png)
![image](https://user-images.githubusercontent.com/47399146/52368841-6b7b9900-2a60-11e9-9c8f-4c22a519bed7.png)

**Comment by Razviar** [comment]
Thanks for the report, I will investigate this. Mysterious "not captured deck" is old issue, but we still can't figure out why it appears. Will keep working.
