### ISSUE TITLE
Add the possibility to manually assign deck

### ISSUE THREAD

**Issue by Hobuso** [Razviar/mtga-pro-tracker#316]
**Is your feature request related to a problem? Please describe.**
Deck not captured issue

**Describe the solution you'd like**
Add the possibilty to manually assign deck (from my decks page) if it was not identified automatically

![image](https://user-images.githubusercontent.com/47399146/52369546-03c64d80-2a62-11e9-8538-d593c35a2433.png)

**Comment by Razviar** [comment]
We still have a hope to track down bug causing those un-captured decks, so for now we won't implement manual decks assignment.
