### ISSUE TITLE
Card type counts in deck listing incorrect

### ISSUE THREAD

**Issue by YelmsLight** [Razviar/mtga-pro-tracker#317]
**Describe the bug**
In the listing of a deck of mine, the listing shows 20 creature cards and 16 non-creature cards.  The listing for lands is correct, at 24.  Both numbers are off by 3.

**To Reproduce**
Go to my deck listing:
https://mtgarena.pro/decks/sultai-aggro-132/

**Expected behavior**
The deck listing should read 23 creatures and 13 non-creatures

**Screenshots**
![decklisting](https://user-images.githubusercontent.com/46224846/52387270-5d1c8580-2a3e-11e9-9125-8df28e6089a0.JPG)

**Additional context**
Since the difference is 3 cards, and the only combination of creatures which I have that matches that number is Hydroid Krasis, I deduce that that is where the issue is.  (Also, as I have reported before, the X part of the spell cost doesn't appear in the thumbnail listing for the card at the left.)

**Comment by Aquaman88** [comment]
Thank you for your report! Yes, Hydroid Krasis does not display in deck like a Creature. But in Smart Search we can find this card as a Creature. We will investigate this problem.
