### ISSUE TITLE
API for link to most recent draft deck

### ISSUE THREAD

**Issue by TomClancyIsDead** [Razviar/mtga-pro-tracker#318]
Hi! I'm a mod for a few streamers (including MPL players), and I'd love the ability to create a bot command on Twitch that shows the deck they drafted.

In order to do that, I need a stable url attached to their profile that returns a string that's the url of their most recent draft deck.

**Comment by Razviar** [comment]
We have link to the current deck streamer playing: https://mtga.cc/stream/#Razviar
But I'll add special link to current draft.

**Comment by Razviar** [comment]
Here you go, now draft can be permalink-ed like this: 
https://mtgarena.pro/stream/#draft-Kormack

**Comment by TomClancyIsDead** [comment]
Would it be possible to set it to the decklist tab by default?
