### ISSUE TITLE
MTGA is not running

### ISSUE THREAD

**Issue by MuddybuddyMTA** [Razviar/mtga-pro-tracker#320]
**Describe the bug**
message "MTGA is not running" displays

**To Reproduce**
Start MTGA

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47458698/52496560-8a754a80-2b88-11e9-9b5d-ca23ffc860e9.png)

**Additional context**
I've tried uninstalling, removing folders manually, reinstalling, rebooting, forcing log updates, etc, to no avail.

**Comment by Razviar** [comment]
I assume the game is running? Can you take a screenshot of your processes list with mtga in it? Maybe name of executable is different. Or for some reason app can't access the list of currently running processes on the pc
