### ISSUE TITLE
Database Error: Error establishing a database connection

### ISSUE THREAD

**Issue by alikoneko** [Razviar/mtga-pro-tracker#322]
**Describe the bug**
Random error establishing connection to database error

**To Reproduce**
1. Refresh any logged in open tab on the website.

**Expected behavior**
Session expired alert, and being asked to sign back in.

**Screenshots**
![image](https://user-images.githubusercontent.com/3050609/52526637-8aa93f00-2c89-11e9-960f-d1a1734e8116.png)

**Additional context**
Tracker is running.
MTGA is running. 
Hit from Firefox.

**Comment by alikoneko** [comment]
Feel free to ping me about this. I may be able to help you fix it if I have info about your stack.

**Comment by Razviar** [comment]
We are under heavy ddos, server is barely holding up. But we already have some solutions to counteract this threat
