### ISSUE TITLE
Open Source it!

### ISSUE THREAD

**Issue by alikoneko** [Razviar/mtga-pro-tracker#323]
**Is your feature request related to a problem? Please describe.**
I would like to do my own analytics beyond is provided, as well as run my own local version of the client for privacy reasons. This will also help ensure you are JUST parsing logs, and not sniffing passwords. Considering the client can be tied to a paypal or credit card number, this would be incredibly good form to ensure you are not doing anything illegal or against TOS.

**Describe the solution you'd like**
BSD or MIT opensource license. 

**Describe alternatives you've considered**
The log is a JSON document. I just have too many projects on my plate right now to figure out how to parse the file, manually. 

**Additional context**
You are deploying via an open source platform, built on code sharing and knowledge sharing from an open repo. Including a license and opening the project would be good form.

**Comment by Razviar** [comment]
I'll open source right after WOTC wool open source of mtga :)
