### ISSUE TITLE
Browser check then Error establishing a database connection

### ISSUE THREAD

**Issue by jeremy-boes** [Razviar/mtga-pro-tracker#324]
When I access mtgarena.pro I have a browser check, then an Error establishing a database connection.

This is probably still the DDOS attack though.

I created the ticket just in case it could be related to a faulty browser check.

**Comment by kenibrewer** [comment]
Can confirm that this problem is still ongoing

**Comment by AnnanFay** [comment]
They appear to be having database issues and there was a DDOS which might have contributed.

See the [latest twitter messages](https://twitter.com/mtgapro):

![image](https://user-images.githubusercontent.com/766048/52640690-f2040080-2ece-11e9-9e64-6382259228dc.png)
