### ISSUE TITLE
The "Need" Column

### ISSUE THREAD

**Issue by cptcanuck1** [Razviar/mtga-pro-tracker#325]
Not sure if this is being looked at already but my favorite feature was knowing how many wildcards I needed to build a deck.  It appears to be missing now

![image](https://user-images.githubusercontent.com/47669416/52867679-4fc66180-30f6-11e9-9749-0317d74fc3b2.png)

**Comment by MorgaineHH** [comment]
same here

**Comment by Razviar** [comment]
It's temporary disabled. Returning it today
