### ISSUE TITLE
Delete Account - why is it not possible to delete my account?

### ISSUE THREAD

**Issue by Episodic2** [Razviar/mtga-pro-tracker#327]
**Describe the bug**
In "edit profile" the link to delete the account doesn't exist. It shows only plain text:
To completely remove your account and all stored data click [plugin_delete_me]this link[/plugin_delete_me]

**To Reproduce**
1. Go to 'Edit profile'
2. Scroll down to the bottom, chapter Delete Account
4. See that there is no link to delete the account.

**Expected behavior**
Link should exist.

**Additional context**
I need to delete my account - now.

**Comment by Razviar** [comment]
Let me know your username, I'll delete it manually if you need it so much

**Comment by Episodic2** [comment]
It's Episodic#65464
thanks.

**Comment by Razviar** [comment]
I can locate it. Let me know what email was used for registration. You can send this information on admin@mtgarena.pro
