### ISSUE TITLE
Deck not changing for regular play

### ISSUE THREAD

**Issue by anonymous555** [Razviar/mtga-pro-tracker#329]
**Describe the bug**
When entering a non-ranked "play" match, the deck does not change.  Instead, a deck is used that is for another mode, such as ranked or singleton.   However, the deck switching and detection seems to work fine for other modes, such as ranked and singleton.  This seemed to break after the mtg update around Feb 14th.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Aquaman88** [comment]
Please, add a screenshot of this problem! It will help us too investigate the reason of the current situation!
