### ISSUE TITLE
Playable/Craftable statuses do not work properly

### ISSUE THREAD

**Issue by LaPillons** [Razviar/mtga-pro-tracker#330]
**Describe the bug**
All the decks are marked as playable on the main deck lists, despite they show missing cards icon when opened in detail (missing cards icons mirror the real state of the collection though), in both the website and the Android app.
Also filtering by playable/craftable does not work for the same reason

**To Reproduce**
Open featured deck list or whatever other deck list on the website
"Need" column shows all decks as playable
Pick a deck you know you are missing cards to complete, it's shown as playable as well
Open the deck details to see the real status of what's missing

**Screenshots**
![image](https://user-images.githubusercontent.com/47711065/52910844-a7530180-329d-11e9-8a96-2a864fb160b9.png)
![image](https://user-images.githubusercontent.com/47711065/52910852-bdf95880-329d-11e9-9694-8fe0d81af18c.png)
![image](https://user-images.githubusercontent.com/47711065/52910854-c6ea2a00-329d-11e9-9979-40511e07418a.png)

**Comment by ecbrodie** [comment]
Also reported on Reddit: https://www.reddit.com/r/MTGArenaPro/comments/arn1ct/need_card_area_not_displaying_properly/

I have personally been seeing this bug ever since I created a new account after last week's user data wipe.

**Comment by iurirolho** [comment]
i also have this, noticed when i tried to find decks with cards, i hope its fixable and good luck on the progress

**Comment by Aquaman88** [comment]
Thank you for your report! We are currently working with the solution!

**Comment by TheWhiteAndTheBlue** [comment]
I also have this issue. Thanks in advance for working to resolve it!
