### ISSUE TITLE
Card popularity statistics

### ISSUE THREAD

**Issue by Mellontoss** [Razviar/mtga-pro-tracker#333]
**Card popularity calculation**
Currently, I guess, you calculate usages of cards in NPE decks too, which leads to cards that are almost never used outside of those NPE decks being on top of the rating. For example, according to your stats, Murder, Leonin Warleader and Meteor Golem are top 3, 5 and 7 used cards respectively, all in more than 20% decks. 
![scr0974](https://user-images.githubusercontent.com/21125290/52935906-bd2ef800-336b-11e9-9bed-a0592f90c631.png)

Also it calculates popularity for same cards but different arts/sets separately (be it cards from different expansion, alt art reward card or just different basic lands)
![scr0973](https://user-images.githubusercontent.com/21125290/52935549-bfdd1d80-336a-11e9-87f0-520b073b598b.png)
![scr0972](https://user-images.githubusercontent.com/21125290/52935484-98865080-336a-11e9-8456-b3ef616156d8.png)

**Suggestion**
Exclude NPE decks and decks that are alters of NPE decks by some small amount, that people usually do in their first couple days of playing (lets say, less than 5 cards difference from NPE decklist, for example)
Calculate popularity not for each unique card, but for each unique card name. Maybe remove basic lands when calculating relative popularity cause they skew numbers pretty hard, and later just calculate it for them separately without adding to general card pool.

**"Not so sure about" suggestions**
Maybe it would be a good idea to remove decks that dont have a single game recorded for them at all, or, maybe, dont have any games recorded for them in recent time (lets say, like, 3 months or so), cause people tend to not delete old decks and numbers can get skewed towards cards that arent really used anymore but were used a lot in previous meta.

Calculate average number of card used. For example some buildaround cards like Arclight Phoenix or Nexus of Fate or just really high powerlevel cards like Teferi or llanowar elf are most likely in every deck they are played 4 copies are included. And some cards are sometimes are ran as 1 off wincon like Chromium or Dawn of Hope. This statistic might be pretty interesting and cool to know.

**Comment by Aquaman88** [comment]
Thank you for your opinion and feedback! We will investigate this question in nearest future.

**Comment by Razviar** [comment]
Npe decks are excluded from calculation

**Comment by Mellontoss** [comment]
Yeah, saw that. I believe you did it couple days ago already. Those stats actually look pretty cool and a lot closer than i expected to be to things i actually see on ladder, really cool info. And even though meteor golem is still rocking 10% somehow and different art cards aren't fixed its actually working amazingly well cause leftover stuff skews numbers just a tiny bit and is pretty minor. Thanks a lot for providing such an amazing tool to the community and reacting to feedback so fast :>
