### ISSUE TITLE
No valid token and account wiped at the website

### ISSUE THREAD

**Issue by vault101** [Razviar/mtga-pro-tracker#334]
**Describe the bug**
After update to 1.6.0, it didn't remember my token. When I enter the old token, it shows No valid user token installed. When I logged into the website, it mentioned a wipe and needed to change my nickname. And there is a different under my account. But I can't find any description about this wipe anywhere.

**To Reproduce**
1. Go to https://mtgarena.pro/mtga-pro-tracker/, login as nma.vault103@gmail.com
2. There is a different token and everything is wiped.

**Comment by Aquaman88** [comment]
Hello! Even after you change something in account, information about your collection and decks will be the same. If you have another token on https://mtgarena.pro/mtga-pro-tracker, you should turn buttom "full reset" in deck tracker. Also you should just change settings and add new token. After that you can work with new token but with old MTGA account.

**Comment by vault101** [comment]
> Hello! Even after you change something in account, information about your collection and decks will be the same. If you have another token on https://mtgarena.pro/mtga-pro-tracker, you should turn buttom "full reset" in deck tracker. Also you should just change settings and add new token. After that you can work with new token but with old MTGA account.

Hi, there is no collection or progress or match history under my email account now, do you mean that when I reset and add new token, these are back? So is the whole profile connected to the token, the MTGA account or mtga-pro email account?

**Comment by Aquaman88** [comment]
Yes, you should turn button "full reset" and add new token in tracker. After that you can use tracker in game. You can check your progress, matches and decks on site after playing some games.

**Comment by vault101** [comment]
> Yes, you should turn button "full reset" and add new token in tracker. After that you can use tracker in game. You can check your progress, matches and decks on site after playing some games.

But what about previous match history under the email account? I didn't find any description about this wipe. Is it some bug of the server or is this wipe a regular thing in the future?

**Comment by H4Z4RD-H42** [comment]
@vault101 https://twitter.com/mtgapro/status/1094349971317493760

**Comment by vault101** [comment]
> @vault101 https://twitter.com/mtgapro/status/1094349971317493760

OK, that's very unlucky.

**Comment by Spongman** [comment]
wtf!? i just discovered all my account was wiped.

seriously, though. how does a DDoS attack result in a corrupt database? did it get the backups, too?

**Comment by Aquaman88** [comment]
https://www.reddit.com/r/MTGArenaPro/comments/aqo5cj/mtgarenapro_were_back/

**Comment by Spongman** [comment]
Not sure that answered the question. How does a ddos delete a database on the server? Weren’t there any backups of said database?
