### ISSUE TITLE
Error Installing Pro Tracker: "Directory must be on a local hard drive"

### ISSUE THREAD

**Issue by anditsgone64** [Razviar/mtga-pro-tracker#335]
Hi,
I'm having a problem installing MTGarena Pro Tracker. During the step when to chose install directory the installer states: "Installation direcory must be on a local hard drive" (see screen shot)

The installation directory is my usual directory for programs (c:\program files (x86)\) und I did not have this issue with other programs before.

I also did manually create the directory in windows explorer - still the same error message.

I'm running Windows 7 (64bit) and Pro Tracker v1.6.0)

Would be great if you could help me out.

![mtgarenapro_error](https://user-images.githubusercontent.com/47775460/53003522-64289800-342f-11e9-9924-c6ac1fb310dc.jpg)

**Comment by Razviar** [comment]
It's generic Windows error. Try to run console as Administrator and execute following command:
msiexec /i C:\path_to_ID_software_package\ID-software-package-name.MSI
