### ISSUE TITLE
Match History Issue

### ISSUE THREAD

**Issue by chrispt** [Razviar/mtga-pro-tracker#339]
I get the following when going to Match History:

![image](https://user-images.githubusercontent.com/1679097/53201857-0b096180-35f3-11e9-930a-d9f528e98c95.png)

Desktop Tracker is running v 1.6.1 Android Tracker is running v 1.1.0

**Comment by Aquaman88** [comment]
Thank you for your report. We will investigate it and try to find solution as soon as possible.

**Comment by chrispt** [comment]
So I just checked today. I am seeing Match History now. All of my recent ones, except the first one I played yesterday, are not showing data on the cards my opponent played though.

![image](https://user-images.githubusercontent.com/1679097/53250388-47d36800-3688-11e9-8fa1-2792cd73d434.png)

**Comment by Aquaman88** [comment]
Now this functional should work correctly.
