### ISSUE TITLE
Collection language settings

### ISSUE THREAD

**Issue by Nil-00** [Razviar/mtga-pro-tracker#341]
**Describe the bug**
When i accessed my collection today most cards are shown with Asian texts with a few exceptions in between that are English. So i looked for some language settings and saw the language option - and switched it to German for testing purposes. The collection now appeared in German as expected. When i switched back to English most cards are back to Asian text.

**Screenshot**
![image](https://user-images.githubusercontent.com/31095242/53287115-1d60d800-3778-11e9-8970-5eaa4b99d1ca.png)

**Additional context**
I already tried a full reset without success.
Account name: NIL
MTGA Account name: NIL#76331

**Comment by Aquaman88** [comment]
Hi! Thank you for your issue! This bug was already fixed. Please, turn CTRL+ f5.

**Comment by Nil-00** [comment]
yep solved - closing the issue
