### ISSUE TITLE
Wins not counted if opponent concedes

### ISSUE THREAD

**Issue by Amblyopius** [Razviar/mtga-pro-tracker#343]
I have noticed that in most cases when the opponent concedes it is not counted as a loss and the tracker does not see that the game has ended (still seeing the cards while on the main screen and the timers only reset after a new game has started). As a result W/L is a bit meaningless as a guide to performance of a deck.

**Comment by Razviar** [comment]
Is it 100% repeating pattern?

**Comment by Amblyopius** [comment]
Apparently not. It happened 3 times today but I played a few games to get someone to concede and when someone did it worked fine. I will play until it happens again to try and figure out what is causing it. I will keep notes of turn, phase ... it happens in.

**Comment by Razviar** [comment]
Thanks for that, please let me know if you find any pattern.
