### ISSUE TITLE
[iOS App] Decks > My decks displays "No results found"

### ISSUE THREAD

**Issue by CircuitMusicLabs** [Razviar/mtga-pro-tracker#345]
In the iOS app, the "My decks" section displays "No results found", while on the website, all decks are displayed and the stats can be viewed without problems.

App:
![mtgapro_app](https://user-images.githubusercontent.com/9432799/53521661-02c09300-3ad9-11e9-9933-f2bd051101f5.png)

Website:
![screen shot 2019-02-27 at 21 45 59](https://user-images.githubusercontent.com/9432799/53522084-f8eb5f80-3ad9-11e9-8c3e-8b806951bd49.png)

**Comment by Aquaman88** [comment]
Thank you for the information. We will check that.

**Comment by Aquaman88** [comment]
We have already find the solution. Everything should be okay.

**Comment by CircuitMusicLabs** [comment]
Thanks for checking it out! But in my case, it still says „No results found“. Do I need to re-sync before my decks are displayed? I‘m not able to run my computer at the moment.
