### ISSUE TITLE
Wrong deck exported on the Website

### ISSUE THREAD

**Issue by pozz94** [Razviar/mtga-pro-tracker#346]
**Bug Description:**
On the website, I tried to find and export a deck just to visualize and export another.
The decklist is correct but the statistics that are displayed and the export list are of an entirely different deck.

**To Reproduce:**
1. Go to https://mtgarena.pro/decks/.
2. Select craftable decks.
3. Order by descending W/L ratio.
4. Select a deck.
5. The selected deck and the visualized one are different.

**Expected behavior:**
Visualize and export the selected deck.

**Screenshot:**
![image](https://user-images.githubusercontent.com/9422368/53577736-7ebce880-3b76-11e9-9bd6-d21aeab7dd43.png)

**Additional context:**
In my case, the selected deck was "Mono Red Aggro" by no-one (Null) posted on Feb 15, 2019.

**Comment by Aquaman88** [comment]
Thank you for the message! We will investigate your issue.
