### ISSUE TITLE
Sideboard guide

### ISSUE THREAD

**Issue by SebaFR7474** [Razviar/mtga-pro-tracker#351]
Is it possible to add an a easier way to add sidebaord guide.

Like when we edit the deck, we add a matchup deck name, and we can add the card we get in and out, using the same way we add card to sideboard for exemple, or an other way ?

Thank when we go to the deck, it shows a sheet of the sideboard guide ?

Thanks

**Comment by Aquaman88** [comment]
Hi!Thank you for your message. Sideboard is one of the main parts of playing events. But for now, i can not see how can we add some sideboard guides.
