### ISSUE TITLE
Can't login with twitch

### ISSUE THREAD

**Issue by mriva** [Razviar/mtga-pro-tracker#352]
I was registered and using mtgarena pro before the database collapse. Now if I try to login with my twitch account the system says "We unfortunately could not retrieve your email address from Twitch.tv. Please enter your email address in the form below in order to continue." but if I enter my email it says "This email is already used by another account" which I assume is my old account.

What can I do to log in succesfully?

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. Please, try to use another social login. For example, you can use facebook or google. Also you can try to turn CTRL+f5 and try to login with your twitch account. Also you can try to login with your twitch account in other browser.

**Comment by mriva** [comment]
Login with google works. I wanted to use twitch login to see if I still had old data, or were all accounts wiped?

**Comment by Aquaman88** [comment]
Your personal account includes all social logins. So current information from google login is the most actual information for you now. Unfortunatelly old data was wiped.
