### ISSUE TITLE
Sealed constructed for Friends/Direct Challenge

### ISSUE THREAD

**Issue by Wutang787** [Razviar/mtga-pro-tracker#355]
Hello,

I would like to make a suggestion for content. I really like to do sealed constructed, but there is no way to do so with my friends. It would be wonderful if there was a way to do a direct challenge, and so long as both players had the same amount of the same type of unopened packs, to allow two players to create a sealed constructed deck with their unopened packs. It's nice buying packs, and part of the fun is opening them. But virtually, it feels like a dull experience. There is no tactile feel or joy in opening an unopened pack other than seeing what is there to be used to boost ones ability to tool a deck for some type of constructed event. Could you please create a way to take our unopened packs to our friends and challenge them to create something wonderful and exciting with it. I can see that there would be challenges with regard to, 1. dusting, and 2. no way to give wild cards. But I would gladly forego the perks of extra cards in the event I had 4 copies, or wildcards to enjoy opening packs with my new online friends in Arena.

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. You should write your ideas on main forum of MTGA or MTGA subreddit. We can not help you right now. We are waiting for upgrading the social part of game (spectator mode, friend list etc). We hope, that after that we will add more functions for our tracker.
