### ISSUE TITLE
Changing name in game (by the wizards support) makes The Pro Tracker not work, even if you chance your alias on site.

### ISSUE THREAD

**Issue by iglesfalco** [Razviar/mtga-pro-tracker#356]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. You can try to solve this problem after clicking button "Full reset" in your tracker. Also you should check the valid token in tracker and the name of your account in tracker`s settings. You can also try to reinstall your tracker. Sometimes users remove program manually and then install tracker again. Programm Data directory is at appdata/roaming/mtgaprotracker .

**Comment by iglesfalco** [comment]
Worked like a charm, Aquaman88. Thanks for you support.
