### ISSUE TITLE
Displaying if a card was scryed to the top or bottom of the deck

### ISSUE THREAD

**Issue by nantukoavatar** [Razviar/mtga-pro-tracker#357]
This is related to the problem that the display of 0 top, 1 bottom. is both temporary and not on the screen for very long. With things like Sphinx of Foresight that scry multiple cards remembering how many the opponent scryed to the top can be difficult. While in paper I can ask the opponent how they scryed, or on MTGO I can look at the game log. This is not an option in MTGA.

**Describe the solution you'd like**
An indicator on the cards in the deck that have been scryed both to the top or bottom of the deck. This is similar to how if a card is placed on top of the deck an image of that card is displayed on top of the deck. This why I can at any time check how many if any cards have been scryed to both the top and the bottom. Ways to do this would be a text overlay of "Scryed", "Scryed". It could also be an icon of some kind. 

This would also be able to be used for things like Survail to display how many have been played back in the deck by the opponent.

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. There are some ways to add copies to your deck or remove cards from it during the game. Also there are some cards with mechanic of card scrying. But tracking those functions are not so popular in different trackers in Collectible Card Games. This function should be basic in the game (like in mtgo). Maybe in future we will add function that can track those situations.
