### ISSUE TITLE
Switching accounts sometimes not recognized.

### ISSUE THREAD

**Issue by jimthev** [Razviar/mtga-pro-tracker#358]
**Describe the bug**
Switching accounts and/or starting mtgarena pro after switching accounts doesn't track the new account and uploads account data to wrong user.

**To Reproduce**
I've had it not track changing accounts and I've had it not recognize the new account when I start the mtgarena.  It appears to happen randomly so I don't know what triggers it.

**Expected behavior**
Don't upload data unless the MTGA nick matches that of the account.  Also recognize the correct user.  Also don't update data if data shows loss of cards.

**Screenshots**
![image](https://user-images.githubusercontent.com/5429073/54074068-548cba00-424b-11e9-848b-29cb525a1f4b.png)

**Additional context**
I have to reset the account/mtga arena to clear the bad data.  Maybe having an optional user prompt before uploading data would help.

**Comment by jimthev** [comment]
Here is the what another account sees:
![image](https://user-images.githubusercontent.com/5429073/54074148-56a34880-424c-11e9-9da4-c6b89a35ea7d.png)

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. Several accounts support remains problematic and not guaranteed. We will try to fix it, but we can't promise any deadlines on that.
