### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by coolmarat** [Razviar/mtga-pro-tracker#360]
**Describe the bug**
When I try to start application it crashes immediatly and I have no see UI, but in tray there is icon with balloon message that there is no valid token.

**To Reproduce**
1. Install 1.6.4
2. Start.
3. Crash.

**Expected behavior**
1. Install 1.6.4
2. Start.
3. UI Appeared.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/7396426/54084469-fc84af00-4341-11e9-96bf-571dbf6261af.png)

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. This is a local problem. First of all, you can try to turn off your antivirus or other programs, which can block the tracker.

**Comment by Razviar** [comment]
Check if there's error log file in app installation folder

**Comment by coolmarat** [comment]
There are only 2 files in application folder: MTGApro.exe, MTGApro.pdb. There are no logs and no cards DB files.

**Comment by Aquaman88** [comment]
Unfortunately, we cannot help you with this local problem. The only one reason of it is the  block of your own system (for example, Windows Brandmauer or other programs can block the start of install process).

**Comment by riQQ** [comment]
Downgrading to .NET Framework 4.5.2 might help you as this could be the same as https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3662.
