### ISSUE TITLE
Incorrect boosters stats 

### ISSUE THREAD

**Issue by Noprimal** [Razviar/mtga-pro-tracker#363]
While all the boosters seem to be correctly imported to the site, the stats doesn't sum it right. It seems to count only one booster a day and the other ones are just not added.

https://mtgarena.pro/stats/#Noprimal 

You can clearly see in the "economics" part that only 1 booster is taken into account a day.
In "totals" you can see that I have more boosters than cards.

( here are my boosters https://mtgarena.pro/boosters/#Noprimal . I opened way more than 1 per day )

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. I see more than 1 pack per day. The service works correctly. Maybe you should just wait and the stats will be updated.

**Comment by Noprimal** [comment]
Well that's been 14 days now so I thought I'd share my experience in case of.

**Comment by Aquaman88** [comment]
Thank you for your issue. I have just opened some packs in another account. Statistic shows the correct information. We should investigate this phenomenon. And you should try to turn CTRL+F5.

**Comment by Noprimal** [comment]
Thank you !

I tried ctrl + f5 but it didn't change anything. I got the same informations on my other computer so I don't think that's just browser problem.

**Comment by Aquaman88** [comment]
Hi! I tried to open another 2 packs, statistic works correctly.

**Comment by Noprimal** [comment]
Yes, This seems to happen only to me and I don't know why. Some other people might experience it but I'm the only one reporting it for now. I'm quite sad cause I love those stats and what is done in general.

( I was playing hearthstone and held an excel file with all my packs to have stats as well. I was therefore happy to find such a nice addon to magic but my bad luck follows me everywhere I guess ¯\_(ツ)_/¯ )

**Comment by Noprimal** [comment]
Why closing it while the bug is still there ?
