### ISSUE TITLE
Wrong deck content in deck lists

### ISSUE THREAD

**Issue by fuzzyTew** [Razviar/mtga-pro-tracker#365]
**Describe the bug**
Wildly different decks can be brought up when a deck summary is clicked in the community deck list.

**To Reproduce**
1. Go to https://mtgarena.pro/decks/?community
2. Click on 'Rating' until decks with a *negative* rating are shown at top
3. Observe that for example Azorius Aggro bo3 is listed as a white and blue.
4. Click 'Azorius Aggro bo3'.
5. Observe that this deck is in fact red, and neither white nor blue.

**Expected behavior**
The summary of a deck should match its content.

**Comment by Aquaman88** [comment]
Thank you for your message. A lot of decklists were broken after crashing database.  That is why the decklists from the past can be incorrect. As for new decks, everythig is now working correctly and youy can see the correct decklists.

**Comment by Razviar** [comment]
Now wrong decks are not displaying
