### ISSUE TITLE
Card popularity statistics again

### ISSUE THREAD

**Issue by Mellontoss** [Razviar/mtga-pro-tracker#368]
I dunno why, but card popularity stats show kinda unbelievable stats for basic lands. I have no clue as to what is causing that, but its pretty hard to believe that basic island is in 98% of decks.
![image](https://user-images.githubusercontent.com/21125290/54489934-7b3d9700-48c2-11e9-8669-4098337fb6cc.png)

**Comment by Aquaman88** [comment]
Hi! Thank you for your message! there are different types of each basic land (https://imgur.com/t7Wj4QM) . But all of them were used by players. The card popularity means, that players use it in deck with current color.  98, 61 - 164501 unique deck. You can see another Basic Lad Island on screen with 26,58 - 44344 unique decks.

**Comment by Mellontoss** [comment]
Oh... got it
