### ISSUE TITLE
Use the Releases feature please! Don't commit binaries to your repo.

### ISSUE THREAD

**Issue by GregRos** [Razviar/mtga-pro-tracker#373]
Hey, I'm Greg. I'm a software developer who happens to be an MtG: Arena player. I have lots of projects here on GitHub, and I wanted to give some advice :smile:

I just saw you committed the binaries for the application to your repo (the zip file). Git isn't good at tracking changes to binary files, and storing them in the repo (especially ephemeral ones like releases) will cause your repo to grow in size quickly.

GitHub provides a nifty [Releases](https://help.github.com/en/articles/creating-releases) feature that lets you publish releases. It's also where lots of users look for them.

**Comment by Razviar** [comment]
Done. Thanks for the advice!
