### ISSUE TITLE
command line option to stick with software rendering

### ISSUE THREAD

**Issue by trufanov-nok** [Razviar/mtga-pro-tracker#375]
I'm trying to launch the app via wine under linux. It won't start due to some problems which are directx related in my opinion.
Could you add an optional program launch argument to enforce software rendering? Like described here: http://blogs.microsoft.co.il/janiv/2009/06/07/hardware-acceleration-in-wpf/
Perhaps this will help...

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. It is a local problem, so unfortunately we cannot help you. But we will investigate situation with installing on linux.

**Comment by trufanov-nok** [comment]
Count me in if you'll need a tester
