### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by chesspi** [Razviar/mtga-pro-tracker#377]
My issue is I just don't know how to properly install the program. I see the WIXPROJ file and the WXS file but don't know what to use to install it as my computer has no idea what to do with it. Can someone help me out???

**Comment by ianirons** [comment]
I was doing the same thing until I realized to check the Releases section. MSI installer is on https://github.com/Razviar/mtga-pro-tracker/releases

**Comment by chesspi** [comment]
Thanks. I'll check it out tomorrow.
