### ISSUE TITLE
Constructed Rankings bug

### ISSUE THREAD

**Issue by Spongman** [Razviar/mtga-pro-tracker#379]
https://mtgarena.pro/progress/#Spongman, "Constructed Rankings"

````
Cannot read property 'getTime' of undefined
````

![image](https://user-images.githubusercontent.com/1088194/55534811-2f347580-566a-11e9-92a0-c93e5935a6d7.png)

**Comment by Aquaman88** [comment]
Hi! Thank you for you message. Everything should work correctly. It is a local problem. Try to turn-off your adblocker and upgrade plugins.

**Comment by Razviar** [comment]
I just checked and your constructed ranking tab is working fine. 
![Screen](https://user-images.githubusercontent.com/29640542/55803630-67610b80-5ae3-11e9-93ae-1652b0dbccab.png)

**Comment by Spongman** [comment]
Yeah looks like it works now. Didn’t have to change anything on my end, though.
