### ISSUE TITLE
Summoning Sickness Indicator

### ISSUE THREAD

**Issue by sobrio35** [Razviar/mtga-pro-tracker#382]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sobrio35** [comment]
I've noticed I can't tell which creatures have summoning sickness - in particular when I have tokens on the field and want to pump or put counters on those attacking. I sometimes target the wrong creatures for that reason. Does this feature already exist? If not, I think it would be a good value add.
Thanks!

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. First of all, you should tell about this feature on official MTGA game forum. I do not thing that it should be the function of our tracker.
