### ISSUE TITLE
My Desk List is the only list being shown

### ISSUE THREAD

**Issue by Dorky106** [Razviar/mtga-pro-tracker#385]
**Describe the bug**
Wont show anything other then my list of decks, even in a match for some reason.
I've already re-installed once, no idea what is going on.

**To Reproduce**
No Idea

**Expected behavior**
Should show the list of cards in my deck

**Screenshots**
[https://www.dropbox.com/s/7txv7rrcc5123l9/Screenshot%202019-04-09%2019.32.04.png?dl=0](url)
Can get a better SS when I get back, about to head out and wanted to post about this issue I'm having.

**Comment by Aquaman88** [comment]
Hi! Unfortunatelly i do not see your screenshot. Please, add it again here and i will try to investigate your problem

**Comment by Dorky106** [comment]
Took new screen shot in a practice match
But it does that no matter what kind of match it is for me.
![Screenshot 2019-04-10 07 23 12](https://user-images.githubusercontent.com/2104796/55875144-4ab7e880-5b62-11e9-9bf7-b7eef437bb1e.png)

**Comment by Aquaman88** [comment]
Thank you for the screenshot. Do you use the latest version of the tracker? We had the problem like this , but after updating everything should work correctly.

**Comment by Dorky106** [comment]
Downloaded latest from the start and it was doing it, so...
Like I said though it randomly started working.
