### ISSUE TITLE
"What's in the next booster" loading speed

### ISSUE THREAD

**Issue by Mellontoss** [Razviar/mtga-pro-tracker#386]
**"What's in the next booster" part causes entire boosters page load slow**

Images for every single rare and mythic card are too high quality and that causes entire page to lag out when loading them. While this isnt a problem for sets i have almost all rares and mythics of, for sets where i dont have 4-of of most of them it causes entire page to lag and load extremely slow. Sometimes even popup that page isnt responding appears and suggests reloading page. 

Possible solution: load small thumbnails of cards instead of full high-quality images, and load cards themselves only on mouseover or when every other element is loaded.

**Comment by Mellontoss** [comment]
P.S. it only lags on first load, sometimes after you load it next time you open same page it loads way faster, i assume it caches images somewhere, but after some time it turns into lag gallore again

**Comment by Razviar** [comment]
Thanks for bringing this to my attention. We already have thumbnails, and links to full image is set by mistake. Will be fixed very soon.

**Comment by Razviar** [comment]
Fixed
