### ISSUE TITLE
Deck Management (Deletion)

### ISSUE THREAD

**Issue by 29** [Razviar/mtga-pro-tracker#387]
There is currently no visible option to remove a deck from my own deck list apart from a total account wipe (I presume this also wipes that data).

A delete button on the list page when you hover over the deck image (in the area marked in ss1) or a separate button in the deck management section below the cards when viewing a deck (marked in ss2).

![ss1](https://user-images.githubusercontent.com/810101/55993156-66afad00-5c7c-11e9-8a60-15f896d933a7.png)

![ss2](https://user-images.githubusercontent.com/810101/55993163-6c0cf780-5c7c-11e9-8c8c-2c63e09ca00d.png)

I apologize if this has already been requested, I search multiple times for this and could not find anything matching.

**Comment by Aquaman88** [comment]
Hi! To remove deck, you should turn "Edit name and Format" ( it looks like a pencil) and then turn "Remove". After that, your deck will be removed.
