### ISSUE TITLE
Is there an API that lets you interact with the game?

### ISSUE THREAD

**Issue by pawarren** [Razviar/mtga-pro-tracker#388]
From what I've read, this and other projects listen to log files. Can MTGA Pro Tracker interact with the game, for example programmatically playing a specific card?

**Comment by Aquaman88** [comment]
Hi! Thank you for your question. No, we can not change anything in game. But we can give the resources for analyzing in different situations during the game according to statistic.

**Comment by pawarren** [comment]
Thanks for the response!
