### ISSUE TITLE
Favorite decks from other users can't be added to the craft list

### ISSUE THREAD

**Issue by osnofa** [Razviar/mtga-pro-tracker#393]
Just like the title says. Even though there is a craft icon on a Favorite deck, and even though I click it, in doesn't appear on my Craft List.

To reproduce:
1. Add a deck from the community to your Favorites;
2. Go to the list of your favorite decks;
3. Click on the craft icon for that specific community deck you just added to your favorite list;
4. Go to your Craft List;
5. The deck doesn't appear on the Craft List.

I expected the deck to be on my Craft List.

Thanks for reading.

**Comment by Aquaman88** [comment]
Thank you for your message. We will investigate your issue

**Comment by Aquaman88** [comment]
Fixed

**Comment by osnofa** [comment]
Thank you very much!
