### ISSUE TITLE
decks

### ISSUE THREAD

**Issue by MayaPlays** [Razviar/mtga-pro-tracker#394]
hi i just need help because the link function to show all my decks to my viewers is not working at all 
https://mtga.cc/decks/?MayaPlays

**Comment by Aquaman88** [comment]
Hi! Now I see only one deck after clicking this link

**Comment by Aquaman88** [comment]
Do you have more not hidding from other decks? The function Hide from others give you a chance not of hidding your decks from others. It can be the reason of your problem too.

**Comment by tarantula2107** [comment]
I'm having this problem as well. I re-imported the missing decks. and they won't sync up even while Arena's running. I can verify that hiding a deck from public view has bullshit to do with the error. You can't see the decks formatted #. Name in the screen below on my page (mtga.cc/decks/?TurkeySloth ).
![Hidden decks](https://user-images.githubusercontent.com/40201918/56475803-92d8e400-645b-11e9-8da0-74c56f982fbc.png)

**Comment by Aquaman88** [comment]
Thanks, we will investigate this phenomenon.

**Comment by Aquaman88** [comment]
Fixed
