### ISSUE TITLE
Progress card collection

### ISSUE THREAD

**Issue by Pettyx2** [Razviar/mtga-pro-tracker#395]
**Describe the bug**
In the progress page that gives out stats for card collection completion, the totals of card collected by cards and by unique cards differ from the stats shown in the graph, (namely 19/40 and 22.5/47)

**To Reproduce**
Just open the progress page
**Expected behavior**
for the same stats to appear the same in different places

**Screenshots**
![image](https://user-images.githubusercontent.com/26479831/56473071-72625700-6466-11e9-9174-10a9e1462bb1.png)

**Additional context**

If I misinterpreted the stats and they refer to different values, please feel free to let me know what they refer to.

**Comment by Aquaman88** [comment]
Thank you for your message! We will investigate this phenomenon.

**Comment by Aquaman88** [comment]
According to investigation, statistic on the graphics can include some non-craftable cards in your collection.  But they are a part of your collection. So,  you can see all craftable cards (the main statistic) in in your collection in "Total". That is why those stats have a little bit different values.
