### ISSUE TITLE
Matches History retrieving matches from other players using the same computer

### ISSUE THREAD

**Issue by e-berg** [Razviar/mtga-pro-tracker#396]
So i found matches in my match history that don't belong to me. I can tell they are played with a deck of a different user on the same computer. 

Common for all wrong listings are the match result: "undefined:0" instead of the usual 1:0 or 0:1

The tracker was NOT active during those games. In fact, it wasnt even installed yet.

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. Please, add a screenshot of your problem.

**Comment by Razviar** [comment]
Should be fixed in v.1.7.8, please update.
