### ISSUE TITLE
Android App Cards List Error

### ISSUE THREAD

**Issue by bipolarmorgan** [Razviar/mtga-pro-tracker#397]
**ERROR IN ANDROID APPLICATION**
While attempting to view cards within a deck, error appears instead - saying 

> NoSuchMethodError: The method 'where' was called on null. 
> Receiver: null
> Tried calling: where()

**To Reproduce**
Go to decks, click on a specific deck and it loads the Cards tab with error.

**Expected behavior**
Show me the cards in the deck.

**Screenshots**
![Screenshot_20190422-194722](https://user-images.githubusercontent.com/49892530/56551614-b1171080-653d-11e9-9f65-ad1a4c157792.jpg)

**Comment by Aquaman88** [comment]
Thank you! We will investigate your issue.

**Comment by Aquaman88** [comment]
Right now everything should work correctly.

**Comment by bipolarmorgan** [comment]
> Right now everything should work correctly.

Still not working, same issue... please re-open and fix.

**Comment by Razviar** [comment]
We will investigate it further

**Comment by Razviar** [comment]
Updated app is pushed to the Play Market.
