### ISSUE TITLE
Deck Sync Still Fucked

### ISSUE THREAD

**Issue by tarantula2107** [Razviar/mtga-pro-tracker#399]
As of three days ago, Aquaman said this issue this issues was fixed. However, it's not because, as seen in the screens attached, I'm still having the issue, even after multiple full and soft resets.
![MTGA decks](https://user-images.githubusercontent.com/40201918/56775839-f5e9b400-6796-11e9-8b9e-12c28967ac5a.png)
![Site decks](https://user-images.githubusercontent.com/40201918/56775840-f5e9b400-6796-11e9-91ac-0a29e6aea55c.png)

**Comment by Aquaman88** [comment]
Hi! What do you mean? You can remove your decks from site by yourself. As for the new decks, all of them should be automatically added into site.

**Comment by tarantula2107** [comment]
Before the breakdown, all of my decks were showing up correctly. The breakdown cost me Angelic Strength (down for possible rename), Bio Angels, Bio Domri, Domri's Party, and Up the Creek. After the double-patch today, I was able to add a brand new brew in Vraska's Army (not pictured above). But, it's still not importing/collecting the other four decks it ate when it flopped. For the record, Ral Memekin is an evolution of the pre-breakdown Memekin deck.

**Comment by Razviar** [comment]
Just rename and save old deck. But you need to rename not in deck overview, and open missing deck for edition. Open deck in mtga - rename - save - rename back. It'll appear. It's very old issue, and I'm still have no idea how to fix it, so sorry about that, but that's the only way.

**Comment by tarantula2107** [comment]
Ended up deleting/recreating my account. Will update this post after work tomorrow.
