### ISSUE TITLE
In Deck Builder, removed cards from deck do not appear in card searches

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#4]
If the quantity of a card in the deck is reduced to 0, but the user has done quick searches by card name before doing that, doing consecutive quick searches the card will NOT appear in them anymore, until the page is refreshed.

**Comment by Razviar** [comment]
Patch applied, needs testing.

**Comment by Razviar** [comment]
Fixed. Now for real :)

**Comment by apoapostolov** [comment]
Reopen, not fixed

**Comment by Razviar** [comment]
Check again please

**Comment by apoapostolov** [comment]
Okay new issues:

This is how a Green Stompy looks when loaded fresh to edit

![image](https://user-images.githubusercontent.com/4083812/47000280-9b5d0480-d130-11e8-9336-4be54110828e.png)

A search for "ghalta" (a card already included in the deck) shows totally different card - It's not the fast typing query problem stucking a "gha" because I was able to replicate this 3 different times

![image](https://user-images.githubusercontent.com/4083812/47000321-b29bf200-d130-11e8-991a-eb4ca7f28261.png)

Removing all ghaltas, searching again, now the card is there

![image](https://user-images.githubusercontent.com/4083812/47000416-e6771780-d130-11e8-9b1d-16d799ba84d9.png)

Not just Ghalta issue - this is issue with every card included in the deck, and I think there's a rogue filtering (maybe related to the initial filtering to mosrly included cards, etc. as that filtering no longer appears later if you clear the query). Here's example of searching for Vivien Reid while Vivien is included - and it is not found in search

![image](https://user-images.githubusercontent.com/4083812/47000585-41107380-d131-11e8-94c6-7b3b17a7e58a.png)

**Comment by apoapostolov** [comment]
Finally fixed, confirmed.
