### ISSUE TITLE
PC App In Game Overlay error

### ISSUE THREAD

**Issue by bipolarmorgan** [Razviar/mtga-pro-tracker#400]
**Describe the bug**
Overlay isn't working properly. It displays my deck names, some incorrectly, and then during the matches it improperly shows what cards are played on the opponent and doesn't show my deck list on my turn.... please advise.

**To Reproduce**
Use in game overlay

**Expected behavior**
For it to work properly...

**Comment by Aquaman88** [comment]
Hi! Thank you for your report! Please, update the tracker, turn-off and turn onn an overlay. Everything is working correctly. You can also pick the option to turn-off or turn-onn the automatical changing your and your opponents decks during the matches.
