### ISSUE TITLE
Tracker seems to think my account doesn't exist/I'm missing something.

### ISSUE THREAD

**Issue by jfclavette** [Razviar/mtga-pro-tracker#401]
![image](https://user-images.githubusercontent.com/2823653/56783172-2e8d8b80-679f-11e9-94bc-229f4a7bf7da.png)

**Comment by jfclavette** [comment]
No space or weird things in the text box.  Username is blacked out for privacy but matches.

**Comment by Aquaman88** [comment]
Hi! Did you try to copy your token from site and add into tracker?

**Comment by kenibrewer** [comment]
@jfclavette Your token is not the same thing as your full username with the numbers. You can find your token at this site if you are logged in. https://mtgarena.pro/mtga-pro-tracker/

Look at this screenshot to see where you can find it. The token is 8 characters long and should consist solely of numbers and the letters "a" through "f".

![mtgarenaprotoken](https://user-images.githubusercontent.com/17461269/56801191-da0ffd80-67ea-11e9-8453-f1f861d772ec.png)
