### ISSUE TITLE
Collection progress graph incorrectly calculating

### ISSUE THREAD

**Issue by matthompson** [Razviar/mtga-pro-tracker#405]
**Describe the bug**
After the release of War of the Spark, the collection graph jumped from 39.8% total collected down to 2.4%. This different than higher up on the page where it calculates my new total collection at 34% complete.

To be clear, I am expecting a drop at that date since new cards were added, but the graph appears to be miscalculating in some fashion now. A screenshot has been attached.

![mtg pro tracker bug](https://user-images.githubusercontent.com/22378368/56867884-3a549a00-69b9-11e9-89a7-d0713d9a928c.png)

**Comment by georgesdimitrov** [comment]
I have the same issue. After updating the tracker today, the percentages are now back at their normal value, but I still have that ugly notch down on April 25th:

[img]https://i.imgur.com/1pqNPch.png[/img]

Is there any way to remove this? I've tried a full reset, but it didn't change anything. Seems it permanently wrote a 0% in my account. The collection progress is one of the main reasons I use the tracker, and looking at how the graph progresses... It's really annoying in its current state now.

Thanks!

**Comment by Aquaman88** [comment]
Hi! Thank you for your report. We have already investigated this phenomenon. Now everything works correctly and the information in graphics and in statistic fields is the same. Unfortunately we cannot fix the falling in graphics on the 25th of April right now.

**Comment by georgesdimitrov** [comment]
Thank you. Does this mean it will be possible to fix this "falling" in a near future?

**Comment by Razviar** [comment]
Unfortunately at this point it's really hard to manually edit stored history data, so I wouldn't promise to remove this issue in nearest future.
