### ISSUE TITLE
bug access other deck list

### ISSUE THREAD

**Issue by SebaFR7474** [Razviar/mtga-pro-tracker#406]
Hi, i trying to access the page https://mtgarena.pro/decks/?MagicArenaFR but i have the windows 
RETRY, STOP, RELOAD PAGE .

**Comment by Aquaman88** [comment]
Hi! This functional works correctly (try one of my links mtga.cc/decks/?Aquaman88 ) . So the problem is because of incorrect name or because of hidden decks.

**Comment by SebaFR7474** [comment]
hi, yes with your link idont have any error but the list is empty.

**Comment by Aquaman88** [comment]
It is because there were no decks in this list)

**Comment by SebaFR7474** [comment]
Oki, so if they have deck hide we can't access their deck? Because they put
their url on their YouTube video to show their decks

**Comment by Razviar** [comment]
There's no user named "MagicArenaFR" in our database, that is why you can't see the decks. 
Owner of the account should use account settings page and set Nickname to "MagicArenaFR" and then from /u/ page make sure that decks sharing is active in settings.
