### ISSUE TITLE
cant open the file / installer 

### ISSUE THREAD

**Issue by must0341** [Razviar/mtga-pro-tracker#408]
cant open the installer it cant finde the right souce
![Udklip](https://user-images.githubusercontent.com/50184022/57044226-28e5e900-6c6a-11e9-9be3-dda2da7f6215.PNG)

**Comment by must0341** [comment]
![Udklip](https://user-images.githubusercontent.com/50184022/57044283-634f8600-6c6a-11e9-985d-090c62355f54.PNG)
 from here i cant get the installer to work but cant finde the right files

**Comment by Aquaman88** [comment]
Hi! Thank you for your message! After downloading the .zip file , you can find the programm for installation in directory: mtga-pro-tracker-master ---mtgapro---mtgapro.installer.

**Comment by must0341** [comment]
![Udklip](https://user-images.githubusercontent.com/50184022/57060928-6de63b80-6cbb-11e9-86b5-deb527dcec52.PNG)

**Comment by must0341** [comment]
in the file you say the installer cannot read as exe but it became a readable file

**Comment by Aquaman88** [comment]
It is a local problem. Maybe one of the programs in your computer blocks the setupping process
