### ISSUE TITLE
"Not Enough Data" 

### ISSUE THREAD

**Issue by jpcguy89** [Razviar/mtga-pro-tracker#409]
My opponents "seen cards" have not been populating. It says "Not Enough Data" on the app, and on the site under Matches List just shows their name instead of the cards in their deck. I've tried Manual Re-Sync, Scan Old Logs, Full Reset. Nothing works.

**Comment by Aquaman88** [comment]
Thank you for your message. Please, add the screenshot of your problem and we will investigare it

**Comment by jpcguy89** [comment]
https://imgur.com/a/Kaw72nT Pics of the issue.

**Comment by Aquaman88** [comment]
Okay, we will investigate your issue

**Comment by uzimith** [comment]
<img width="1171" alt="Screen Shot 2019-05-31 at 10 56 40" src="https://user-images.githubusercontent.com/365836/58676320-ced46280-8392-11e9-87ea-2ad286beb6d5.png">

I started to use this awesome application from yesterday. Thank you.

 I guess I'm in the similar situation. It could log opponent cards only in Play mode. There are no cards in Ladder mode.

**Comment by Razviar** [comment]
Issue should be fixed now
