### ISSUE TITLE
Incorrect "Boosters needed" count

### ISSUE THREAD

**Issue by combataran** [Razviar/mtga-pro-tracker#410]
It's telling me that an Esper Control list missing 11 rare wildcards only needs 7 more boosters than a White Weenie list missing 4 rare wildcards. That's not counting the sideboard cards in the Esper list which was apparently ignored.

![image](https://user-images.githubusercontent.com/2815112/57266233-ba5fbb80-70ad-11e9-886b-6e83cb680f98.png)

**Comment by combataran** [comment]
Here's the full Esper list

![image](https://user-images.githubusercontent.com/2815112/57266336-14f91780-70ae-11e9-8288-4475841454bb.png)

**Comment by combataran** [comment]
Weenie list

![image](https://user-images.githubusercontent.com/2815112/57266354-26422400-70ae-11e9-857b-5780bab654f8.png)

**Comment by Aquaman88** [comment]
Thank you for your message. We will investigate your issue.

**Comment by Aquaman88** [comment]
Hi! I have already investigated your issue. So, what do we have? For Esper list you need 8+22+4=34 different wildcards. They include wildcards that you have in collection and wildcards that you do not have ( you do not have 13 wildcards in screenshot  - 11+2). In deck screenshot you can see, that you need 34 cards without sideboard. So everything shows correctly.
