### ISSUE TITLE
Links on website do not seem to work

### ISSUE THREAD

**Issue by StormStrikeHP** [Razviar/mtga-pro-tracker#411]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by StormStrikeHP** [comment]
On the website, on a decklisting, "export deck" and other links do not work. Seems to be endless loop or something? Go to: https://mtgarena.pro/decks/lvd-big-pig-2/   Click "Export Deck". On both Firefox and Edge website does nothing.

**Comment by nsmvjher** [comment]
i also can not "export deck" in website may be i log in as facebook first then , i used email log in again.
Help me!!!!!

**Comment by Aquaman88** [comment]
Please, tell me if everything is ok. We`ve already fixed the situation with exporting.

**Comment by Razviar** [comment]
Bug is currently fixed. If you still have it, please clean the cache and try to re-login.
