### ISSUE TITLE
can not "export deck" "sample hand" on website

### ISSUE THREAD

**Issue by nsmvjher** [Razviar/mtga-pro-tracker#413]
**Describe the bug**
can not export deck on website

**To Reproduce**
1. Go to https://mtgarena.pro/decks/.
2.Select crafta list.
3.Select a deck .
4.select "export deck"
The "selected deck" "sample hand" can not be kick and does not response 

**Expected behavior**
i hope after i "export deck" i can export the deck and review the sample hand by kicking "sample hand
![can not export](https://user-images.githubusercontent.com/50652497/57754210-7b221200-7720-11e9-8fb5-521ac42b2d47.JPG)
" 

**Screenshots**
Below
**Additional context**
when i registered with facebook account first, then i using email log in and try my password by the email.

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. To export your deck, you should turn buttom Export Deck. Then you can see the code for exporting ( all of cards) and you should turn buttom copy output. In game you can import this code. Here is the screen : https://imgur.com/jGFRH76

**Comment by Razviar** [comment]
Fixed.

**Comment by nsmvjher** [comment]
i do not know why . now i can press the "export deck" and it works. at that time . it didn't show any things.
