### ISSUE TITLE
Sorting by Need Not Working on AutoMETA

### ISSUE THREAD

**Issue by Reithan** [Razviar/mtga-pro-tracker#415]
**Describe the bug**
If you sort by Need column on AutoMETA, it doesn't sort.

**To Reproduce**
1. Go to AutoMETA
2. Click on 'Need'
3. Scroll down to 'Anything'
4. See error - It's not sorted

**Expected behavior**
I expect it to sort.

![image](https://user-images.githubusercontent.com/7475701/57974746-1827b980-7972-11e9-80d5-5de4ffb316a0.png)

**Comment by Aquaman88** [comment]
Thank you! we will investigate this phenomenon

**Comment by Aquaman88** [comment]
Hi! So, It is not a bug, it is a feature. It seems, that auto meta will be changed every week.

**Comment by Reithan** [comment]
Even with autometa changing frequently, why is not being able to sort by Need a feature?

**Comment by Aquaman88** [comment]
This filter works , but not in auto meta. It is a feature. For example you can filter decks by Need in featured decks.

**Comment by Reithan** [comment]
I know the filtering is a feature, but the fact that it doesn't work in Autometa isn't a feature. I don't understand how that filter not working in that mode isn't a bug?

**Comment by Razviar** [comment]
It's not a big because auto meta renders decks in specific order (in order of, basically, meta importance). If you sort decks differently, you'll get not meta, but just featured decks. That is why there's no point in this sorting

**Comment by Reithan** [comment]
I didn't realize that. Maybe there could be a tooltip or something explaining it?
What does "meta importance" mean though? 🤔
