### ISSUE TITLE
"Can't parse date from log!" bug

### ISSUE THREAD

**Issue by gerrardgit** [Razviar/mtga-pro-tracker#416]
I didn't play MTGA for a few weeks but yesterday I updated it played and now the MTG Arena Pro Tracker is giving me this bug, a pop up saying "Can't parse date from log!" and telling me to contact the admin@mtgarena.pro mail adress. I tried mailing this to the address but the mailed couldn't be delivered.

Things I did to try to fix this:
- Doing a full reset of MTG Arena Pro Tracker
- Reinstalling MTG Arena Pro Tracker
- Deleting the output_log.txt file in AppData\LocalLow\Wizards Of The Coast\MTGA
- Reinstalling MTGA (thinking that there had been some problems with the most recent update)

But nothing worked. The error keeps happening and my data isn't being uploaded.

Things that may have had something to do with this:
- I use the tracker mostly after play sessions to upload what I did (but I don't have it open mid play).
- The last thing I did in the game was to play one of the new momir games for art styles and in the middle of the game there was a message about the system going down for maintenence (I still finished the game though). After that I opened the tracker and that's when I saw the bug.
- Also, since the problem seems to be related to the date, I'm from Argentina (we use the format DD/MM/YYYY, timezone GMT -3 and speak Spanish), but I have everything in English (the game and the tracker) since I prefer that for MTG.
- Looking at the code (although I'm not very used to this specific programming language) it seems that the error comes from looking at lines with "UnityCrossThreadLogger" in them and parsing the date. I have a few lines with that line but without date, such as:
- [UnityCrossThreadLogger]FrontDoorConnection.Close(reason = "Initial reset, whatever that means")
- The lines with that text that do have date are:
- [UnityCrossThreadLogger]25/5/2019 9:07:34 a. m.

I wanted to know if there was something I could do to fix this error and keep using your tracker.

I attach my log file for further analysis (i just replaced my nick and my ID with some strings): 
[output_log_EDITED.txt](https://github.com/Razviar/mtga-pro-tracker/files/3219373/output_log_EDITED.txt)

Thank you!

**Comment by Razviar** [comment]
v.1.6.7 fixing this issue have been released

**Comment by gerrardgit** [comment]
It works now, thank you!
