### ISSUE TITLE
My profile page or tracker broken

### ISSUE THREAD

**Issue by rolandkopka** [Razviar/mtga-pro-tracker#419]
**Describe the bug**
May 27-28 missing. 29 appearing twice.
Tracker was running on the missing dates.

**To Reproduce**
Open https://mtgarena.pro/u/KOB/ and check the dates.

**Comment by Aquaman88** [comment]
Hi! Please, add a screenshot of your problem here

**Comment by rolandkopka** [comment]
![2019-06-01 (4)](https://user-images.githubusercontent.com/7033460/58743529-7b662100-8433-11e9-81b4-be6a0c6a57bd.png)
![2019-06-01 (5)](https://user-images.githubusercontent.com/7033460/58743532-7e611180-8433-11e9-8b9b-2fdf5601c5ba.png)

**Comment by Razviar** [comment]
Issue with double posts id fixed now.
