### ISSUE TITLE
Recent tracking data not showing on Profile

### ISSUE THREAD

**Issue by corwinburdick** [Razviar/mtga-pro-tracker#423]
**Describe the bug**
The last several days of tracking data don't show up on my profile. This affects the day summaries on my profile. The number of `undefined` increases by one each day that is not tracked correctly

**To Reproduce**
1. Go to https://mtgarena.pro/u/Gorno/ and look at the data above May 31 (I played on both 6/1 and 6/2)

**Screenshots**
https://i.imgur.com/omWffSc.png

**Comment by Razviar** [comment]
We are investigating the issue

**Comment by Razviar** [comment]
Bug with social page is fixed. But we miss your data from June 1st and 2nd. You should use "Full Reset" button in your tracker to resume normal data uploads.
