### ISSUE TITLE
Rewards populated with month and day swapped

### ISSUE THREAD

**Issue by floodbars** [Razviar/mtga-pro-tracker#425]
**Describe the bug**
After updating to (v1.7.1), I opened a new booster pack and found that the rewards were indexed under 2019-04-06 rather than 2019-06-04 (assuming ISO 8601 conventions)-which was noticeable only because I started on May 10.

I don't know if this is a bug in MTGA Pro Tracker nor am I familiar enough with the log format to say if the format was changed.

**To Reproduce**
Steps to reproduce the behavior (at least retrieving the results since I don't have the gold to buy more boosters at this current time):
1. Go to 'mtgarena.pro/progress/#{username}'
2. Observe that a datapoint exists on April 6

**Expected behavior**
I expected the booster to be indexed under the correct date.

**Screenshots**
![mtg-arena-pro](https://user-images.githubusercontent.com/22568059/58927598-109f3900-8704-11e9-9412-c224466ace5e.gif)

**Additional context**
* The rewards from yesterday were correctly uploaded to 2019-06-03.
* I updated the Tracker while I had MTGA open (but I don't recall if I opened the booster before or after I updated nor do I recall what version I had previously installed).

**Comment by lemabr01** [comment]
This might also be related to https://github.com/Razviar/mtga-pro-tracker/issues/421 as I *do* see stats getting uploaded but they're put on April 6th instead of June 4th.  See below screenshot.

I started playing in late May.
![Untitled](https://user-images.githubusercontent.com/25397001/58928300-e9eefb80-871f-11e9-9d3f-383c2bb18a23.png)

**Comment by Razviar** [comment]
This regression is fixed, new records will have correct date/time. No tracker update needed. Old ones unfortunately will remain as is.
