### ISSUE TITLE
"Edit description" no longer works

### ISSUE THREAD

**Issue by WhiteSp1rit** [Razviar/mtga-pro-tracker#427]
**Describe the bug**
Button "Edit Description" in the deckbuilder on mtgarena.pro site no longer works. Clicking on it does nothing.

**To Reproduce**
In the deckbuilder, click "Edit Description"

**Expected behavior**
Switch to a description editing page

**Additional context**
Tried it in Firefox and Vivaldi (Chromium-based), doesn't work in both

**Comment by Razviar** [comment]
Bug fixed. Try ctrl+f5
