### ISSUE TITLE
Decks not in My Decks

### ISSUE THREAD

**Issue by Rigsnpigs** [Razviar/mtga-pro-tracker#429]
My decks that I've logged games into aren't appearing under the My Decks tab

![mgtapro decklist](https://user-images.githubusercontent.com/51432022/59006758-410cd300-87e9-11e9-81cf-4c62404843d0.png)

![Deck Lists](https://user-images.githubusercontent.com/51432022/59006759-4407c380-87e9-11e9-8427-77f95543ac57.png)

![MGtapro matchlist](https://user-images.githubusercontent.com/51432022/59006765-4833e100-87e9-11e9-8c58-b4fe4e4329ce.png)

You can see that I have these decks in my collection in arena, and MGTAPro is tracking my games with them, but not putting this info in "My Decks"

I don't know if this is because I've made these decks recently, but around that same time I deleted a bunch of decks. But all the decks I had in Arena used to be listed here.

**Comment by Rigsnpigs** [comment]
I've tried Re-Syncing and doing a full reset.

**Comment by Razviar** [comment]
You have "WAR" time filter active (right to the deck name and "standard", in the upper menu row).
Switch it to "All time" and you'll see all decks you have.
