### ISSUE TITLE
Progress page looks broken

### ISSUE THREAD

**Issue by updradedsam3000** [Razviar/mtga-pro-tracker#430]
Since last night my progress page is broken. It appears that for some reason data was recorded as happening in the 1900s and my progress page looks broken because of it. [Here are some images.](https://imgur.com/a/DsVOSWQ)

**Comment by uzimith** [comment]
My account's progress page is the same.
I tried Account wipe, but there are no effect.

**Comment by Aquaman88** [comment]
thank you, we will investigate this issue

**Comment by Razviar** [comment]
Wrong data is removed from DB. You need to check your date format settings in tracker app (go to settings / date format and read manual there)
