### ISSUE TITLE
remove basic lands from expansion counter

### ISSUE THREAD

**Issue by WEBhicham** [Razviar/mtga-pro-tracker#431]
**Is your feature request related to a problem? Please describe.**
when checking how many cards a deck has on a expansion the counter would b wrong because it also counts the expansion of the basic lands. this isn't actual interesting because every one has the basic lands by default. 
**Describe the solution you'd like**
having the counter not count the basic lands in the expansion counter.
**Describe alternatives you've considered**
being able to choose which cards to count in the expansion counter. 
**Additional context**
The counter I am talking about 😂 
![image](https://user-images.githubusercontent.com/27362642/59032091-b918de80-8865-11e9-888d-d1ca3892c73a.png)

**Comment by Razviar** [comment]
It's implemented, but will affect only the new decks. Old ones will not be recalculated and stats will remain the same unless the author will make changes there.

**Comment by Razviar** [comment]
Addendum: now it's implemented even with old decks.
