### ISSUE TITLE
Log Upload Still Not Working + Entering Date & Time Issues

### ISSUE THREAD

**Issue by khazidroid** [Razviar/mtga-pro-tracker#432]
I am still having issues with the log upload, just played a bunch of games and none of them were uploaded.

My profile page does not show any new cards earned or a synopsis of games played on June 8.

I am located in Sydney, Australia [GMT+10]

Attempting to set the date format also fails as soon as I try to enter the time format.

Sample date and time from log is : 8/06/2019 6:39:11 PM

Actual time for me right now is 18:39:11 on June 8.

So day/month/year + hour (12 hour clock):minute:second AM/PM

As per the instructions I enter d/MM/yyyy as the date format, no issues so far ...

however when I try to then enter the time format as h:mm:ss as soon as I type the first character - h - I get the ERROR! Check your template message. I tried other hour formats with the same result. Seems I cannot enter my date/time format at all.

I am not sure if I need to enter a date format or not, as the instructions seem to imply that a date/time format is only needed for non-standard date/time formats.

I did get some matches uploaded in the early hours of 8 June without having set a date/time format in the settings menu, however the Progress/Constructed Rankings data showed my latest batch of games as Aug 6 and not June 8. Also the Vault Progress time scale stretched out to August.

Do I need to enter a date format at all, if so could you advise which one ?

Output log is attached.
[output_log.zip](https://github.com/Razviar/mtga-pro-tracker/files/3268375/output_log.zip)

**Comment by Razviar** [comment]
Please provide a screenshot of your settings page open on date format tab. I will see a sample of date format and will provide correct template.

**Comment by Razviar** [comment]
Let's take sample date format from your log: 8/06/2019 6:05:26 PM
String for date formatting is: d/MM/yyyy h:mm:ss tt
Just ignore ERROR and keep typing it until it gets changed to confirmation message. You can copy string right from this message.

**Comment by khazidroid** [comment]
Razviar - thanks for the response and feedback, my date format is now correctly set, and uploads look to be reporting correct dates, progress vault, gold, gems & cards etc.

Apologies but it wasn't obvious to me that the tt filter also needed to be present for en-US date/time formats. Now I know :)

Please close this issue, thanks.

**Comment by Razviar** [comment]
Glad it worked out, and I'll update the manual
