### ISSUE TITLE
Cannot parse old logs with different date format

### ISSUE THREAD

**Issue by AnnanFay** [Razviar/mtga-pro-tracker#433]
It's impossible to parse old logs which have a different date format to the current log.

1. Click "Scan old logs..."
2. Error "Set date format in settings!"
3. Set date in settings
4. Tracker restarts after saving settings
5. Tracker automatically sets date to current log format
6. Return to 1.

I _assume_ this is what is happening. Maybe step 3. is just failing causing the tracker to crash which returns the date format to the previous value?

Either way, something is causing the tracker to restart and prevents me from parsing the old log file.

**Comment by Razviar** [comment]
Unfortunately, this won't be fixed. Logs with obsolete date formats are not supported. We are thinking to get rid of old log scanning at all, because it never works stable and only cause troubles
