### ISSUE TITLE
Feed shows incorrect numbers for a card gained from boosters

### ISSUE THREAD

**Issue by riQQ** [Razviar/mtga-pro-tracker#434]
**Describe the bug**
See screenshot.

**To Reproduce**
I don't know how to reproduce

**Expected behavior**
In reality I only have 2 Ajanis. So it should show 1/2 instead of 3/2

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/3404787/59229483-d1c52380-8bda-11e9-8c2e-8c9b485e82d5.png)

**Comment by Aquaman88** [comment]
Thank you! We will check your issue

**Comment by rolandkopka** [comment]
Same issue here.

To Reproduce:

- Play some games and earn cards without running the tracker
- Close the MTGA client
- Run the tracker
- When it finished, my profile shows the correct numbers
- Close the tracker
- Open the tracker again and let it finish reading the logs
- All the numbers doubled up

The numbers in parentheses are correct but the numbers before them are not.

**Comment by Razviar** [comment]
fixed in v.1.7.8, old records will remain as is.
