### ISSUE TITLE
Profile lists all cards ever earned or crafted

### ISSUE THREAD

**Issue by cheqq2** [Razviar/mtga-pro-tracker#436]
**Describe the bug**
"My Profile" page will show every card ever earned or crafted.

**To Reproduce**

1. Login to MTGA with Pro Tracker running.
2. Craft a card or two and/or open a booster and/or earn a card as a reward.
3. Log out of MTGA, go to "My Profile" page with Pro Tracker.

**Expected behavior**
My Profile page should only list cards earned/crafted that day. Instead it lists pretty much every card ever crafted/earned/etc. instead. 

**Screenshots**
If applicable, add screenshots to help 
![image](https://user-images.githubusercontent.com/51725380/59312459-35069280-8c7b-11e9-8056-0cf8269a5bce.png)

**Additional context**
This has happened to me twice recently. Each time it happened seemed to be shortly after my girlfriend played on my computer using her account-- she logs in to MTGA with her ID but doesn't shut down Pro Tracker first. Not sure why that would mess things up but just an FYI.

**Comment by Aquaman88** [comment]
Thank you! We will investigate your issue

**Comment by Razviar** [comment]
Multiple account support is unfortunately very problematic. We are working on it

**Comment by Razviar** [comment]
v.1.7.8 should be able to address this issue.
