### ISSUE TITLE
Vault Progress page uses time in x axis instead of date

### ISSUE THREAD

**Issue by mmkayPL** [Razviar/mtga-pro-tracker#438]
**Describe the bug**
Vault progress page on https://mtgarena.pro/progress/ shows incorrect tooltip when hovering over the graph

**To Reproduce**
1. Go to My Arena -> Progress -> Vault Progress
2. Hover over any area in the graph
3. Tooltip shows time (e.g. 11:00) (possibly time of log creation/upload)

**Expected behavior**
Graph should show date in the tooltip like in other graphs on the site

**Screenshots**
![mtgproarena](https://user-images.githubusercontent.com/11991443/59786205-02861680-92c7-11e9-8e4a-09462d0512a1.png)

**Additional context**

**Comment by Razviar** [comment]
Fixed, try ctrl+f5 on that page
