### ISSUE TITLE
Deck Organization

### ISSUE THREAD

**Issue by arasimus** [Razviar/mtga-pro-tracker#440]
It has become apparent to me, in constructing decks and playing with different ideas, that it would be very useful to many people to be able to create categories or 'folders' of decks to organize them. Having to scroll through a ton of decks to find the one you are looking for can get quite annoying. Or maybe, if you are like me, you get annoyed with having so many decks, you find yourself having to delete decks you just made for an event, like Pauper, Counters, etc.  I would prefer to save those decks to play with in the future, but I just have to delete them to keep my deck management more simple.  But if I could have them separated into categories, which I could define myself, it would be a huge quality of life improvement for the experience of the game.

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. You can try to use filters to find decks

**Comment by arasimus** [comment]
That's a small part of what I am talking about, but does nothing for being able to sort out decks by type, theme, etc. Having customizable organization to clean up your deck list at the top would be a huge improvement.

**Comment by Razviar** [comment]
We are considering different approaches to better decks organization. Most likely it will be something like user defined tags, working as quasi folders. But for now we don't have strict ETA of this feature
