### ISSUE TITLE
Direct Challenge card pool (build deck) is not loading

### ISSUE THREAD

**Issue by tomguta** [Razviar/mtga-pro-tracker#442]
Hi,

when I try to build a deck for a direct challenge event, the cards start loading, then they all disappear and a spin dial is displayed instead. It stays there and nothing happens then.

E.g.
https://mtgarena.pro/deckbuilder/?Magesa&pool-1561404265

Note - changing collection to My Collection and back helps a bit, but the cards disappear again after several seconds (and the spin dial is then shown again).

This completely breaks the Direct Challenge feature as it prevents me from building a deck.
![image](https://user-images.githubusercontent.com/1763443/60046939-d56fa480-96c8-11e9-9836-4d08a4d8733a.png)

**Comment by Razviar** [comment]
Thanks for report, we'll investigate this

**Comment by Razviar** [comment]
It's fixed, try ctrl+f5

**Comment by tomguta** [comment]
This is partially fixed, see #445
