### ISSUE TITLE
Editing a direct challenge adds RIX to the editions pool - can't be removed.

### ISSUE THREAD

**Issue by tomguta** [Razviar/mtga-pro-tracker#444]
**Describe the bug**
Editing (or somehow modifying) a Direct challenge event randomly adds RIX edition.

**To Reproduce**
1. Create new direct challenge with WAR, RNA, GRN
2. Save, Edit (or so)
3. Observe that RIX is added
4. Try to remove it by pressing the "X" on "RIX" button, edition selector is displayed:

**Expected behavior**
1. RIX is not added
2. RIX is removable.

**Screenshots**
![image](https://user-images.githubusercontent.com/1763443/60134039-e854a880-979e-11e9-90f6-e73bb7adcc03.png)
-> Clickng the X on RIX button causes this:
![image](https://user-images.githubusercontent.com/1763443/60134094-09b59480-979f-11e9-8923-c47351658cce.png)

**Comment by Aquaman88** [comment]
Thank you for your issue. We will investigate it

**Comment by Razviar** [comment]
Bug fixed.
