### ISSUE TITLE
Filtering dirrect challenge pool freezes on spin dial

### ISSUE THREAD

**Issue by tomguta** [Razviar/mtga-pro-tracker#445]
**To Reproduce**
1. Go to https://mtgarena.pro/deckbuilder/?Magesa&pool-1561404265
2. Try filtering by various colours
3. Filtering by Multicoulour shows the spin dial 

**Expected behavior**
Filtering works as expected (no freezes).

**Screenshots**

![image](https://user-images.githubusercontent.com/1763443/60134496-e3dcbf80-979f-11e9-8650-c50c5d4f8f49.png)

**Comment by Aquaman88** [comment]
Hi! Thank you for your issue. I tried to check it and i did not have problem like yours. Can you check it again?

**Comment by Razviar** [comment]
Bug confirmed and already fixed. Thanks.
