### ISSUE TITLE
No more tracking since June 21. 

### ISSUE THREAD

**Issue by StefanKoenigMUC** [Razviar/mtga-pro-tracker#446]
Dear all,

sinice June 21. there is no more tracking for my Account (TRO#05189)

Could you assist me? :-)

Thanks for your great work!

Regards,

**Comment by Razviar** [comment]
Have you updated to v 1.7.9?
Try reinstall, manual reset button in the app, set date format in the app settings

**Comment by StefanKoenigMUC** [comment]
Date Format was missing, thanks a lot!
