### ISSUE TITLE
Editing deck description doesn't work

### ISSUE THREAD

**Issue by WhiteSp1rit** [Razviar/mtga-pro-tracker#447]
**Describe the bug**
After editing the deck description the first time, it stops working.
When you go to edit the deck description, the popup that has deck description editing field either closes itself after about 1 second, or it opens with the field in a non-editable state, so that you couldn't change any text in it.

**To Reproduce**
1. Click "Edit description", change description, click "Ok"
2. Click "Edit description"

**Comment by Razviar** [comment]
Bug confirmed, working on fix

**Comment by Razviar** [comment]
Fixed
