### ISSUE TITLE
Two Isssues

### ISSUE THREAD

**Issue by stormcat664** [Razviar/mtga-pro-tracker#448]
**Describe the bug**
Daily match results are no longer reflected in my profile since 6/20.
And Pro.Tracker started to do strange recordings.
Please refer to Screenshot.
![capture_001_28062019_062923](https://user-images.githubusercontent.com/52299273/60302386-c578ee80-996e-11e9-9ed9-aca128d62c3c.jpg)

**To Reproduce**
Nothing special.

**Comment by Razviar** [comment]
Can you give a link to your profile?
Also, do you have tracker updated to latest version?

**Comment by Grabbl** [comment]
I see the same issues, 2:2-recordings when a match ended 2:1 and the weird "Was first"-Icon. 

Here's my profile: https://mtgarena.pro/u/Mianthril

**Comment by Razviar** [comment]
I see it's connected to bo3 issue, we will investigate

**Comment by Razviar** [comment]
Update: patch for incorrect matches scores applied, checking if it's consistently fixed.
Missing icons are fixed.

**Comment by Razviar** [comment]
I can see from the database that issue is resolved.
