### ISSUE TITLE
Missing Cards on Deck Converter

### ISSUE THREAD

**Issue by CrookedBuckeye** [Razviar/mtga-pro-tracker#449]
**Describe the bug**
When using the deck converter feature, cards that have an apostrophe in their name are not converted and left out of the converted decklist. Mox Amber also has this issue.

**To Reproduce**
1. Go to Deck Converter
2. Paste in a Decklist containing a card with an apostrophe (e.g., Chemister's Insight or Legion's Landing)
3. Save Deck and Check in Deckbuilder or Check the Converted Decklist on the right

**Comment by Razviar** [comment]
Bug confirmed, working on fix

**Comment by Razviar** [comment]
Fixed, thanks for reporting!
