### ISSUE TITLE
Devil token from Tibalt plainswalker not showing the art in latest update 

### ISSUE THREAD

**Issue by Lostsorrow** [Razviar/mtga-pro-tracker#452]
Devil token from Tibalt plainswalker not showing the art in latest update

![B68E0AD1-1D12-446C-B0EF-5F0A190E6165](https://user-images.githubusercontent.com/52535115/60666647-88f93700-9e35-11e9-8bbd-aa474c432f67.jpeg)

**Comment by Aquaman88** [comment]
It is a game phenomenon, so we can not fix that
