### ISSUE TITLE
Matchup matrix mirror match winrate

### ISSUE THREAD

**Issue by jbarthelmes** [Razviar/mtga-pro-tracker#453]
On the [Matchups page](https://mtgarena.pro/meta-matchups/) the winrate of all mirror matches should be 50%.

**Comment by Aquaman88** [comment]
Thak you for your message. Make sence. But there are some factors in MTGA matchmaking. First of all, you can use different decks with the same archetypes (especially it is about different cards, that have their winrates) That is why Winrate is near 50% ( 49,94 etc)
