### ISSUE TITLE
"Ads help us run this site" appearing at every click

### ISSUE THREAD

**Issue by RageOfAchilles** [Razviar/mtga-pro-tracker#454]
I'm a fan of your tracker and been using it every single day but since yesterday, every time I click anything or open any page I keep getting the popup reminder "Ads help us run this site" and I have to accept every single time, it's a nightmare and it's making it impossible to use the tracker anymore! Please fix this mess!

**Comment by Aquaman88** [comment]
Hi! Thank you for your feedback!
Ads are being disabled permanently and for good after you make $10 donation just once as a patron. After that you can reduce amount or unsubscribe at all, but you still can enjoy your ad-free site.If you do not want to be a patron, you can just use AdBlock. Thank you for your understanding
