### ISSUE TITLE
Feature Request: Spectate on games

### ISSUE THREAD

**Issue by Reitohl** [Razviar/mtga-pro-tracker#455]
**Is your feature request related to a problem? Please describe.**

Some times I want to watch players work away, at high levels too to give me deck ideas in many areas

**Describe the solution you'd like**

being able to watch players play the various modes and various ranks of the ranked mode.

**Describe alternatives you've considered**

Youtube I guess? Not really considered an alternative, I just thought this wouldn't be too hard to implement 

**Additional context**

This would make Tournaments and such events more like your own gran prix events with spectators able to enjoy the highly impressive matches that're held. Seems a waste for such skill to be held in such isolation. I hope you consider this Thank you.

**Comment by Aquaman88** [comment]
Hi! We hope, that the spectator mode will be revealed in game in nearest future. Unfortunately now players even have some inconvenience when they need to play direct challenges. On our site we have the utilite that calls "Direct limited" (https://mtgarena.pro/direct-limited/). It is the first step from us to make MTGA tournaments for everyone who wants to play or organize them.

**Comment by Reitohl** [comment]
Ah cool, I'm glad that it's on your radar. I personally would look forwards to watching people play, especially at high levels of ranked mode or the gem event modes! Thanks for the expedient reply, best of luck with the title :)
