### ISSUE TITLE
My collection wont import

### ISSUE THREAD

**Issue by zephes95** [Razviar/mtga-pro-tracker#456]
My collection wont import

I installed the tracker and copied my code, it is awaiting for updates and wont finish. 
my collection in the page is empty

**Comment by Aquaman88** [comment]
Hi!Please, update your tracker to latest version. After tracking matches during first day, all unformation about your collection, decks and progress will be on site.

**Comment by Razviar** [comment]
Also you should check if your date format in settings set up correctly.

**Comment by zephes95** [comment]
![Untitled](https://user-images.githubusercontent.com/52645848/60831687-8463b400-a190-11e9-902f-46ba4e8de837.png)
what am i doing wrong?

**Comment by Razviar** [comment]
d/M/yyyy h:mn:as tt

**Comment by zephes95** [comment]
problem solved thx!
