### ISSUE TITLE
Editing deck description is not working

### ISSUE THREAD

**Issue by WhiteSp1rit** [Razviar/mtga-pro-tracker#457]
**Describe the bug**
The field where you supposed to write the deck description is not editable, can't write anything in it

**To Reproduce**
1. Go to deck page
2. Click "Edit"
3. Click "Edit Description"
4. try to write something in the deck description field

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. This functional works correctly. You can edit description of your decks if you logged in on site. Please, try to use another browser and check the functional again.
