### ISSUE TITLE
Collection manager by date reports 4 cards, I only have 2 in collection

### ISSUE THREAD

**Issue by kevinhisel** [Razviar/mtga-pro-tracker#458]
**Description:**
I'm currently reviewing the cards I gained by specific date. In this view it shows that I have 4 Herald of the Sun; however, when I smart search for the same card it shows that I only have 2.

**To Reproduce**
I am unsure of how to reproduce the bug in other accounts; however, on my account:

1. Go to Collection Manager
2. Click for More Filters
3. Click on History Filter
4. Click on July 7, 2019
   - From here you will be able to see Herald of the Sun marked as having 4 copies. I believe this should only list the number of copies I received that day.

1. Go to Collection Manager
2. Click on Smart Search
3. Type Herald of the Sun
   - From here you will be able to see Herald of the Sun marked as having 2 copies. This should list all copies in my collection.
   - I have verified in Magic Arena that I only have 2 Herald of the Sun.

**Expected Behavior**
2 Herald of the Sun should be shown when using History Filter for July 7, 2019.

**Screenshots**

![image](https://user-images.githubusercontent.com/18108628/61187358-245c8a00-a636-11e9-8e11-bd6313592b91.png)

![image](https://user-images.githubusercontent.com/18108628/61187403-5a017300-a636-11e9-951e-6bdd67eadee8.png)

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. Please, try to check the information again. I have checked Herald of the Sun in game and on the site and my investigation said, that the information is the same - 4 copies.
