### ISSUE TITLE
Rotation indicator

### ISSUE THREAD

**Issue by heho** [Razviar/mtga-pro-tracker#459]
As the first rotation is coming up quite soon it would be really helpful to have some kind of rotation indicator, so that you dont invest in cards you are not able to play afterwards.

I think a good way of doing this would be adding a highlight to the expansion bars and adding a statistics like highlighting feature to them. 

another solution would be to add a set symbol (and coloring it) to the cards in the deck view, but I think this might just clutter things. 

A third solution would be putting an exclamation next to the cards, but I think this would be somewhat confusing for users not knowing about that feature.

**Comment by Aquaman88** [comment]
Thank you for your suggestion. We are waiting for the rotation and we will do all our best for our users to have as much information as possible and the way to get it.

**Comment by Razviar** [comment]
We will roll out something by the end of this month.

**Comment by Razviar** [comment]
Implemented: https://twitter.com/mtgapro/status/1152534990779047937
