### ISSUE TITLE
Account wipe doesn't work

### ISSUE THREAD

**Issue by soleera** [Razviar/mtga-pro-tracker#461]
**Describe the bug**
The account wipe feature doesn't delete any of the selected data from your account.

**To Reproduce**
1. Log in and go to My Arena > Account Wipe
2. Click on any of the toggles under "Select the data to wipe:"
3. Click on "Proceed with wipe"
4. Check that account data still exists (e.g. My Arena > Collection)

**Expected behavior**
The relevant account data should be deleted after following this process.

**Comment by Razviar** [comment]
Can you give a link to your account?

**Comment by soleera** [comment]
Sure, it's https://mtgarena.pro/u/soleera

**Comment by Razviar** [comment]
You can try again now, patch applied

**Comment by soleera** [comment]
Looks like everything is working as intended now :)
