### ISSUE TITLE
Changed log format with today's patch

### ISSUE THREAD

**Issue by mlacs** [Razviar/mtga-pro-tracker#463]
After updating today the tracker is broken. Keeps complaining about incorrect date format, even though it says 'Date format is correctly set' under the Date Format tab

**Comment by mlacs** [comment]
Links to news: https://forums.mtgarena.com/forums/threads/58440
New log format: https://magic.wizards.com/sites/mtg/files/output_log_arena.txt

**Comment by Razviar** [comment]
Update will be rolled out till the end of the day 26th Jul

**Comment by pquinn** [comment]
also if you're paranoid about losing data: it's possible (i think, may be wrong) to save your log files to some other location (it looks like the MTGA client resets it every time you launch the client so make sure you get em after a session) and manually re-upload them using the "Scan Old Logs..." functionality but i'll defer to the maintainer

**Comment by dysonlol** [comment]
> 
> 
> Update will be rolled out till the end of the day 26th Jul

comes the update automaticly when i start the prog ?

**Comment by Razviar** [comment]
Update is ready: https://github.com/Razviar/mtga-pro-tracker/releases/tag/1.8.0

**Comment by Souldrinker** [comment]
The 1.8.0 update seems to have fixed the date issue with 1.7.9 and the latest mtga update, but it seems I no longer get the information about what cards I get in the booster packs in the profile now.

I got one booster before the 1.8.0 update when running the game without this tracker running and after upgrading the tracker the match result (2:0 wins) and the progress section was updated (including percentage increase of each color and the vault), but I got no "booster" section in the profile.

Now after playing another match with the tracker running it's still the same. The match result and progress were updated, but the cards from the two boosters I got doesn't show up in the profile.

**Comment by Razviar** [comment]
It's regressions connected with numerous log format changes. It will take some time to track all that down and fix.

**Comment by Razviar** [comment]
Numerous regressions handled properly:
https://github.com/Razviar/mtga-pro-tracker/releases/tag/1.8.1

**Comment by MaXimillionZero** [comment]
Here's the log file from issue #469 https://puu.sh/DYjz8/b81fe600c8.rar

**Comment by Razviar** [comment]
@MaXimillionZero thanks! We'll investigate it and let you know about the updates

**Comment by Razviar** [comment]
Update 1.8.2 should address the issue with "still asking for date input"

**Comment by Kirsan13** [comment]
Problem is still here.
![76](https://user-images.githubusercontent.com/53311511/62012868-47d61780-b194-11e9-8705-3522a3edd5ce.JPG)

**Comment by Razviar** [comment]
With v.1.8.3 this issue is considered to be resolved. Let me know if something comes up.
