### ISSUE TITLE
Possible way to resolve date/time parsing issues

### ISSUE THREAD

**Issue by mikiurban** [Razviar/mtga-pro-tracker#464]
**Note: this message is for the developer, not the end user, to avoid users entering date time strings ***

When I had to parse international date/times, it was very hard but I solved it like this:

1) Create a DateTime object of January 2nd, 2003 17:18:19
   var d = new DateTime(2003, 2, 1, 17, 18, 19);
2) Convert to local format string
   var s = d.ToString();
3) Replace "1" with "M", "2" with "d", "2003" with "yyyy" and "03" with "yy", "17" with "HH", "5" with "H", etc.
4) Replace "CultureInfo.CurrentCulture.DateTimeFormat.AMDesignator" with "tt"
5) Replace "CultureInfo.CurrentCulture.DateTimeFormat.PMDesignator" with "tt"
6) Parse
  DateTime parsedTime = DateTime.parse(originalDate, s, CultureInfo.CurrentCulture);

It is not exact, it has been a few years, but this should work.  Another option is to use different replacement values and Regex:
* Replace "1" with "(?\<month>\d+)", "2" with "(?\<day>\d+)", "2003" with "(?\<year>\d+)" etc
* Replace AM and PM Designators with (?\<am>.\*) and (?\<pm>.\*)
* Parse code is:  
   var r = new Regex(s);
   if (r.IsMatch(logFileLine)) {
      var match = r.Match(logFileLine);
      int year = match["year"];
      etc
   }

**Comment by dysonlol** [comment]
hey, for me it sounds like japanese... what i want is a simple tool to track my W/L in mtgarena. i dont wanna learn a programmer language or something like this.
i am from germany ( TT.MM.JJJJ SS:MM.ss ) 
i dont know if is right... do you have an idea what i have to do ? 
can you tell me how i update the tool ? 
my next step is to try an other tool...

**Comment by mikiurban** [comment]
> hey, for me it sounds like japanese... what i want is a simple tool to track my W/L in mtgarena. i dont wanna learn a programmer language or something like this.
> i am from germany ( TT.MM.JJJJ SS:MM.ss )
> i dont know if is right... do you have an idea what i have to do ?
> can you tell me how i update the tool ?
> my next step is to try an other tool...

Sorry, I did not mean for normal users to perform these steps, this is something the author has to do.

**Comment by dysonlol** [comment]
> 
> 
> > hey, for me it sounds like japanese... what i want is a simple tool to track my W/L in mtgarena. i dont wanna learn a programmer language or something like this.
> > i am from germany ( TT.MM.JJJJ SS:MM.ss )
> > i dont know if is right... do you have an idea what i have to do ?
> > can you tell me how i update the tool ?
> > my next step is to try an other tool...
> 
> Sorry, I did not mean for normal users to perform these steps, this is something the author has to do.

sure, my fault. sorry :)

**Comment by mikiurban** [comment]
> > > hey, for me it sounds like japanese... what i want is a simple tool to track my W/L in mtgarena. i dont wanna learn a programmer language or something like this.
> > > i am from germany ( TT.MM.JJJJ SS:MM.ss )
> > > i dont know if is right... do you have an idea what i have to do ?
> > > can you tell me how i update the tool ?
> > > my next step is to try an other tool...
> > 
> > 
> > Sorry, I did not mean for normal users to perform these steps, this is something the author has to do.
> 
> sure, my fault. sorry :)

That's OK, I wasn't specific when I originally posted this, no big deal :)

**Comment by Razviar** [comment]
Update is here: https://github.com/Razviar/mtga-pro-tracker/releases/tag/1.8.0

**Comment by mikrobestie** [comment]
@Razviar Thanks for the update, but for me it does not work. In main panel there is a message "Set date format in settings" and in the settings - "Date format" tab there are various errors like
`NULL entity on { "id": 2019, "affectorId... `
can't see the whole error message, is there any log?

**Comment by Razviar** [comment]
@mikrobestie try "full reset" button, might help. If not, I'll ask you to send me the log

**Comment by Razviar** [comment]
Merged with https://github.com/Razviar/mtga-pro-tracker/issues/463
