### ISSUE TITLE
1.8.0 release doesn't work on 32-bit Windows

### ISSUE THREAD

**Issue by frei-0xff** [Razviar/mtga-pro-tracker#465]
**Describe the bug**
After update to version 1.8.0 program doesn't work on Windows 10 32-bit

**To Reproduce**
Install 1.8.0 version on 32-bit Windows

**Comment by Razviar** [comment]
Today we'll add x86 version installer

**Comment by Razviar** [comment]
Grab it here: https://github.com/Razviar/mtga-pro-tracker/releases/tag/1.8.1
