### ISSUE TITLE
Try DateTime.Parse before requiring user input

### ISSUE THREAD

**Issue by jeohist** [Razviar/mtga-pro-tracker#466]
I think a lot of users would appreciate it if the application tried to automatically parse the DateTime output from MTGA before requiring user input. Most of the outputs I've generated seem to be standard formats which it recognises. 

Really sympathize with the tracker devs on tackling this issue, this is probably one of the worst ways WotC could've implemented timestamps in logging...

**Comment by Razviar** [comment]
It actually is trying to parse the most frequently used formats, and asks user to input format only if none of known formats worked.

The latest issues were connected not with date format itself, but with global log format change.
