### ISSUE TITLE
1.8.0 Error reading log (1140)

### ISSUE THREAD

**Issue by zobi** [Razviar/mtga-pro-tracker#467]
With the last version of tracker : 1.8.0 

When i try to resync the tracker i have an error message : "Error reading log! (1140)"

i don't know where to find better log ... 

thanks a lot

**Comment by Razviar** [comment]
We are working on fix

**Comment by Razviar** [comment]
Fix is here: https://github.com/Razviar/mtga-pro-tracker/releases/tag/1.8.1

**Comment by zobi** [comment]
Nice job ! it works nice 
Thanks a lot for your help
