### ISSUE TITLE
Invalid date format sample 

### ISSUE THREAD

**Issue by wintersteiger** [Razviar/mtga-pro-tracker#468]
After two updates today, the tracker still gets invalid samples for the date format string:
![image](https://user-images.githubusercontent.com/10155819/61995890-ec1d6880-b085-11e9-84c7-62d099cf4e85.png)

Not sure which of my logs triggers that, but here's one of them to look at:
[UTC_Log - 7-20-2019 3.19.36 PM - 1.zip](https://github.com/Razviar/mtga-pro-tracker/files/3438274/UTC_Log.-.7-20-2019.3.19.36.PM.-.1.zip)

In general: surely the date format can be inferred automatically. Not sure why this is being pushed on to the user who often doesn't even know where to find the logs and how to read them. Also, MTGA probably uses whatever the system date format is and the system is happy to provide that information...

**Comment by Aquaman88** [comment]
Hi! The correct data format should be d/M/yyyy h:mm:ss tt

**Comment by wintersteiger** [comment]
Thanks @Aquaman88, but he month definitely comes first in all of my logs. Either way, it doesn't work with either of our settings, and it still shows me an invalid sample. After re-opening the Settings dialog lots of times, it did show me a valid sample (but still didn't accept my or your settings). After re-opening the Settings dialog again, it then gave me an error message sample:
![image](https://user-images.githubusercontent.com/10155819/61997076-03fbe900-b094-11e9-8ad3-0cb7a7a719d3.png)

**Comment by Aquaman88** [comment]
Please, try to turn Full reset and try again

**Comment by Razviar** [comment]
Merging with this issue: https://github.com/Razviar/mtga-pro-tracker/issues/463

**Comment by Razviar** [comment]
We are trying to detect the most common date formats, and ask user for input only if auto detection fails. Current issues are related to log format changes with latest game update.
