### ISSUE TITLE
Program doesn't accept date format

### ISSUE THREAD

**Issue by MaXimillionZero** [Razviar/mtga-pro-tracker#469]
![](https://puu.sh/DY3mu/3a665d210d.png)

Hitting save settings refreshes the window but it complains about incorrect date format again. As far as I can tell everything should be set correctly. Is the lack of AM/PM indicator the issue?

**Comment by Razviar** [comment]
Please try to use full reset and try again afterwards.

**Comment by MaXimillionZero** [comment]
Tried full reset twice, same end result every time.

**Comment by Razviar** [comment]
Can you send me your have log from appdata folder? You can zip it and upload to some cloud

**Comment by Razviar** [comment]
Merging with this issue: https://github.com/Razviar/mtga-pro-tracker/issues/463
