### ISSUE TITLE
Uploads succeed but aren't reflected in profile

### ISSUE THREAD

**Issue by claviger** [Razviar/mtga-pro-tracker#471]
The tracker successfully uploads all of my matches, and if I go to the Matches screen I see them.  However, other data -- like my Profile, win/loss record, etc. -- does not reflect any of these matches.

My profile is https://mtgarena.pro/u/Vylanis

Here's an example.  I have matches practically every day of the last month:

![Untitled](https://user-images.githubusercontent.com/7929944/61998700-a30aeb80-b068-11e9-82f1-f82ffa7deaab.png)

Yet my profile only shows anything for three days this month (7/7, 7/9, 7/23.)  The past few months are the same way -- hundreds of matches on the Matches screen, only 2-3 days updated in my Profile.

![Untitled2](https://user-images.githubusercontent.com/7929944/61998706-cb92e580-b068-11e9-9abf-eb3da5570696.png)

This issue has been persistent for me for at least three months.  I'm using the current tracker (1.8.1) and have tried uploading matches from two different computers, with the same effect.

**Comment by Aquaman88** [comment]
Hi! Thank you for your issue. We will investigate it

**Comment by Razviar** [comment]
Daily post is generated only if someone (you or your followers) access /u/ page. You can request regeneration of daily posts using "regenerate feed" button below your avatar
