### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by cc92000** [Razviar/mtga-pro-tracker#474]
hi. 
i have a problem : i tried to create an account on mtgarena.pro website, and it doesn't works. 
it seems it memorized my email adress. but i don't receive nothing in that adress email, neither a new password.
i don't understand, i'm sure i respected all the process... 
can you help me please ?

**Comment by cc92000** [comment]
to complete my previous message...

i already complete my profil.

when i want to login i fill the login field and the password field, and i've got this error message : 
"ERROR: The password you entered is incorrect. Lost your password?"
(but for sure it's the true password, and the only one it can be).

and when i click on "Lost your password?", i've got this error message :
"ERROR: There was an error while trying to send the activation link to ...@yahoo.fr!"

and when i want to register with my email adress (...@yahoo.fr) i've got this error message :
"This email is already in use."

i tried everything. for sure : i don't know what to do... 

can you help me, please ?

thank you

**Comment by Aquaman88** [comment]
Hi! You can try to use another social logins like facebook, google or twitch to login.

**Comment by cc92000** [comment]
hi. 
thanks for your answer.
i saw that, but i don't have a lot of social account, and i don't want them linked to MTGArena.PRO.
i want MTGArena.PRO linked with email adress.
i don't understande this bug, cause it seems i made everything well...
thanks for your help

**Comment by Aquaman88** [comment]
We will investigate the situation with resetting password. You can try to use another social login before we find the solution.

**Comment by cc92000** [comment]
i tried to login with my twitch account.
but when i done it MTGArena.PRO didn't found my email adress and asked me to write it. 
i done it.
and it answered me : "This email is already used by another account"...
what can i do ?
(thanks for your answer and help...)

**Comment by Aquaman88** [comment]
You have only one account and it doesn't matter what kind of login you use

**Comment by cc92000** [comment]
ok. so it might works.
but i can't login to MTGArena.PRO.
clicking directly on "login" on the website : it doesn't work.
trying to login via twitch : it doesn't work.
i don't know what to do.

can you reinitialized my account ?
i don't know what to do...

**Comment by Aquaman88** [comment]
Please, try again to recover your pass again. Here is the link https://mtgarena.pro/recover-password/

**Comment by Razviar** [comment]
Send me your full email address to admin@mtgarena.pro
I will reset your account and you will be able to register anew.

**Comment by cc92000** [comment]
thank you Aquaman88 for your help and your time.
but your link is the same i got before. and for sure i get the sema error message : "This email is already used by another account"...

**Comment by Razviar** [comment]
Resolved
