### ISSUE TITLE
Application No Longer Accepts Valid Date Template

### ISSUE THREAD

**Issue by Tokuhisa1** [Razviar/mtga-pro-tracker#475]
Since late this morning, the Pro Tracker has rejected valid date format settings, accordingly, changes to my game state are not being reflected/recorded. No matter what inputs I give in the value in the "Format" field, the application persistently responds "ERROR! Check your template". In in an effort to rectify this undesired behavior, thus far I have tried closing and re-opening the application multiple times, as well as restarting my machine and Magic: the Gathering Arena with no success.

![Capture](https://user-images.githubusercontent.com/5890853/62417163-1a1b2380-b617-11e9-81a8-8c85ccb2cedf.PNG)

![Capture2](https://user-images.githubusercontent.com/5890853/62417166-2ef7b700-b617-11e9-9ef5-f5ad4dbfe54f.PNG)

**Comment by Aquaman88** [comment]
Hi! After last update problems with data settings were fixed. Please, turn button Full Reset in your tracker, input your token again and it should get date format automatically.

**Comment by Tokuhisa1** [comment]
It worked, thank you! (This is the type of info that should be on the website as part of an FAQ.)
