### ISSUE TITLE
the tracker don´t work

### ISSUE THREAD

**Issue by Jebrahe** [Razviar/mtga-pro-tracker#476]
Hello, I hope someone can help me, for some reason the program no longer sends information to the page and no data is updated, can someone help me?

The last day it worked and I have some record was July 30

**Comment by Aquaman88** [comment]
Hi! Please, check the latest update. The version of tracker should be 1.83. Also you can use full reset button, input your token again and start tracking.

**Comment by Jebrahe** [comment]
It is something quite strange what happens, it does not register absolutely anything apart from the rank, I have already tried everything else, some bug?

**Comment by Aquaman88** [comment]
So, do you still have problems? Please, add screenshots that will image your issue (especially important screenshot of your open tracker)

**Comment by Jebrahe** [comment]
![screen](https://user-images.githubusercontent.com/53353171/62428409-38405c80-b6c7-11e9-9436-b503fcd44bb4.jpg)

**Comment by Jebrahe** [comment]
since jul 30, noting its updated

**Comment by Jebrahe** [comment]
but all its runing

**Comment by Aquaman88** [comment]
Thank you for your screen. Did you try full reset button? When you did that, what happened?

**Comment by Razviar** [comment]
Also you might need to set up date format in app settings, because your date format seems to be non-standard.

**Comment by Jebrahe** [comment]
well with the full reset nothing happens, just enter the token again and do not register anything, although with date format I have not tried anything

**Comment by Jebrahe** [comment]
although previously I did not make any movement and it worked correctly

**Comment by Jebrahe** [comment]
although previously I did not make any movement and it worked correctly

**Comment by Aquaman88** [comment]
So, you can try to set up data settings byself.  In tracker settings you should choose Data Format and according to instruction (https://mtgarena.pro/date-setting-manual/) add correct date settings byself.

**Comment by Jebrahe** [comment]
Bingo, thx
