### ISSUE TITLE
"Set date format in settings!" bug

### ISSUE THREAD

**Issue by macsmith26** [Razviar/mtga-pro-tracker#477]
Upon loading the app, the status displace a red circle with title. I go into settings and all fields are blank with a tutorial on formatting. Never encountered this before with this app and it's no longer keeping statistics current on app/website. Can we have default date format settings, or auto detect as a fix?

**Comment by Aquaman88** [comment]
Hi! Please, check the latest update. The version of tracker should be 1.83. Also you can use full reset button, input your token again and start tracking.
