### ISSUE TITLE
Tracker showing my cards from a deck I played HOURS ago and doesn't update to current deck

### ISSUE THREAD

**Issue by SoilnRock** [Razviar/mtga-pro-tracker#478]
The tracker keeps showing cards from a deck I played hours ago and doesn't update to show the cards of the currently played deck. I uninstalled and installed 5+ times already, cleaned the registry, did a full reset 5+ times and STILL it's showing trhe cards from the wrng deck - which I even deleted and is nonexistant anymore.
I have no clue what is happening and how to fix this.
I'm running the current version.

**Comment by Aquaman88** [comment]
Hi! We had the issue like that before, but the conclusion was that it was a local bug. First of all, in tracker settings you should turn on and then turn off buttons "Auto-Switch between me and opponent" and "Show declists between battles" and play more games without concede with this four different settings.  Then you can tell us about the result. I have just checked on my account, for me everything works correctly

**Comment by SoilnRock** [comment]
Many thanks for your very quick response! I woke up today and without doing anything, it suddenly worked again. Unfortunately after having done an account wipe on the web page almost all my decks are gone except for a few. Is there a way to manually sync all my decks in the game with the decks shown on the webpage?

**Comment by SoilnRock** [comment]
Unfortunately the tracker started to show the wrong cards/deck again :-( There is no way for me to reconstruct the problems, at the moment, the tracker is totally unreliable/unusable for me :-(

**Comment by Aquaman88** [comment]
You can try to delete some decks manually on site and in game and then continue tracking during 24 hours.

**Comment by SoilnRock** [comment]
Thx for your response, I do appreciate. Sorry for the harsh words, but the tracker is practically unusable (for me): it doesn't update after cards being changed in a deck, shows wrong mana costs for some cards, even mixes my cards with the opponent's cards.
My decks don't get uploaded to the site even after 24+ hours.
I really like your site but the tracker app is a mess. :-(

**Comment by Aquaman88** [comment]
It is just a local problems, because tracker and overlay works correctly. The version of tracker should be 1.83. Please, use full reset button, input your token again and it should get date format automatically. If you have problems with data settings, you should add correct data settings byself according to instruction (https://mtgarena.pro/date-setting-manual/).

**Comment by SoilnRock** [comment]
As I already wrote before, I did multiple full resets, fresh installations and reentering tokens and/or date settings. I also wrote that I am indeed running the latest version and still I'm not getting a working tracker but instead repeatedly messages of apparently incorrect date settings although they are clearly entered correctly. It's a shame.

**Comment by SoilnRock** [comment]
So now you start deleting my comments?! So much for transparency - and so much for the tracker. I'm out. Shame on you.
