### ISSUE TITLE
Boosters tracker limited to show only 30 numbers per day

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#48]
Boosters tracker limited to show only 30 numbers per day

Also, when you click on "Date Range From" or "Date Range To" and choose some day, for every click there new strings are added:

Share your progress stats using this link: (click to copy)

Share your progress stats using this link: (click to copy)

Share your progress stats using this link: (click to copy)

**Comment by Razviar** [comment]
Fixed.
