### ISSUE TITLE
600+ Windows notification in seconds "Unable to parse logs" after opening an older client version

### ISSUE THREAD

**Issue by arktouros** [Razviar/mtga-pro-tracker#484]
**Describe the bug**
After opening an older version of the client (2-3 months old)
it produced more than 600 windows notifications because it could not read the date 
on the logs

**Comment by Razviar** [comment]
This is known issue, which will be addressed in the next release

**Comment by Razviar** [comment]
Just released 1.8.4 fixes this issue
