### ISSUE TITLE
Number of already owned cards is not shown in social feed

### ISSUE THREAD

**Issue by riQQ** [Razviar/mtga-pro-tracker#485]
**Describe the bug**
The number of already owned cards is not shown in the social feed

**To Reproduce**
1. Go to the social feed
2. See error

**Expected behavior**
The number of already owned card is shown in the social feed.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3404787/62839328-07dd5d00-bc89-11e9-95f7-ce8b119db48e.png)

**Comment by Razviar** [comment]
Please provide a link to your account so we could investigate the issue

**Comment by Wishbringer** [comment]
I'm having the same issue, my account is Wishbringer#28016 since the 12'th of august.

**Comment by Razviar** [comment]
Issue is confirmed to be global, we are investigating it now

**Comment by Razviar** [comment]
Bug is fixed, new posts will be correctly generated. Also you can regeneragte old ones using REGENERATE button under your avatar.
