### ISSUE TITLE
Progress show date of Dec 18, 2019

### ISSUE THREAD

**Issue by NaiDoX** [Razviar/mtga-pro-tracker#486]
**Describe the bug**
On the progression page there is an data on Dec 18th, 2019. My Link is NaiDoX's Progress
mtga.cc/progress/#NaiDoX

**Expected behavior**
The data on progress should be only until Today date

**Screenshots**
![image](https://user-images.githubusercontent.com/54059563/62926836-8815d680-bddf-11e9-9da3-f3658d4d341b.png)

**Comment by Razviar** [comment]
It's fixed now, thanks for reporting.

**Comment by NaiDoX** [comment]
Thanks a lot
