### ISSUE TITLE
Profile information missing

### ISSUE THREAD

**Issue by residualfail** [Razviar/mtga-pro-tracker#487]
**Describe the bug**
I'm missing random updates to my profile from decks, deck names, cards changes, and match histories.

**To Reproduce**
1. I'm unable to reproduce on demand.  The information that's missing is just random to me.

**Expected behavior**

**Screenshots**
This shows I'm missing my "Token Singleton" deck which was made on 8/12.  I also circled 3 decks that have been changed but aren't updated in my profile.  The monoblue deck should be called "Terrible Control", the "WB LifeDmg?" deck was deleted, and the monowhite deck was renamed to "Bad Lifegain".
![image](https://user-images.githubusercontent.com/7663668/62983266-c372ce00-bdfc-11e9-9436-c0a18b0cf304.png)

I should have 6 matches yesterday with the "Token Singleton" deck which is also missing from the "My Decks" view.  I'm missing my first win of those matches.
![image](https://user-images.githubusercontent.com/7663668/62983374-1b113980-bdfd-11e9-9728-5bfd60027ce0.png)

**Additional context**
https://mtgarena.pro/u/residualfail

**Comment by Razviar** [comment]
We know about those random discrepancies, but those are very hard to track and debug, because they are literally impossible to reproduce. We are working on better tracking mechanism to be introduced in future, but with current system some errors and discrepancies will remain.
