### ISSUE TITLE
Booster-icons on Events-page doesn't render

### ISSUE THREAD

**Issue by Ezelmannen** [Razviar/mtga-pro-tracker#490]
**Describe the bug**
Booster-icons on Events-page doesn't render

**To Reproduce**
1. Go to https://mtgarena.pro/events/#[playername]

**Expected behavior**
Icons for booster packs should render. They are 'broken links'.
If one follows the link the page says the server is down for maintenance.
But most other things on the server seems to be working fine.

**Screenshots**
![2019-08-18-mtgarenaprobugCapture](https://user-images.githubusercontent.com/28021692/63224175-bcfba200-c1c0-11e9-908e-506b30b5fd5c.PNG)

**Comment by Lucille654** [comment]
Thanks for reporting, we will fix it.

**Comment by Razviar** [comment]
Fixed.
