### ISSUE TITLE
I can't seem to access my booster advisor page

### ISSUE THREAD

**Issue by tieyourshoelaces** [Razviar/mtga-pro-tracker#493]
mtga.cc/crafter/#TYSL

That is the link to my booster advisor page, I added a new deck to the crafting list and now the page is stuck at showing me the loading animation.

I have tried it in firefox and edge, with and without adblockers, in a private window with all the addons disabled.

**Comment by Razviar** [comment]
We are working on it, hold on

**Comment by Razviar** [comment]
Fixed, use ctrl+f5 for update.
