### ISSUE TITLE
MTGAPro.exe not launching

### ISSUE THREAD

**Issue by Maxtille** [Razviar/mtga-pro-tracker#494]
Hello there,
I'm running on windows 7 Familial Edition Premium SP1,
It's the first time I try pro tracker and so I still don't have any account. I have installed v1.8.4 and v1.8.3 but both aren't able to start, and administrator rights won't help.
Strangely when I try to launch the app the "little dots" separator just on the right of the start button  disappears for a few instants, and process in task manager seems to auto stop synchronously ...
Any idea ?

**Comment by Razviar** [comment]
This means app crashes on startup. You might need to update .net to 4.6.2. If it's not .net, it might be connectivity problem, which we are currently working on.

**Comment by Maxtille** [comment]
Nice ! Problem solved ! :smiley_cat:
