### ISSUE TITLE
No sample date from log, can't set the date correctly

### ISSUE THREAD

**Issue by necromanek** [Razviar/mtga-pro-tracker#496]
Hello,

after today's MTGarena update I'm not able to set the correct date anymore. I tried possibly everything, I opened the log itself to see the date format there but I always get an error message, no matter what I try to write. The date is ok but when I try to write hours:mins:secs, error appears. Where could be the problem? I spent like an hour setting date and time, and I'm stuck. And, no sample date from log appears in the Settings as it should. Thanks!

**Comment by Wishbringer** [comment]
MTGA devs decided to turn off detailed logging, so unless they revert that change sadly nothing can be done. ;(

**Comment by justinfyffe** [comment]
You can enable detailed logging in your Account Settings in the game. Works for me.

**Comment by Wishbringer** [comment]
Oh really, thanks for the info @justinfyffe .

**Comment by Razviar** [comment]
We are investigating log changes right now.

**Comment by Razviar** [comment]
Also, I would ask anyone who has similar problems to get the log from AppData\LocalLow\Wizards Of The Coast\MTGA and send it over to me using any cloud service.

**Comment by paqua2** [comment]
Hello,

I have a similar problem. Link to my log file:
https://www.dropbox.com/s/sg1yxjbktsc4b0u/output_log.txt?dl=0

**Comment by Wishbringer** [comment]
Enabling the detailed logging in account settings (from within the game) fixed the problem for me.
Its off by default, so everyone need to do this with the new version.

**Comment by Maxtille** [comment]
I don't find where can I set this in game :/ 
I also will send you my logs fies ;)

**Comment by Maxtille** [comment]
Ok just found it you just need to click on view account all in the bottomwhen you're in settings :smiley:

**Comment by Maxtille** [comment]
Just to signify that for me after changing settings for logs file, it appears the new logs files have a new date format with different separator than before, that's why I had to change date format settings in the tracker in addition to enabling the logs files in game :wink:

**Comment by NaiDoX** [comment]
Hi, Even after enabling the detailed log I still can not find the date/time sample. please help.

**Comment by necromanek** [comment]
I enabled detailed log, set the correct date but I can't see today's games on my MTGArena.PRO account. All seems to be working in Tracker. Any idea please?

**Comment by yads** [comment]
I'm trying to manually set the date format based on one of the new log files `M/d/yyyy h:mm:ss tt`. And it says `ERROR! Check your template`. My guess is that it's not pointing at the correct logs. Which logs is it parsing? The output_log file that's under Users\AppData or the Logs folder in the installation folder (mine is in E:\Wizards of the Coast\MTGA\MTGA_Data\Logs\Logs)

**Comment by Razviar** [comment]
V.1.8.5. released, please try it out. If you are still in trouble, use Full Reset button! If it didn't help, **get the log from AppData\LocalLow\Wizards Of The Coast\MTGA and send it over to me using any cloud service.**

**Comment by yads** [comment]
1.8.5 seems to be working now! Thanks @Razviar

**Comment by Razviar** [comment]
Resolved with 1.8.6
