### ISSUE TITLE
error MTGA not installed

### ISSUE THREAD

**Issue by f-andrey** [Razviar/mtga-pro-tracker#498]
**Describe the bug**
after 31 Aug, 2019 (or first days september), tracker not work correct "MTGA not installed!"

**To Reproduce**
1. wine (32bit) for FreeBSD : )
2. MTGA installed in msi https://mtgarena.downloads.wizards.com/Live/Windows32/versions/1684.728405/MTGAInstaller_0.1.1684.728405.msi https://forums.mtgarena.com/forums/threads/58489 (or any prewious september version)
3. run it

**Screenshots**
![image](https://user-images.githubusercontent.com/10493955/64884175-b2baaf80-d669-11e9-994b-ceb3676c94f7.png)

**Comment by Razviar** [comment]
Locate log file manually in app settings.

**Comment by f-andrey** [comment]
Thanks and truth indicating the way solved the problem, as I did not guess to check
