### ISSUE TITLE
MTG Arena and books

### ISSUE THREAD

**Issue by iPadMTG** [Razviar/mtga-pro-tracker#500]
Possible suggestion for MTG Arena

If there was a possibility to integrate the MTG novels into MTG Arena, it might be a way for people to start investing their time and money into the books too.

One chapter for free.
Earn additional chapters through play or purchase.
Possibly someone reading the book and MTG Arena shows images of what's going on.
Just a thought from someone who enjoys the stories and game-play.

Ken B.

**Comment by Razviar** [comment]
Sorry, this is MTG pro tracker git, not the game itself. We are 3rd party developers
