### ISSUE TITLE
Split Cards from GRN & RNA no longer show up in the collection

### ISSUE THREAD

**Issue by lanfill** [Razviar/mtga-pro-tracker#504]
**Describe the bug**
Split cards no longer show up as "in your collection"

**To Reproduce**
1. Go to https://mtgarena.pro/collection/
3. Scroll down to `Depose // Deploy`
4. See error:
![Screen Shot 2019-09-24 at 12 17 52 PM](https://user-images.githubusercontent.com/635297/65534681-90286200-dec5-11e9-9527-1b90e54e4a83.png)

**Expected behavior**
I have these cards in MTG Arena, they should show up in my collection

**Comment by Razviar** [comment]
This bug is fixed, collection will get updated as soon as you get any new card. Alternatively you can try "Manual Reset" button in tracker.
