### ISSUE TITLE
Incorrect display of the deck on the site

### ISSUE THREAD

**Issue by TheoDormant** [Razviar/mtga-pro-tracker#506]
Something goes wrong on site with my deck   https://mtgarena.pro/decks/stand2020-bl-white

**To Reproduce**

1. Go to https://mtgarena.pro/decks/stand2020-bl-white
2. See empty screen

**Comment by Razviar** [comment]
Bug confirmed, we are working on this

**Comment by Razviar** [comment]
Deck is rendering now, but with some bugs. Will continue later...

**Comment by TheoDormant** [comment]
Hi, Razviar!
My deck is renamed to "New_vampires_2020". 
Though it's still broken because this deck has two different addresses https://mtgarena.pro/decks/new-vampires-2020-29407/ and https://mtgarena.pro/decks/new-vampires-2020-4c94c/ which depend on a way of opening the deck's page

Many thanks for great site & software!

**Comment by Razviar** [comment]
Should be fixed now
