### ISSUE TITLE
Split cards in deck list shown as not collected, while they are.

### ISSUE THREAD

**Issue by Lumeni77** [Razviar/mtga-pro-tracker#508]
**Describe the bug**

**To Reproduce**
If you go to deck list. My decks or even other people decks. It shows you the missing cards you do not have in your collection.
However I do have the cards in my collection. After checking multieple decks and multiple cards shown as missing I noticed all the incorrect missing cards are split cards.

**Expected behavior**
Cards should not show as not in collection if they are in the collection. Probably has to do with the naming of split cards.

**Screenshots**

**Additional context**

**Comment by Razviar** [comment]
This issue is fixed, collection will update as long as you get at lest 1 new card
