### ISSUE TITLE
https://mtgarena.pro/decks/ not loading

### ISSUE THREAD

**Issue by Augmented35** [Razviar/mtga-pro-tracker#509]
After logging in to the website the page https://mtgarena.pro/decks/ displays as a white blank page.
![chrome error](https://user-images.githubusercontent.com/55924420/65819766-c5fc7c00-e220-11e9-81d3-dbeecafd65bc.PNG)

I am logging in via google account login feature.
 This error persists on Chrome, Firefox and Edge.
Full clear of C&C was done.

**Comment by Razviar** [comment]
Thanks for reporting, it's fixed
