### ISSUE TITLE
W/L Sorting not working properly

### ISSUE THREAD

**Issue by Reithan** [Razviar/mtga-pro-tracker#510]
**Describe the bug**
Sort by winrate isn't working properly

**To Reproduce**
1. Go to browse decks
2. Click on "W/L"

**Expected behavior**
Expect to see decks sorted by W/L

**Screenshots**
![image](https://user-images.githubusercontent.com/7475701/65820723-5024f000-e1e1-11e9-9fa5-cc269baf5d92.png)

**Additional context**
None

**Comment by Razviar** [comment]
Thanks for reporting, it's fixed
