### ISSUE TITLE
Can't Import decks from MTG Arena.Pro.

### ISSUE THREAD

**Issue by flick1234** [Razviar/mtga-pro-tracker#511]
**Describe the bug**
When importing a deck from MTG Arena.pro, it keeps getting an error. You can see on the image I attached.

**To Reproduce**
Go to a deck in MTGArena.Pro
Click on "Export deck"
Go to MTG Arena and import the deck
See the error

**Expected behavior**
The deck is imported properly.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/55934875/65824919-bcaff580-e29a-11e9-9adf-51e4bc3eb197.png)

**Comment by Razviar** [comment]
Fixed, try again

**Comment by flick1234** [comment]
Nope, still got the same error.
________________________________

**Comment by Razviar** [comment]
Can you give a link to specific deck with error?

**Comment by flick1234** [comment]
Actually I tried every deck and got the same error.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by flick1234** [comment]
I just tested it earlier and it worked. It's okay to close the thread now, thanks a lot you are the best.
________________________________

**Comment by Razviar** [comment]
Glad it worked out
