### ISSUE TITLE
Garruk not being exported correctly

### ISSUE THREAD

**Issue by iggraham** [Razviar/mtga-pro-tracker#512]
**Describe the bug**
Garruk, Cursed Huntsman is incorrectly getting exported as card number 270 of ELD rather than number 191.

**To Reproduce**
1. In the deckbuilder create a deck that has Garruk, Cursed Huntsman.
2. Export it in MTG Arena format.
3. Look at the exported result, which includes "1 Garruk, Cursed Huntsman (ELD) 270"
4. Try to import it into MTG Arena, and it will fail.

**Expected behavior**
MTG Arena Pro website should export the card as "1 Garruk, Cursed Huntsman (ELD) 191"

**Comment by Razviar** [comment]
Thanks for reporting, it's fixed
