### ISSUE TITLE
Murderous Rider not being exported correctly

### ISSUE THREAD

**Issue by iggraham** [Razviar/mtga-pro-tracker#513]
**Describe the bug**
Murderous Rider is incorrectly getting exported with an invalid name that is not recognized by MTG Arena.

**To Reproduce**
1. In the deckbuilder create a deck that has Murderous Rider.
2. Export it in MTG Arena format.
3. Look at the exported result, which includes "1 Murderous Rider // Swift End (ELD) 97"
4. Try to import it into MTG Arena, and it will fail.

**Expected behavior**
MTG Arena Pro website should export the card as "1 Murderous Rider (ELD) 97"

**Comment by Razviar** [comment]
Thanks for reporting, it's fixed
