### ISSUE TITLE
ELD Common Cards Not Tracking in Collection

### ISSUE THREAD

**Issue by lanfill** [Razviar/mtga-pro-tracker#514]
**Describe the bug**
Collection manager does not show how many Opt, Reave Soul, and Return To Nature you have in your collection. Right now I have a full set of all three of these cards, yet the collection is showing I have none:
![2019-09-30_1321](https://user-images.githubusercontent.com/635297/65905204-bcd8ef80-e385-11e9-8b34-36a8151ab9c3.png)

**To Reproduce**
1. Go to https://mtgarena.pro/collection/
2. Click on Set selection (ELD) filter by Commons, and No-Full Set.
3. Scroll down to Opt, Reave Soul, and Return To Nature
4. See no collection counts for Opt, Reave Soul, and Return To Nature

**Expected behavior**
I should have 4x of all three of these card

**Comment by Razviar** [comment]
Fixed, collection will update when you will get at least 1 new card.
