### ISSUE TITLE
"My decks" stack in loading icon

### ISSUE THREAD

**Issue by Saisur** [Razviar/mtga-pro-tracker#517]
"My decks" option in the page just stack in loading icon...

**Comment by Razviar** [comment]
Give a link to your profile please

**Comment by gravitycircle** [comment]
Same here, experiencing same error. I will PM you my profile link.

**Comment by gravitycircle** [comment]
Here you go:
mtga.cc/decks/?richard.124390

**Comment by Razviar** [comment]
Can't reproduce bug for now, I don't see endless load and any errors. Can you please take a screenshot of bugged screen with Chrome console open and JS errors visible in it?

**Comment by Saisur** [comment]
https://mtgarena.pro/u/Cesarmgc

**Comment by Razviar** [comment]
Try now, should be fixed
