### ISSUE TITLE
Can't get it to work at all!

### ISSUE THREAD

**Issue by FoxDracon** [Razviar/mtga-pro-tracker#518]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
the app refuses to load my cards from arena period even after all patches updates ie programs etc etc, If you are going to have a app that does nothing then say so and stop with your claims can help when does nothing at all!

**Comment by Razviar** [comment]
If you are looking for some help, please provide any details: what you tried to do and what happened
