### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by MayaPlays** [Razviar/mtga-pro-tracker#519]
The link to my decks is broken! I kinda need it for my stream to be working to show the decks I planned. When someone opens the link just opens a precon decklist that is not mine.
Here is the link -- > https://mtgarena.pro/decks/?MayaPlays

I had this problem 3 days ago and it was fixed. Now it is the same again. Why this keep happening?

**Comment by Razviar** [comment]
It's fixed. Issue re-occurred because we make some updates on site, and while updating things might get broken. Sorry about that.
