### ISSUE TITLE
Deck Converter has wrong IDs for some cards

### ISSUE THREAD

**Issue by ineffablebob** [Razviar/mtga-pro-tracker#522]
**Describe the bug**
Using the deck converter at https://mtgarena.pro/converter/ sometimes has wrong card IDs, which causes import into Arena to fail.

**To Reproduce**
I imported this deck (from SCG):
```
Maindeck:

Creatures
4 Edgewall Innkeeper
4 Foulmire Knight
4 Lovestruck Beast
4 Murderous Rider
3 Order of Midnight

Instants
3 Assassin's Trophy
4 Once Upon a Time

Legendary Creatures
4 Questing Beast
3 Rankle, Master of Pranks

Sorceries
2 Find
2 Legion's End

Basic Lands
5 Forest
8 Swamp

Lands
2 Fabled Passage
4 Overgrown Tomb
4 Temple of Malady

Sideboard:
3 Noxious Grasp
2 Veil of Summer
2 Massacre Girl
2 Davriel, Rogue Shadowmage
1 Vraska, Golgari Queen
3 Duress
1 Epic Downfall
1 Legion's End
```
It figured out the formatting fine and produced this:
```
3 Assassin's Trophy (GRN) 152
2 Find // Finality (GRN) 225
4 Overgrown Tomb (GRN) 253
2 Legion's End (M20) 106
4 Temple of Malady (M20) 254
4 Foulmire Knight (ELD) 90
3 Order of Midnight (ELD) 99
4 Lovestruck Beast (ELD) 299
3 Rankle, Master of Pranks (ELD) 356
8 Swamp (ELD) 258
5 Forest (ELD) 266
4 Murderous Rider (ELD) 97
4 Edgewall Innkeeper (ELD) 151
4 Once Upon a Time (ELD) 169
4 Questing Beast (ELD) 171
2 Fabled Passage (ELD) 244

1 Vraska, Golgari Queen (GRN) 213
2 Davriel, Rogue Shadowmage (WAR) 83
2 Massacre Girl (WAR) 99
3 Duress (M20) 97
1 Legion's End (M20) 106
3 Noxious Grasp (M20) 110
2 Veil of Summer (M20) 198
1 Epic Downfall (ELD) 85
```
But importing this into Arena fails with no error message. After some trial and error, I discovered that was happening because two of the card IDs - Rankle and Lovestruck Beast - are incorrect. Here's what they should be:
```
4 Lovestruck Beast (ELD) 165
3 Rankle, Master of Pranks (ELD) 101
```

Replacing those two IDs fixes the problem. 

**Expected behavior**
Generated deck should import correctly. My guess is this is a database issue - the card IDs are simply incorrect in whatever database you're using to generate the lines in the MTGA formatted list.

I suspect these aren't the only two incorrect IDs. You may want to do a full review of the card database.

**Comment by Razviar** [comment]
Thanks for noticing this, we'll fix it ASAP

**Comment by Razviar** [comment]
Fixed
