### ISSUE TITLE
Craft List not showing any decks

### ISSUE THREAD

**Issue by Brunhine** [Razviar/mtga-pro-tracker#524]
Decks have been added to craft list, but are not shown when searching for them via Craft List filter

![image](https://user-images.githubusercontent.com/828357/66539246-3ab29e80-eadc-11e9-957d-0236682de67c.png)

![image](https://user-images.githubusercontent.com/828357/66539295-56b64000-eadc-11e9-98b6-c8f67b06aa4a.png)

**Comment by Razviar** [comment]
Fixed
