### ISSUE TITLE
Card Collection Data incorrect from recent events

### ISSUE THREAD

**Issue by corvettejoe** [Razviar/mtga-pro-tracker#529]
**Describe the bug**
I was about to start drafting this weekend and wanted to see my before/after collection for the new set Throne of Eldraine.

I have roughly 30-40 cards from the set, as I have not opened any packs or anything yet. I only have the daily ICR cards and cards rewarded from the Brawl event.

Yet, it shows I have 116/287 singles and 201/1148 of the entire playset.
Looking through the cards displayed in my collection on MTGArena.Pro, it appears that it has grabbed all of the Brawl Decks from the Brawl Event a couple of weeks ago.

Since we were "temporarily" given the Brawl Decks during the event only, it appears that it captured that as actually being in my Collection. I certainly don't have any of these cards when looking in Arena.

There doesn't appear to be a way to remove cards from my MTGArena.Pro collection either, or even a "resync" just my collection data (I don't want to nuke my entire account).

The Collection manager has a "manual edit" option (left-click to remove, right-click to add), but right clicking only brings up the web browser menu, and left clicking tries to open the individual card's info page, which usually just crashes (RETRY/STOP/Reload Page error).

I tried this with both Firefox and Chrome (both latest versions)

**Comment by Razviar** [comment]
Thanks for noticing this, patch have been applied. With next card gained collection will update to actual state.

**Comment by Razviar** [comment]
Bug have been resolved.

**Comment by corvettejoe** [comment]
Wow, I wasn't expecting a response back. I was just doing due diligence and
reporting issues.

Awesome work! Everything looks great. Much respect for you as a developer
who cares about your work.

I've been using your tracker since I started playing again earlier this
year and have found it to be the most powerful for pure data. Nothing else
really comes close.
