### ISSUE TITLE
Owned cards in MTGA collection, missing in MTGAPro?

### ISSUE THREAD

**Issue by Ezelmannen** [Razviar/mtga-pro-tracker#530]
**Describe the bug**
I've gained, as an ICR I think, a second copy of "The Circle of Loyalty".
This shows up fine in MTGA but MTGAPro have missed it somehow.

Isn't there a way to make MTGAPro recheck once whole collection perhaps?
I tried Manual Re-Sync which sound like it might be the thing to do just that, but that didn't seem to help.

![image](https://user-images.githubusercontent.com/28021692/66699918-6f487500-eceb-11e9-9af1-64fd7841b687.png)

**Comment by Razviar** [comment]
Bug have been resolved. With next card gained collection will update to actual state.
