### ISSUE TITLE
Can't add new deck from converter

### ISSUE THREAD

**Issue by ghigio** [Razviar/mtga-pro-tracker#535]
**Describe the bug**
I have saved a new deck from the converter but that deck doesn't appear in the "my deck" section.

**To Reproduce**
1. Go to Deck converter section
2. Paste a new deck
3. Scroll down to Assign a new name and put some text in.
4. Message success appear
5. Go to My deck section
6. The new deck doesn't show inside the list (even if i change the filters)

**Expected behavior**
The new deck have to appear in my deck section

**Additional context**
It's happened in Firefox and Chrome on a PC and on Chrome on mobile

**Comment by Razviar** [comment]
I just imported this deck https://mtgarena.pro/decks/twilight-abzan-hero assigned name and got it rendering in My Decks section. So it's probably problem with specific deck. Can you post here your username (link to your profile) and decklist you are trying to import, I'll look into it.

**Comment by ghigio** [comment]
Sure!
https://mtgarena.pro/u/sevelt

And here the list i have taken from mtggoldfish (
https://www.mtggoldfish.com/deck/arena_download/2379611)

4 Bonecrusher Giant (ELD) 115
4 Gruul Spellbreaker (RNA) 179
4 Pelt Collector (GRN) 141
2 Robber of the Rich (ELD) 138
3 Skarrgan Hellkite (RNA) 114
4 Zhur-Taa Goblin (RNA) 215
3 Questing Beast (ELD) 171
8 Forest (XLN) 277
8 Mountain (XLN) 273
2 Castle Embereth (ELD) 239
4 Stomping Ground (RNA) 259
4 Once Upon a Time (ELD) 169
4 Shock (M19) 156
2 Embercleave (ELD) 120
4 Domri's Ambush (WAR) 192

3 Cindervines (RNA) 161
2 Flame Sweep (M20) 139
2 Domri, Anarch of Bolas (WAR) 191
2 Sarkhan the Masterless (WAR) 143
3 Claim the Firstborn (ELD) 118
3 Lava Coil (GRN) 108

Thank you

Il giorno ven 18 ott 2019 alle ore 14:08 Razviar <notifications@github.com>
ha scritto:

**Comment by Razviar** [comment]
The reason found: this deck contains "4 Shock (M19) 156" which is non-standard reprint of the card. That is why your deck is marked as 'Historic'. You can see it when you switch to "my historic" mode https://mtgarena.pro/decks/?my-historic

Meanwhile we are working on auto-replacement of non-standard reprints with standard cards if available.

**Comment by Razviar** [comment]
Patch implemented, now import will assume the latest version of card reprint if original one is not Standard.
