### ISSUE TITLE
Not seeing my name on Mythic Leaderboard and I´m #500

### ISSUE THREAD

**Issue by DrVaporeso** [Razviar/mtga-pro-tracker#537]
Hi! I´m #547 in the Mythic Leaderboard right now, few days ago i was checking the concordance between the game and the leaderboard, but somehow i couldn´t find me anymore. This is constructed by the way. I hit Mythic top since like 2 weeks. 

Why is this disappearance?

Thank you!

**Comment by Razviar** [comment]
Leaderboard is incomplete and updated as soon as some of tracker user meet some of leaders in combat. This means you never met any of our tracker users.
