### ISSUE TITLE
Site not working via Edge

### ISSUE THREAD

**Issue by ImLAKI** [Razviar/mtga-pro-tracker#538]
**Describe the bug**
Hello guys, unfortunately site didn't work on Edge.

I tried to find out way how to change default opening of URL's for this site in other browser, but there is no option for windows for example via registry neighter in applicatin itself. 

In case of any question let me know. Thanks.

**To Reproduce**
Clicked in APP tools for deck URL. (Default browser is Edge)

**Expected behavior**
Page will load. 

**Screenshots**
[https://ibb.co/9WMdTGz](url)

**Comment by Razviar** [comment]
Edge doesn't support some modern JS standards like spread operators. And it's overall not recommended for daily usage browser, even Microsoft admitted that by making next version of Edge on Chromium basis. So we are not going to fix edge incompatibilities.
