### ISSUE TITLE
New Brawl Event not showing rewards

### ISSUE THREAD

**Issue by corvettejoe** [Razviar/mtga-pro-tracker#539]
Joining the new Brawl event today,  which shows up as "Brawl_Launch_20191024" in the rewards page, it doesn't show any rewards earned for Daily wins.

I got 2 x 50 gold and 2 x ICR while playing the event, but it's now showing in either the rewards page or the Profile for my game play today.

Also the past week, since the last update for MTGArenaPro I think? It has now shown my daily win ICR's on the profiles page either, but it does show correctly on the Rewards page.

**Comment by Razviar** [comment]
Fix will be implemented by 28th of October, please hold on till then

**Comment by corvettejoe** [comment]
To add to this in case it helps for some new information:

It isn't showing any rewards on regular Play sessions either. I did not see my ICR for today, nor any of the cards from the free booster pack I opened. This is in the Rewards page as well as the Profile page.

Thanks for responding to these issues, it's great to see active developers in action! Thanks for all the hard and awesome work!

**Comment by Razviar** [comment]
Fix implemented.
