### ISSUE TITLE
No data details since last update (v1.8.9)

### ISSUE THREAD

**Issue by dcpc007** [Razviar/mtga-pro-tracker#541]
**Describe the bug**
In Rewards, there ony empty events since the 2 last updates (24/10/2019) 

![image](https://user-images.githubusercontent.com/847516/67575121-273e3f00-f73c-11e9-9265-fa602aac1622.png)

Already done :
* restart the client and no update messages
* manual re-sync

**Comment by Razviar** [comment]
Fix will be implemented by 28th of October, please hold on till then

**Comment by soulb1ight** [comment]
This is probably related, but the last 11 boosters that I've opened are showing up as "Undefined."

![2019-10-25](https://user-images.githubusercontent.com/11745280/67599436-6ffaf580-f746-11e9-981f-6316f9db2273.png)

**Comment by soulb1ight** [comment]
This is probably related, but the last 11 boosters that I've opened are showing up as "Undefined."

![2019-10-25 crop](https://user-images.githubusercontent.com/11745280/67599636-e13aa880-f746-11e9-8bb7-e4bfccfbcd7d.png)

**Comment by Razviar** [comment]
Yep, related, and will be fixed by 28th as well. Sorry for the wait

**Comment by Razviar** [comment]
Fix implemented
