### ISSUE TITLE
It no longer tracks my ICR on the rewards tab

### ISSUE THREAD

**Issue by mynamesbrad** [Razviar/mtga-pro-tracker#542]
**Describe the bug**
When I play the game and get my daily ICRs, I like to check to see if it is a duplicate. I go to your website and I check and nothing is there noting I even received the ICR. I open boosters and it shows if the cards are a duplicate or not. Also, when I play the standard event and receive rewards, they also do not show up on the rewards received. Everything appears in my collection and it also records my matches and decks. It keeps track of my gems and money.

**To Reproduce**
1.  https://mtgarena.pro
2. Click on 'rewards'
3. Scroll down to the latest rewards received.
4. See error: No rewards were recorded from ICR

**Expected behavior**
I expected to see my ICR and I do not see them
![Screenshot (24)](https://user-images.githubusercontent.com/57064981/67635084-cb38ff00-f890-11e9-9aba-fb9439769156.png)
![Screenshot (24)](https://user-images.githubusercontent.com/57064981/67635090-d5f39400-f890-11e9-984a-57c804a4e806.png)
![Screenshot (24)](https://user-images.githubusercontent.com/57064981/67635091-dc820b80-f890-11e9-8562-26d1460ac044.png)

**Screenshots**

**Additional context**

**Comment by Razviar** [comment]
The reason of missing ICR and other inventory updates is found, but implementation will take a day or two since log format changes are substantial. We'll tweet when it's ready. Good news is no tracker app update will be needed, all will be updated server-side.

**Comment by Razviar** [comment]
ICR are back online.
