### ISSUE TITLE
Card Time Wipe  doesn't correct mana price

### ISSUE THREAD

**Issue by 5h1k4r1** [Razviar/mtga-pro-tracker#543]
also Enter the God-Eternals

**Comment by Razviar** [comment]
What is wrong? I can't find any mistakes, please elaborate.

**Comment by 5h1k4r1** [comment]
Ok, now i see you just show which mana colour may used by that card, so
what is the numbers near colors?

ср, 30 окт. 2019 г., 18:58 Razviar <notifications@github.com>:

**Comment by Razviar** [comment]
It's colorless mana number (you can use land of any color). Read this https://mtg.gamepedia.com/Mana to get better understanding of mana system in MTGA.

**Comment by 5h1k4r1** [comment]
Yeah, that's what I am talking about. Big thanks!

чт, 31 окт. 2019 г., 2:42 Razviar <notifications@github.com>:
