### ISSUE TITLE
I go for days at a time with nothing being tracked.

### ISSUE THREAD

**Issue by napoearth** [Razviar/mtga-pro-tracker#546]
**Describe the bug**
Currently my matches and rewards list is missing Oct 24 and 25 and everything after the 28th.

**To Reproduce**
Open website and click matches or rewards

**Expected behavior**
I expect every day to have been tracked.

**Screenshots**
![gap between 23rd and 26th](https://user-images.githubusercontent.com/44950690/67992267-05e0c580-fc0a-11e9-9cd4-82fb70589bc3.jpg)

![missing after 28th](https://user-images.githubusercontent.com/44950690/67992278-142ee180-fc0a-11e9-9bdb-8ea2763d0830.jpg)

**Additional context**
I've tried scanning old logs but nothing changes.

**Comment by Razviar** [comment]
This is wired floating bug affecting small portion of our users. Try full reset button on the app. It will not wipe anything in account, but might help restore tracking
