### ISSUE TITLE
Tracker stuck in "Reading long log"

### ISSUE THREAD

**Issue by realJohnDoe** [Razviar/mtga-pro-tracker#547]
While playing today, the tracker got stuck in status 'Reading long log' and does not track any games anymore. I tried resetting it but the problem appears again after I enter my token. Any ideas?

**Comment by Razviar** [comment]
You need to manually remove game log from AppData\LocalLow\Wizards Of The Coast\MTGA folder and reset both tracker AND the game.

**Comment by realJohnDoe** [comment]
Thanks, that worked :)
