### ISSUE TITLE
No decks displaying

### ISSUE THREAD

**Issue by Augmented35** [Razviar/mtga-pro-tracker#548]
![mtga error](https://user-images.githubusercontent.com/55924420/68527393-8c6e6480-02e6-11ea-90f6-8e283a6204e1.png)

1. Log in with google
2. Go to deck browser
3. Click on any deck
4. Error in the image appears

This error has been present for a week now. Due to the text on the error I waited but it seems to be default text.

**Comment by Razviar** [comment]
Let me know your username on site (link to your account would be best).

Also, we are having troubles with replication of this bug, so please click on  this link https://pastenow.ru/363aa705062ab5abcc51461bce3b95c3 and make another screen of the actual code with error, so we could locate it.

**Comment by Augmented35** [comment]
![code vendor](https://user-images.githubusercontent.com/55924420/68529539-065f1780-0300-11ea-88ec-f4839c4f3a70.PNG)
It's throwing me to that section of the code when I click the vendor link.  I can't upload the .js here, do you have a dropbox of a sorts? 
https://www.dropbox.com/s/who3yvjpqyc7fdb/vendor.79b2cd975e49fb68b287.js?dl=0

This is my profile. https://mtgarena.pro/u/nikola%20mitkovic

The gmail account I use to log in is ektim666@gmail.com

**Comment by Augmented35** [comment]
![moved](https://user-images.githubusercontent.com/55924420/68529736-ce58d400-0301-11ea-88b6-6cbe5d79e542.PNG)

This is how decklist browser looks for me, I just did a full clear of Cache and Cookies as well, the issue still persists. Could the distorted decklist view have anything to do with it? Or is it a separate issue? It does not bother me as much as it is purely cosmetic it appears.

**Comment by Razviar** [comment]
I can assume it's because of space in your nickname. For now you could experimentally change your nickname to anything without space (even nikola.mitkovic) here: https://mtgarena.pro/edit-profile/

We will investigate this issue and fix it soon, but for faster solution you can try that.

**Comment by Razviar** [comment]
Also, I would ask you to open console and open tabs as shown on this screenshot:
https://pastenow.ru/41f4a3505f876c06f1e2750552c45429

To get all needed calls you need to open console first, and then load website/

**Comment by Augmented35** [comment]
Well changing the nickname worked. As I used google to log in it automatically filled it in, never bothered to change it, changed it to one word now and it fixed all the issues.

**Comment by Augmented35** [comment]
Ahhh, I changed the username before checking the console error.
![no space](https://user-images.githubusercontent.com/55924420/68531359-948fc980-0311-11ea-8e90-c93f5e5b8b8c.PNG)

Now when I change it back to a name with a space it does not reproduce the error again. Thanks for your help anyway!
