### ISSUE TITLE
GRN_Quick_Draft doesn't show up on Events page

### ISSUE THREAD

**Issue by Lila-Blume** [Razviar/mtga-pro-tracker#549]
My last Guilds of Ravnica ranked draft was tracked correctly (shows up in matches etc.) but isn't displayed on the Events page. https://mtgarena.pro/events/
This is the first time ever I did a GRN draft so I don't know if it's a problem with this specific draft or the general event label.

**Comment by Razviar** [comment]
It might be general issue with draft tracking. We are investigating

**Comment by Lila-Blume** [comment]
Quick update, as I'm playing GRN Draft again right now. This one is showing up now.

**Comment by Razviar** [comment]
Investigation shown that it was some kind of random glitch, overall events are being recorded normally. We'll keep monitoring if new issues will arise.
