### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by MayaPlays** [Razviar/mtga-pro-tracker#552]
As I open my decklists individually, an error pops up "Ouch! Something went wrong and we were unable to render this page properly. We already logged this event and will look into this issue ASAP. Please try to reload page later!".
I think it's only for me because other people can see it but I wonder why this happens and I'm afraid that it's not the only one

**Comment by Razviar** [comment]
Hello! Please post a link to your account and let me know how are you logging in (social or just login and password). This is known issue, we still can't find out why is happening for small part of logged in users.

**Comment by Razviar** [comment]
Nevermind. Now it's found and fixed. Sorry about this inconvenience.
