### ISSUE TITLE
Rewards page not updating

### ISSUE THREAD

**Issue by corvettejoe** [Razviar/mtga-pro-tracker#559]
A quick heads up for an issue I noticed this morning:  After the latest update yesterday to 2.1.10 the rewards page is not being updated.

I enjoy using it for tracking what gets vaulted, double checking gold rewards, etc for my spreadsheets.

Also, I really enjoy the new client interface, looks much nicer, I like how it matches the website too. Nice work!!

**Comment by Razviar** [comment]
Rewards tracking is fixed. To get it tracked, just restart your tracker (Stop Tracker in the app interface and launch again then)

**Comment by corvettejoe** [comment]
Awesome, thanks so much.
Let me know if there's anything I could ever do to help with the project if
needed.
