### ISSUE TITLE
"No log file found"

### ISSUE THREAD

**Issue by Guruhoops** [Razviar/mtga-pro-tracker#563]
Good afternoon,
I've installed the new version but I'm getting the above error.  I've tried manually locating the log but that hasn't helped.  The location I've used is:
C:\Program Files (x86)\Wizards of the Coast\MTGA\MTGA_Data\Logs\Logs
Please let me know what I'm doing wrong :o)
John

**Comment by Guruhoops** [comment]
I've updated to 2.0.11 but this hasn't changed anything.

I've also noticed that the "Start with Windows" and "Start Minimized" settings change back to on when the program restarts.

**Comment by Razviar** [comment]
You should locate log in appdata folder, not in program files.AppData\LocalLow\Wizards Of The Coast\MTGA

**Comment by Guruhoops** [comment]
Thanks for your reply Razviar.

There are no logs in the location you've provided.  The location I mentioned is where ones I have used the "Scan old logs" feature for.  It is also where logs are created when I start Magic Arena.

**Comment by Razviar** [comment]
You need to locate output_log.txt file then. It's main log output of mtga. Files you've mentioned are just supplementary

**Comment by Guruhoops** [comment]
Got it, thanks Razviar.  Perhaps I missed it, or there wasn't one when I checked, when you originally gave me the location becuase there is a log file there now.  :o)
Is there a way to scan old logs to import the missing information?  Looking at the Rewards page I have a gap from the 21st until just now.

**Comment by Razviar** [comment]
For now it's not possible. In the next release we'll add old logs scanner

**Comment by Guruhoops** [comment]
Thanks very much for your help and for the Tracker.
