### ISSUE TITLE
The exe doesn t run 

### ISSUE THREAD

**Issue by francescopasini77** [Razviar/mtga-pro-tracker#59]
**Describe the bug**
When i run the installer it report me this textbox 
"warning 1946. property
'system.appusermodel.ToastActivatorCLSID' for shortcut
'MTGA Pro Traker.ink' could not be set."
the instalation end and the exe doesnt run even if i double click it 

**To Reproduce**
1. Go to the instalation.zip
2. Click on start and install
3.""
4. See error warning 1946. property
'system.appusermodel.ToastActivatorCLSID' for shortcut
'MTGA Pro Traker.ink' could not be set.

**Expected behavior**
I expected to install correctly and run the .exe

**Screenshots**
![pro traker](https://user-images.githubusercontent.com/43914921/46574712-0c215580-c9a8-11e8-8fd0-58b3dbee75bd.png)

**Additional context**

**Comment by Razviar** [comment]
This warning normal installer behavior for Windows 8. Just click on and continued installation

**Comment by francescopasini77** [comment]
yes, it does but the .exe doent run even if i double click

**Comment by Razviar** [comment]
Make sure you have .net 4.6 or higher https://www.microsoft.com/net/download/dotnet-framework-runtime/net462
