### ISSUE TITLE
Open sourcing of the project

### ISSUE THREAD

**Issue by pedro-walter** [Razviar/mtga-pro-tracker#63]
Any reason why this project has a closed source code? The community could contribute with bug fixes, features, etc.

**Comment by Razviar** [comment]
For now we are sticking to closed source model because it's better suits our needs. If situation changes in future, we'll consider opening source.

**Comment by martinstark** [comment]
+1 to open source, and using github release system :)

**Comment by Razviar** [comment]
Yeah, guys, opensource is great, but not this time.
