### ISSUE TITLE
Improve Quick Deck Rename Functionality

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#66]
Move the Quick Edit pencil icon from column 1 to column 2 after the deck name, visible when hovering over the deck.

![image](https://user-images.githubusercontent.com/4083812/46735660-8a7b4180-cc9f-11e8-8049-b0649b1d0867.png)

Rework the UI and visual appeal of the Quick Rename modal dialog:
* Deck Field should contain the current deck name, not use the unreadable grey hint text
* Add YouTube video url field. 

![image](https://user-images.githubusercontent.com/4083812/46735698-aed71e00-cc9f-11e8-8283-d221d7645745.png)

**Comment by Razviar** [comment]
Done
