### ISSUE TITLE
Searching Decks by Included Card doesn't remember the card, doesn't filter the deck list.

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#7]
Searching Decks by Included Card doesn't remember the card, doesn't filter the deck list.

**Comment by Razviar** [comment]
> This really needs fixed, searching by card name 90% of the time just doesn't work at all.

Can you please provide me steps to replicate the issue? I just checked and search by card and it worked fine

**Comment by tapr00t** [comment]
Messing around with the filter options and somehow got this no results found for no real filter options selected?
![image](https://user-images.githubusercontent.com/3802245/51503831-5ee21a00-1dab-11e9-8ac7-de0fbbfcb627.png)
