### ISSUE TITLE
No immediate tracking after MTGA client update

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#72]
On 12/10 there was MTGA client update. I was running Pro Tracker while the client updated, then started it and some sessions were not tracked. I had to kill the Pro tracker, start it again, refreshed the token just in case, for the Pro tracker to continue tracking. 

Some people complaining about missing tracking may have it due to client update on the same day prior that.

**Comment by Razviar** [comment]
Posted recommendations on Twitter and Reddit to do manual reset.
Actual fix will be integrated into general stability update, planned to be released in this month.
