### ISSUE TITLE
While in Favorite Decks, don't show personal deck shorturl

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#73]
![image](https://user-images.githubusercontent.com/4083812/46906582-6e310c00-cf0e-11e8-8923-114fe4198183.png)

**Comment by apoapostolov** [comment]
It's fixed, but the link shows in Favorite Decks. I am reopening and rewording to reuse the issue.

**Comment by Razviar** [comment]
Uploaded patch, will take some time to propagate through cahce

**Comment by apoapostolov** [comment]
Will confirm later and close.

**Comment by apoapostolov** [comment]
Fixed.
