### ISSUE TITLE
Reorder buttons under deck list in Deck Page by usability

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#77]
Current order: 
![image](https://user-images.githubusercontent.com/4083812/46907395-5bbccf80-cf1a-11e8-8d5c-53871c665486.png)

I suggest the following by order of actionable response, and by frequency of usability (right to left)

1st row, most actionable - Edit Deck / Export Deck
2nd row, user feedback - Vote Deck / Favorite Deck
3rd row, less actionable - For Stream / Copy Link
4rd row, non actionable - Views / Sample Hand

**Comment by Razviar** [comment]
Done
