### ISSUE TITLE
Switching to Favorite Decks may be broken

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#82]
The link: https://mtgarena.pro/decks/#fav opens in fresh tab, but switching from My Decks to Favorite Decks in the same tab is broken.

When switching back from Favorite to My, causes an empty list with just one entry remaining from Favorite Decks. May be related bug to #80 

While at it, rename Favo**u**rite to Favorite for the US-centric demographic.

**Comment by Razviar** [comment]
Fixed. And added nice switcher button on the menu
