### ISSUE TITLE
Messed up multiple accounts handling

### ISSUE THREAD

**Issue by PincoPallo01** [Razviar/mtga-pro-tracker#83]
When using 2 different accounts for MTG Arena (and, obviously, 2 different accounts for MTGArena Pro and 2 token with tracker) the tracker often sends data (decks, collection, acquired cards, status as vault and gold) from the NOT connected account to the connected one.
This happens even if I stop the tracker after I disconnect account 1 and reopen it only after logged in account 2.
I Tried anything I can think of... keeping the tracker active between logout/login accounts, closing it after logout and relaunching after login and even stop tracker, close MTGA then relaunch MTGA and the tracker.
It does not happen 100% of the times, but it does happen a lot... at least 50%... it seems like a thread read player info BEFORE the tracker realize wich account is active.

**Comment by Razviar** [comment]
This issue will be addressed in version 1.3.3 planned to be released till the end of the month

**Comment by PincoPallo01** [comment]
Thank you for the fast response :)
BTW: Great job with the tracker !

**Comment by apoapostolov** [comment]
@Razviar should I reopen the bug since it it not yet deployed?

**Comment by Razviar** [comment]
I already did.

**Comment by Razviar** [comment]
Just released v.1.3.3 fixes that

**Comment by Memoryadept** [comment]
I am having the same problem. When my brother did his account on the site. He had the same MTGA nick even though he has a different account. mtgaarena.pro shows that he has the same cards as I do.

**Comment by Razviar** [comment]
Issue still persists, will try to fix it in the next release

**Comment by Razviar** [comment]
v.1.7.7 is released, which should hopefully remedy this issue. Fingers crossed.
