### ISSUE TITLE
Center Need column in Deck Lists. 

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#86]
Since you removed needed boosters to reach a deck (that really isn't that useful these days as people already have visual feedback in-game how many boosters until a WC) how about centering the needed WC in the column, they are off side because the now removed number on the left.

![image](https://user-images.githubusercontent.com/4083812/46920717-23d98900-cffb-11e8-8199-ee2207862060.png)

**Comment by Razviar** [comment]
Finally it's done
