### ISSUE TITLE
Improved Deck Builder UI - better visibility of meta content [mockup inside]

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#87]
The current Deck Builder is fine, except:
* The description and metadata are hidden behind hard to find modal dialog and only exposed when saving a deck, and some people don't save decks because they are auto-saved anyways. 
* The new compact menu actually makes it harder to find where to go to describe your deck

Suggestion:
Remove the keywords field (it's not very useful when building a deck, it's more useful on individual deck pages where you are not aware of the deck and want to study its synergies) and instead use the space for exposing important metadata fields.

Mockup below:

* Describe Deck button will open a modal dialog as description has be written in large enough writing area, not compact one-liners that we can fit in this space. 

![image](https://user-images.githubusercontent.com/4083812/46920954-0e199300-cffe-11e8-9609-3f7a5e909143.png)

**Comment by Razviar** [comment]
Done
