### ISSUE TITLE
Deck Content Missing in all My Decks 

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#92]
https://mtgarena.pro/decks/murmuring-murmurs/

![image](https://user-images.githubusercontent.com/4083812/47000057-078b3880-d130-11e8-80d8-fba4824c7331.png)

https://mtgarena.pro/decks/green-stompy-135/

![image](https://user-images.githubusercontent.com/4083812/47000092-2a1d5180-d130-11e8-8697-8ed284da268c.png)

**Comment by Razviar** [comment]
Fixed, may need ctrl+f5
