### ISSUE TITLE
Featured Decks

### ISSUE THREAD

**Issue by apoapostolov** [Razviar/mtga-pro-tracker#95]
* Whole new deck table page called Featured Decks featuring decks with (a) video; (b) description > 400 characters; (c) any description with [[card tags]]
* Links below Front Page Deck lead to Featured Decks
* Below the Featured Decks header, one line text to tell users why these decks are featured and suggest better quality if they want them featured: _"Get your deck featured by adding YouTube video and a good detailed description using our card tags."_
* Featured Decks appear on Community Decks page with Quality icon before or after their name

![image](https://user-images.githubusercontent.com/4083812/47033892-99ba2d80-d17e-11e8-98f5-1f1005e082ef.png)

* Community Decks features 3-4 Featured Decks, then chronological all decks (featured and nonfeatured)

**Comment by Magican28** [comment]
If you set a filter (eg Decks with Disinformation Campaign) after you view one deck and head back to the deck explorer the filter evaporates, and all possible decks appear again. 

It would be good if the filter persisted by default, with a method of turning it off

**Comment by Razviar** [comment]
Done
